<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Listvend', 'premium');

/**
 * BaseListvend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $codigo
 * @property string $nombre
 * @property string $direccion
 * @property float $comision
 * @property string $sector
 * @property date $fecha
 * @property string $cedula
 * @property string $telefonos
 * @property string $telefono_movil
 * @property float $cobranza
 * @property string $expediente
 * @property string $codigocont
 * @property float $activcomi
 * @property float $desde1
 * @property float $desde2
 * @property float $desde3
 * @property float $desde4
 * @property float $desde5
 * @property float $desde6
 * @property float $hasta1
 * @property float $hasta2
 * @property float $hasta3
 * @property float $hasta4
 * @property float $hasta5
 * @property float $hasta6
 * @property float $prccomi1
 * @property float $prccomi2
 * @property float $prccomi3
 * @property float $prccomi4
 * @property float $prccomi5
 * @property float $prccomi6
 * @property float $bono1
 * @property float $bono2
 * @property float $bono3
 * @property float $bono4
 * @property float $bono5
 * @property float $bono6
 * @property float $utilvent
 * @property float $aplicaramendoc
 * @property float $cobdesde1
 * @property float $cobdesde2
 * @property float $cobdesde3
 * @property float $cobdesde4
 * @property float $cobdesde5
 * @property float $cobdesde6
 * @property float $cobhasta1
 * @property float $cobhasta2
 * @property float $cobhasta3
 * @property float $cobhasta4
 * @property float $cobhasta5
 * @property float $cobhasta6
 * @property float $cobprccomi1
 * @property float $cobprccomi2
 * @property float $cobprccomi3
 * @property float $cobprccomi4
 * @property float $cobprccomi5
 * @property float $cobprccomi6
 * @property float $cobbono1
 * @property float $cobbono2
 * @property float $cobbono3
 * @property float $cobbono4
 * @property float $cobbono5
 * @property float $cobbono6
 * @property float $valoraporcent
 * @property float $no_comi_art
 * @property float $art_prc_1
 * @property float $art_prc_2
 * @property float $art_prc_3
 * @property float $art_prc_4
 * @property float $art_prc_5
 * @property float $art_prc_6
 * @property float $art_prc_7
 * @property string $email
 * @property string $campo1
 * @property string $campo2
 * @property string $campo3
 * @property string $campo4
 * @property string $campo5
 * @property string $claverest
 * @property integer $es_servidor
 * 
 * @method string   getIdEmpresa()      Returns the current record's "id_empresa" value
 * @method string   getAgencia()        Returns the current record's "agencia" value
 * @method string   getCodigo()         Returns the current record's "codigo" value
 * @method string   getNombre()         Returns the current record's "nombre" value
 * @method string   getDireccion()      Returns the current record's "direccion" value
 * @method float    getComision()       Returns the current record's "comision" value
 * @method string   getSector()         Returns the current record's "sector" value
 * @method date     getFecha()          Returns the current record's "fecha" value
 * @method string   getCedula()         Returns the current record's "cedula" value
 * @method string   getTelefonos()      Returns the current record's "telefonos" value
 * @method string   getTelefonoMovil()  Returns the current record's "telefono_movil" value
 * @method float    getCobranza()       Returns the current record's "cobranza" value
 * @method string   getExpediente()     Returns the current record's "expediente" value
 * @method string   getCodigocont()     Returns the current record's "codigocont" value
 * @method float    getActivcomi()      Returns the current record's "activcomi" value
 * @method float    getDesde1()         Returns the current record's "desde1" value
 * @method float    getDesde2()         Returns the current record's "desde2" value
 * @method float    getDesde3()         Returns the current record's "desde3" value
 * @method float    getDesde4()         Returns the current record's "desde4" value
 * @method float    getDesde5()         Returns the current record's "desde5" value
 * @method float    getDesde6()         Returns the current record's "desde6" value
 * @method float    getHasta1()         Returns the current record's "hasta1" value
 * @method float    getHasta2()         Returns the current record's "hasta2" value
 * @method float    getHasta3()         Returns the current record's "hasta3" value
 * @method float    getHasta4()         Returns the current record's "hasta4" value
 * @method float    getHasta5()         Returns the current record's "hasta5" value
 * @method float    getHasta6()         Returns the current record's "hasta6" value
 * @method float    getPrccomi1()       Returns the current record's "prccomi1" value
 * @method float    getPrccomi2()       Returns the current record's "prccomi2" value
 * @method float    getPrccomi3()       Returns the current record's "prccomi3" value
 * @method float    getPrccomi4()       Returns the current record's "prccomi4" value
 * @method float    getPrccomi5()       Returns the current record's "prccomi5" value
 * @method float    getPrccomi6()       Returns the current record's "prccomi6" value
 * @method float    getBono1()          Returns the current record's "bono1" value
 * @method float    getBono2()          Returns the current record's "bono2" value
 * @method float    getBono3()          Returns the current record's "bono3" value
 * @method float    getBono4()          Returns the current record's "bono4" value
 * @method float    getBono5()          Returns the current record's "bono5" value
 * @method float    getBono6()          Returns the current record's "bono6" value
 * @method float    getUtilvent()       Returns the current record's "utilvent" value
 * @method float    getAplicaramendoc() Returns the current record's "aplicaramendoc" value
 * @method float    getCobdesde1()      Returns the current record's "cobdesde1" value
 * @method float    getCobdesde2()      Returns the current record's "cobdesde2" value
 * @method float    getCobdesde3()      Returns the current record's "cobdesde3" value
 * @method float    getCobdesde4()      Returns the current record's "cobdesde4" value
 * @method float    getCobdesde5()      Returns the current record's "cobdesde5" value
 * @method float    getCobdesde6()      Returns the current record's "cobdesde6" value
 * @method float    getCobhasta1()      Returns the current record's "cobhasta1" value
 * @method float    getCobhasta2()      Returns the current record's "cobhasta2" value
 * @method float    getCobhasta3()      Returns the current record's "cobhasta3" value
 * @method float    getCobhasta4()      Returns the current record's "cobhasta4" value
 * @method float    getCobhasta5()      Returns the current record's "cobhasta5" value
 * @method float    getCobhasta6()      Returns the current record's "cobhasta6" value
 * @method float    getCobprccomi1()    Returns the current record's "cobprccomi1" value
 * @method float    getCobprccomi2()    Returns the current record's "cobprccomi2" value
 * @method float    getCobprccomi3()    Returns the current record's "cobprccomi3" value
 * @method float    getCobprccomi4()    Returns the current record's "cobprccomi4" value
 * @method float    getCobprccomi5()    Returns the current record's "cobprccomi5" value
 * @method float    getCobprccomi6()    Returns the current record's "cobprccomi6" value
 * @method float    getCobbono1()       Returns the current record's "cobbono1" value
 * @method float    getCobbono2()       Returns the current record's "cobbono2" value
 * @method float    getCobbono3()       Returns the current record's "cobbono3" value
 * @method float    getCobbono4()       Returns the current record's "cobbono4" value
 * @method float    getCobbono5()       Returns the current record's "cobbono5" value
 * @method float    getCobbono6()       Returns the current record's "cobbono6" value
 * @method float    getValoraporcent()  Returns the current record's "valoraporcent" value
 * @method float    getNoComiArt()      Returns the current record's "no_comi_art" value
 * @method float    getArtPrc1()        Returns the current record's "art_prc_1" value
 * @method float    getArtPrc2()        Returns the current record's "art_prc_2" value
 * @method float    getArtPrc3()        Returns the current record's "art_prc_3" value
 * @method float    getArtPrc4()        Returns the current record's "art_prc_4" value
 * @method float    getArtPrc5()        Returns the current record's "art_prc_5" value
 * @method float    getArtPrc6()        Returns the current record's "art_prc_6" value
 * @method float    getArtPrc7()        Returns the current record's "art_prc_7" value
 * @method string   getEmail()          Returns the current record's "email" value
 * @method string   getCampo1()         Returns the current record's "campo1" value
 * @method string   getCampo2()         Returns the current record's "campo2" value
 * @method string   getCampo3()         Returns the current record's "campo3" value
 * @method string   getCampo4()         Returns the current record's "campo4" value
 * @method string   getCampo5()         Returns the current record's "campo5" value
 * @method string   getClaverest()      Returns the current record's "claverest" value
 * @method integer  getEsServidor()     Returns the current record's "es_servidor" value
 * @method Listvend setIdEmpresa()      Sets the current record's "id_empresa" value
 * @method Listvend setAgencia()        Sets the current record's "agencia" value
 * @method Listvend setCodigo()         Sets the current record's "codigo" value
 * @method Listvend setNombre()         Sets the current record's "nombre" value
 * @method Listvend setDireccion()      Sets the current record's "direccion" value
 * @method Listvend setComision()       Sets the current record's "comision" value
 * @method Listvend setSector()         Sets the current record's "sector" value
 * @method Listvend setFecha()          Sets the current record's "fecha" value
 * @method Listvend setCedula()         Sets the current record's "cedula" value
 * @method Listvend setTelefonos()      Sets the current record's "telefonos" value
 * @method Listvend setTelefonoMovil()  Sets the current record's "telefono_movil" value
 * @method Listvend setCobranza()       Sets the current record's "cobranza" value
 * @method Listvend setExpediente()     Sets the current record's "expediente" value
 * @method Listvend setCodigocont()     Sets the current record's "codigocont" value
 * @method Listvend setActivcomi()      Sets the current record's "activcomi" value
 * @method Listvend setDesde1()         Sets the current record's "desde1" value
 * @method Listvend setDesde2()         Sets the current record's "desde2" value
 * @method Listvend setDesde3()         Sets the current record's "desde3" value
 * @method Listvend setDesde4()         Sets the current record's "desde4" value
 * @method Listvend setDesde5()         Sets the current record's "desde5" value
 * @method Listvend setDesde6()         Sets the current record's "desde6" value
 * @method Listvend setHasta1()         Sets the current record's "hasta1" value
 * @method Listvend setHasta2()         Sets the current record's "hasta2" value
 * @method Listvend setHasta3()         Sets the current record's "hasta3" value
 * @method Listvend setHasta4()         Sets the current record's "hasta4" value
 * @method Listvend setHasta5()         Sets the current record's "hasta5" value
 * @method Listvend setHasta6()         Sets the current record's "hasta6" value
 * @method Listvend setPrccomi1()       Sets the current record's "prccomi1" value
 * @method Listvend setPrccomi2()       Sets the current record's "prccomi2" value
 * @method Listvend setPrccomi3()       Sets the current record's "prccomi3" value
 * @method Listvend setPrccomi4()       Sets the current record's "prccomi4" value
 * @method Listvend setPrccomi5()       Sets the current record's "prccomi5" value
 * @method Listvend setPrccomi6()       Sets the current record's "prccomi6" value
 * @method Listvend setBono1()          Sets the current record's "bono1" value
 * @method Listvend setBono2()          Sets the current record's "bono2" value
 * @method Listvend setBono3()          Sets the current record's "bono3" value
 * @method Listvend setBono4()          Sets the current record's "bono4" value
 * @method Listvend setBono5()          Sets the current record's "bono5" value
 * @method Listvend setBono6()          Sets the current record's "bono6" value
 * @method Listvend setUtilvent()       Sets the current record's "utilvent" value
 * @method Listvend setAplicaramendoc() Sets the current record's "aplicaramendoc" value
 * @method Listvend setCobdesde1()      Sets the current record's "cobdesde1" value
 * @method Listvend setCobdesde2()      Sets the current record's "cobdesde2" value
 * @method Listvend setCobdesde3()      Sets the current record's "cobdesde3" value
 * @method Listvend setCobdesde4()      Sets the current record's "cobdesde4" value
 * @method Listvend setCobdesde5()      Sets the current record's "cobdesde5" value
 * @method Listvend setCobdesde6()      Sets the current record's "cobdesde6" value
 * @method Listvend setCobhasta1()      Sets the current record's "cobhasta1" value
 * @method Listvend setCobhasta2()      Sets the current record's "cobhasta2" value
 * @method Listvend setCobhasta3()      Sets the current record's "cobhasta3" value
 * @method Listvend setCobhasta4()      Sets the current record's "cobhasta4" value
 * @method Listvend setCobhasta5()      Sets the current record's "cobhasta5" value
 * @method Listvend setCobhasta6()      Sets the current record's "cobhasta6" value
 * @method Listvend setCobprccomi1()    Sets the current record's "cobprccomi1" value
 * @method Listvend setCobprccomi2()    Sets the current record's "cobprccomi2" value
 * @method Listvend setCobprccomi3()    Sets the current record's "cobprccomi3" value
 * @method Listvend setCobprccomi4()    Sets the current record's "cobprccomi4" value
 * @method Listvend setCobprccomi5()    Sets the current record's "cobprccomi5" value
 * @method Listvend setCobprccomi6()    Sets the current record's "cobprccomi6" value
 * @method Listvend setCobbono1()       Sets the current record's "cobbono1" value
 * @method Listvend setCobbono2()       Sets the current record's "cobbono2" value
 * @method Listvend setCobbono3()       Sets the current record's "cobbono3" value
 * @method Listvend setCobbono4()       Sets the current record's "cobbono4" value
 * @method Listvend setCobbono5()       Sets the current record's "cobbono5" value
 * @method Listvend setCobbono6()       Sets the current record's "cobbono6" value
 * @method Listvend setValoraporcent()  Sets the current record's "valoraporcent" value
 * @method Listvend setNoComiArt()      Sets the current record's "no_comi_art" value
 * @method Listvend setArtPrc1()        Sets the current record's "art_prc_1" value
 * @method Listvend setArtPrc2()        Sets the current record's "art_prc_2" value
 * @method Listvend setArtPrc3()        Sets the current record's "art_prc_3" value
 * @method Listvend setArtPrc4()        Sets the current record's "art_prc_4" value
 * @method Listvend setArtPrc5()        Sets the current record's "art_prc_5" value
 * @method Listvend setArtPrc6()        Sets the current record's "art_prc_6" value
 * @method Listvend setArtPrc7()        Sets the current record's "art_prc_7" value
 * @method Listvend setEmail()          Sets the current record's "email" value
 * @method Listvend setCampo1()         Sets the current record's "campo1" value
 * @method Listvend setCampo2()         Sets the current record's "campo2" value
 * @method Listvend setCampo3()         Sets the current record's "campo3" value
 * @method Listvend setCampo4()         Sets the current record's "campo4" value
 * @method Listvend setCampo5()         Sets the current record's "campo5" value
 * @method Listvend setClaverest()      Sets the current record's "claverest" value
 * @method Listvend setEsServidor()     Sets the current record's "es_servidor" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseListvend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('listvend');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('codigo', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('nombre', 'string', 54, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '54',
             ));
        $this->hasColumn('direccion', 'string', 74, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '74',
             ));
        $this->hasColumn('comision', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('sector', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('cedula', 'string', 21, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             ));
        $this->hasColumn('telefonos', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '100',
             ));
        $this->hasColumn('telefono_movil', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '100',
             ));
        $this->hasColumn('cobranza', 'float', 9, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '9',
             ));
        $this->hasColumn('expediente', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('codigocont', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('activcomi', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('desde1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('desde2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('desde3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('desde4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('desde5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('desde6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('hasta1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('hasta2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('hasta3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('hasta4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('hasta5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('hasta6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('prccomi1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('prccomi2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('prccomi3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('prccomi4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('prccomi5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('prccomi6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('bono1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('bono2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('bono3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('bono4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('bono5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('bono6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('utilvent', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('aplicaramendoc', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('cobdesde1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobdesde2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobdesde3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobdesde4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobdesde5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobdesde6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobhasta1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobhasta2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobhasta3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobhasta4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobhasta5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobhasta6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobprccomi1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobprccomi2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobprccomi3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobprccomi4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobprccomi5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobprccomi6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobbono1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobbono2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobbono3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobbono4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobbono5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cobbono6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('valoraporcent', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('no_comi_art', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('art_prc_1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('art_prc_2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('art_prc_3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('art_prc_4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('art_prc_5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('art_prc_6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('art_prc_7', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('email', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '60',
             ));
        $this->hasColumn('campo1', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('campo2', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('campo3', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('campo4', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('campo5', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('claverest', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('es_servidor', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}