<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Optsubmenu', 'premium');

/**
 * BaseOptsubmenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $id_empresa
 * @property string $agencia
 * @property string $codigo
 * @property string $idcodigo
 * @property string $orden
 * @property string $nombre
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method string     getIdEmpresa()  Returns the current record's "id_empresa" value
 * @method string     getAgencia()    Returns the current record's "agencia" value
 * @method string     getCodigo()     Returns the current record's "codigo" value
 * @method string     getIdcodigo()   Returns the current record's "idcodigo" value
 * @method string     getOrden()      Returns the current record's "orden" value
 * @method string     getNombre()     Returns the current record's "nombre" value
 * @method Optsubmenu setId()         Sets the current record's "id" value
 * @method Optsubmenu setIdEmpresa()  Sets the current record's "id_empresa" value
 * @method Optsubmenu setAgencia()    Sets the current record's "agencia" value
 * @method Optsubmenu setCodigo()     Sets the current record's "codigo" value
 * @method Optsubmenu setIdcodigo()   Sets the current record's "idcodigo" value
 * @method Optsubmenu setOrden()      Sets the current record's "orden" value
 * @method Optsubmenu setNombre()     Sets the current record's "nombre" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOptsubmenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('optsubmenu');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('codigo', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('idcodigo', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('orden', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}