<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Operti', 'premium');

/**
 * BaseOperti
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $tipodoc
 * @property string $moneda
 * @property string $documento
 * @property string $codcliente
 * @property string $nombrecli
 * @property string $contacto
 * @property string $comprador
 * @property string $rif
 * @property string $nit
 * @property string $direccion
 * @property string $telefonos
 * @property float $tipoprecio
 * @property string $orden
 * @property date $emision
 * @property date $recepcion
 * @property date $vence
 * @property date $ult_interes
 * @property date $fechacrea
 * @property float $totcosto
 * @property float $totcomi
 * @property float $totbruto
 * @property float $totneto
 * @property float $totpagos
 * @property float $totalfinal
 * @property float $totimpuest
 * @property float $totdescuen
 * @property float $impuesto1
 * @property float $impuesto2
 * @property float $impuesto3
 * @property float $impuesto4
 * @property float $impuesto5
 * @property float $impuesto6
 * @property float $recargos
 * @property float $dsctoend1
 * @property float $dsctoend2
 * @property float $dsctolinea
 * @property string $notas
 * @property string $estatusdoc
 * @property date $ultimopag
 * @property float $diascred
 * @property string $vendedor
 * @property float $factorcamb
 * @property float $multi_div
 * @property float $factorreferencial
 * @property date $fechanul
 * @property string $uanulador
 * @property string $uemisor
 * @property string $estacion
 * @property float $sinimpuest
 * @property string $almacen
 * @property string $sector
 * @property float $formafis
 * @property float $al_libro
 * @property string $codigoret
 * @property float $retencion
 * @property float $aux1
 * @property float $aux2
 * @property string $aplicadoa
 * @property string $referencia
 * @property string $operac
 * @property string $motanul
 * @property float $seimporto
 * @property float $dbcr
 * @property string $horadocum
 * @property float $ampm
 * @property float $tranferido
 * @property float $procedecre
 * @property float $entregado
 * @property float $vuelto
 * @property float $integrado
 * @property float $escredito
 * @property string $seq_nodo
 * @property string $tipo_nc
 * @property float $porbackord
 * @property float $chequedev
 * @property string $ordentrab
 * @property string $compcont
 * @property string $planillacob
 * @property string $nodoremoto
 * @property string $turno
 * @property string $codvend_a
 * @property string $codvend_b
 * @property string $codvend_c
 * @property string $codvend_d
 * @property float $baseimpo1
 * @property float $baseimpo2
 * @property float $baseimpo3
 * @property string $iddocumento
 * @property float $imp_nacional
 * @property float $imp_producc
 * @property float $retencioniva
 * @property timestamp $fechayhora
 * @property float $tipopersona
 * @property string $idvalidacion
 * @property float $nosujeto
 * @property string $serialprintf
 * @property string $documentofiscal
 * @property string $ubica
 * @property float $usa_despacho
 * @property string $despachador
 * @property string $despacho_nro
 * 
 * @method string    getIdEmpresa()         Returns the current record's "id_empresa" value
 * @method string    getAgencia()           Returns the current record's "agencia" value
 * @method string    getTipodoc()           Returns the current record's "tipodoc" value
 * @method string    getMoneda()            Returns the current record's "moneda" value
 * @method string    getDocumento()         Returns the current record's "documento" value
 * @method string    getCodcliente()        Returns the current record's "codcliente" value
 * @method string    getNombrecli()         Returns the current record's "nombrecli" value
 * @method string    getContacto()          Returns the current record's "contacto" value
 * @method string    getComprador()         Returns the current record's "comprador" value
 * @method string    getRif()               Returns the current record's "rif" value
 * @method string    getNit()               Returns the current record's "nit" value
 * @method string    getDireccion()         Returns the current record's "direccion" value
 * @method string    getTelefonos()         Returns the current record's "telefonos" value
 * @method float     getTipoprecio()        Returns the current record's "tipoprecio" value
 * @method string    getOrden()             Returns the current record's "orden" value
 * @method date      getEmision()           Returns the current record's "emision" value
 * @method date      getRecepcion()         Returns the current record's "recepcion" value
 * @method date      getVence()             Returns the current record's "vence" value
 * @method date      getUltInteres()        Returns the current record's "ult_interes" value
 * @method date      getFechacrea()         Returns the current record's "fechacrea" value
 * @method float     getTotcosto()          Returns the current record's "totcosto" value
 * @method float     getTotcomi()           Returns the current record's "totcomi" value
 * @method float     getTotbruto()          Returns the current record's "totbruto" value
 * @method float     getTotneto()           Returns the current record's "totneto" value
 * @method float     getTotpagos()          Returns the current record's "totpagos" value
 * @method float     getTotalfinal()        Returns the current record's "totalfinal" value
 * @method float     getTotimpuest()        Returns the current record's "totimpuest" value
 * @method float     getTotdescuen()        Returns the current record's "totdescuen" value
 * @method float     getImpuesto1()         Returns the current record's "impuesto1" value
 * @method float     getImpuesto2()         Returns the current record's "impuesto2" value
 * @method float     getImpuesto3()         Returns the current record's "impuesto3" value
 * @method float     getImpuesto4()         Returns the current record's "impuesto4" value
 * @method float     getImpuesto5()         Returns the current record's "impuesto5" value
 * @method float     getImpuesto6()         Returns the current record's "impuesto6" value
 * @method float     getRecargos()          Returns the current record's "recargos" value
 * @method float     getDsctoend1()         Returns the current record's "dsctoend1" value
 * @method float     getDsctoend2()         Returns the current record's "dsctoend2" value
 * @method float     getDsctolinea()        Returns the current record's "dsctolinea" value
 * @method string    getNotas()             Returns the current record's "notas" value
 * @method string    getEstatusdoc()        Returns the current record's "estatusdoc" value
 * @method date      getUltimopag()         Returns the current record's "ultimopag" value
 * @method float     getDiascred()          Returns the current record's "diascred" value
 * @method string    getVendedor()          Returns the current record's "vendedor" value
 * @method float     getFactorcamb()        Returns the current record's "factorcamb" value
 * @method float     getMultiDiv()          Returns the current record's "multi_div" value
 * @method float     getFactorreferencial() Returns the current record's "factorreferencial" value
 * @method date      getFechanul()          Returns the current record's "fechanul" value
 * @method string    getUanulador()         Returns the current record's "uanulador" value
 * @method string    getUemisor()           Returns the current record's "uemisor" value
 * @method string    getEstacion()          Returns the current record's "estacion" value
 * @method float     getSinimpuest()        Returns the current record's "sinimpuest" value
 * @method string    getAlmacen()           Returns the current record's "almacen" value
 * @method string    getSector()            Returns the current record's "sector" value
 * @method float     getFormafis()          Returns the current record's "formafis" value
 * @method float     getAlLibro()           Returns the current record's "al_libro" value
 * @method string    getCodigoret()         Returns the current record's "codigoret" value
 * @method float     getRetencion()         Returns the current record's "retencion" value
 * @method float     getAux1()              Returns the current record's "aux1" value
 * @method float     getAux2()              Returns the current record's "aux2" value
 * @method string    getAplicadoa()         Returns the current record's "aplicadoa" value
 * @method string    getReferencia()        Returns the current record's "referencia" value
 * @method string    getOperac()            Returns the current record's "operac" value
 * @method string    getMotanul()           Returns the current record's "motanul" value
 * @method float     getSeimporto()         Returns the current record's "seimporto" value
 * @method float     getDbcr()              Returns the current record's "dbcr" value
 * @method string    getHoradocum()         Returns the current record's "horadocum" value
 * @method float     getAmpm()              Returns the current record's "ampm" value
 * @method float     getTranferido()        Returns the current record's "tranferido" value
 * @method float     getProcedecre()        Returns the current record's "procedecre" value
 * @method float     getEntregado()         Returns the current record's "entregado" value
 * @method float     getVuelto()            Returns the current record's "vuelto" value
 * @method float     getIntegrado()         Returns the current record's "integrado" value
 * @method float     getEscredito()         Returns the current record's "escredito" value
 * @method string    getSeqNodo()           Returns the current record's "seq_nodo" value
 * @method string    getTipoNc()            Returns the current record's "tipo_nc" value
 * @method float     getPorbackord()        Returns the current record's "porbackord" value
 * @method float     getChequedev()         Returns the current record's "chequedev" value
 * @method string    getOrdentrab()         Returns the current record's "ordentrab" value
 * @method string    getCompcont()          Returns the current record's "compcont" value
 * @method string    getPlanillacob()       Returns the current record's "planillacob" value
 * @method string    getNodoremoto()        Returns the current record's "nodoremoto" value
 * @method string    getTurno()             Returns the current record's "turno" value
 * @method string    getCodvendA()          Returns the current record's "codvend_a" value
 * @method string    getCodvendB()          Returns the current record's "codvend_b" value
 * @method string    getCodvendC()          Returns the current record's "codvend_c" value
 * @method string    getCodvendD()          Returns the current record's "codvend_d" value
 * @method float     getBaseimpo1()         Returns the current record's "baseimpo1" value
 * @method float     getBaseimpo2()         Returns the current record's "baseimpo2" value
 * @method float     getBaseimpo3()         Returns the current record's "baseimpo3" value
 * @method string    getIddocumento()       Returns the current record's "iddocumento" value
 * @method float     getImpNacional()       Returns the current record's "imp_nacional" value
 * @method float     getImpProducc()        Returns the current record's "imp_producc" value
 * @method float     getRetencioniva()      Returns the current record's "retencioniva" value
 * @method timestamp getFechayhora()        Returns the current record's "fechayhora" value
 * @method float     getTipopersona()       Returns the current record's "tipopersona" value
 * @method string    getIdvalidacion()      Returns the current record's "idvalidacion" value
 * @method float     getNosujeto()          Returns the current record's "nosujeto" value
 * @method string    getSerialprintf()      Returns the current record's "serialprintf" value
 * @method string    getDocumentofiscal()   Returns the current record's "documentofiscal" value
 * @method string    getUbica()             Returns the current record's "ubica" value
 * @method float     getUsaDespacho()       Returns the current record's "usa_despacho" value
 * @method string    getDespachador()       Returns the current record's "despachador" value
 * @method string    getDespachoNro()       Returns the current record's "despacho_nro" value
 * @method Operti    setIdEmpresa()         Sets the current record's "id_empresa" value
 * @method Operti    setAgencia()           Sets the current record's "agencia" value
 * @method Operti    setTipodoc()           Sets the current record's "tipodoc" value
 * @method Operti    setMoneda()            Sets the current record's "moneda" value
 * @method Operti    setDocumento()         Sets the current record's "documento" value
 * @method Operti    setCodcliente()        Sets the current record's "codcliente" value
 * @method Operti    setNombrecli()         Sets the current record's "nombrecli" value
 * @method Operti    setContacto()          Sets the current record's "contacto" value
 * @method Operti    setComprador()         Sets the current record's "comprador" value
 * @method Operti    setRif()               Sets the current record's "rif" value
 * @method Operti    setNit()               Sets the current record's "nit" value
 * @method Operti    setDireccion()         Sets the current record's "direccion" value
 * @method Operti    setTelefonos()         Sets the current record's "telefonos" value
 * @method Operti    setTipoprecio()        Sets the current record's "tipoprecio" value
 * @method Operti    setOrden()             Sets the current record's "orden" value
 * @method Operti    setEmision()           Sets the current record's "emision" value
 * @method Operti    setRecepcion()         Sets the current record's "recepcion" value
 * @method Operti    setVence()             Sets the current record's "vence" value
 * @method Operti    setUltInteres()        Sets the current record's "ult_interes" value
 * @method Operti    setFechacrea()         Sets the current record's "fechacrea" value
 * @method Operti    setTotcosto()          Sets the current record's "totcosto" value
 * @method Operti    setTotcomi()           Sets the current record's "totcomi" value
 * @method Operti    setTotbruto()          Sets the current record's "totbruto" value
 * @method Operti    setTotneto()           Sets the current record's "totneto" value
 * @method Operti    setTotpagos()          Sets the current record's "totpagos" value
 * @method Operti    setTotalfinal()        Sets the current record's "totalfinal" value
 * @method Operti    setTotimpuest()        Sets the current record's "totimpuest" value
 * @method Operti    setTotdescuen()        Sets the current record's "totdescuen" value
 * @method Operti    setImpuesto1()         Sets the current record's "impuesto1" value
 * @method Operti    setImpuesto2()         Sets the current record's "impuesto2" value
 * @method Operti    setImpuesto3()         Sets the current record's "impuesto3" value
 * @method Operti    setImpuesto4()         Sets the current record's "impuesto4" value
 * @method Operti    setImpuesto5()         Sets the current record's "impuesto5" value
 * @method Operti    setImpuesto6()         Sets the current record's "impuesto6" value
 * @method Operti    setRecargos()          Sets the current record's "recargos" value
 * @method Operti    setDsctoend1()         Sets the current record's "dsctoend1" value
 * @method Operti    setDsctoend2()         Sets the current record's "dsctoend2" value
 * @method Operti    setDsctolinea()        Sets the current record's "dsctolinea" value
 * @method Operti    setNotas()             Sets the current record's "notas" value
 * @method Operti    setEstatusdoc()        Sets the current record's "estatusdoc" value
 * @method Operti    setUltimopag()         Sets the current record's "ultimopag" value
 * @method Operti    setDiascred()          Sets the current record's "diascred" value
 * @method Operti    setVendedor()          Sets the current record's "vendedor" value
 * @method Operti    setFactorcamb()        Sets the current record's "factorcamb" value
 * @method Operti    setMultiDiv()          Sets the current record's "multi_div" value
 * @method Operti    setFactorreferencial() Sets the current record's "factorreferencial" value
 * @method Operti    setFechanul()          Sets the current record's "fechanul" value
 * @method Operti    setUanulador()         Sets the current record's "uanulador" value
 * @method Operti    setUemisor()           Sets the current record's "uemisor" value
 * @method Operti    setEstacion()          Sets the current record's "estacion" value
 * @method Operti    setSinimpuest()        Sets the current record's "sinimpuest" value
 * @method Operti    setAlmacen()           Sets the current record's "almacen" value
 * @method Operti    setSector()            Sets the current record's "sector" value
 * @method Operti    setFormafis()          Sets the current record's "formafis" value
 * @method Operti    setAlLibro()           Sets the current record's "al_libro" value
 * @method Operti    setCodigoret()         Sets the current record's "codigoret" value
 * @method Operti    setRetencion()         Sets the current record's "retencion" value
 * @method Operti    setAux1()              Sets the current record's "aux1" value
 * @method Operti    setAux2()              Sets the current record's "aux2" value
 * @method Operti    setAplicadoa()         Sets the current record's "aplicadoa" value
 * @method Operti    setReferencia()        Sets the current record's "referencia" value
 * @method Operti    setOperac()            Sets the current record's "operac" value
 * @method Operti    setMotanul()           Sets the current record's "motanul" value
 * @method Operti    setSeimporto()         Sets the current record's "seimporto" value
 * @method Operti    setDbcr()              Sets the current record's "dbcr" value
 * @method Operti    setHoradocum()         Sets the current record's "horadocum" value
 * @method Operti    setAmpm()              Sets the current record's "ampm" value
 * @method Operti    setTranferido()        Sets the current record's "tranferido" value
 * @method Operti    setProcedecre()        Sets the current record's "procedecre" value
 * @method Operti    setEntregado()         Sets the current record's "entregado" value
 * @method Operti    setVuelto()            Sets the current record's "vuelto" value
 * @method Operti    setIntegrado()         Sets the current record's "integrado" value
 * @method Operti    setEscredito()         Sets the current record's "escredito" value
 * @method Operti    setSeqNodo()           Sets the current record's "seq_nodo" value
 * @method Operti    setTipoNc()            Sets the current record's "tipo_nc" value
 * @method Operti    setPorbackord()        Sets the current record's "porbackord" value
 * @method Operti    setChequedev()         Sets the current record's "chequedev" value
 * @method Operti    setOrdentrab()         Sets the current record's "ordentrab" value
 * @method Operti    setCompcont()          Sets the current record's "compcont" value
 * @method Operti    setPlanillacob()       Sets the current record's "planillacob" value
 * @method Operti    setNodoremoto()        Sets the current record's "nodoremoto" value
 * @method Operti    setTurno()             Sets the current record's "turno" value
 * @method Operti    setCodvendA()          Sets the current record's "codvend_a" value
 * @method Operti    setCodvendB()          Sets the current record's "codvend_b" value
 * @method Operti    setCodvendC()          Sets the current record's "codvend_c" value
 * @method Operti    setCodvendD()          Sets the current record's "codvend_d" value
 * @method Operti    setBaseimpo1()         Sets the current record's "baseimpo1" value
 * @method Operti    setBaseimpo2()         Sets the current record's "baseimpo2" value
 * @method Operti    setBaseimpo3()         Sets the current record's "baseimpo3" value
 * @method Operti    setIddocumento()       Sets the current record's "iddocumento" value
 * @method Operti    setImpNacional()       Sets the current record's "imp_nacional" value
 * @method Operti    setImpProducc()        Sets the current record's "imp_producc" value
 * @method Operti    setRetencioniva()      Sets the current record's "retencioniva" value
 * @method Operti    setFechayhora()        Sets the current record's "fechayhora" value
 * @method Operti    setTipopersona()       Sets the current record's "tipopersona" value
 * @method Operti    setIdvalidacion()      Sets the current record's "idvalidacion" value
 * @method Operti    setNosujeto()          Sets the current record's "nosujeto" value
 * @method Operti    setSerialprintf()      Sets the current record's "serialprintf" value
 * @method Operti    setDocumentofiscal()   Sets the current record's "documentofiscal" value
 * @method Operti    setUbica()             Sets the current record's "ubica" value
 * @method Operti    setUsaDespacho()       Sets the current record's "usa_despacho" value
 * @method Operti    setDespachador()       Sets the current record's "despachador" value
 * @method Operti    setDespachoNro()       Sets the current record's "despacho_nro" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOperti extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('operti');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('tipodoc', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('moneda', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('documento', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('codcliente', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('nombrecli', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '100',
             ));
        $this->hasColumn('contacto', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '30',
             ));
        $this->hasColumn('comprador', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('rif', 'string', 14, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '14',
             ));
        $this->hasColumn('nit', 'string', 14, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '14',
             ));
        $this->hasColumn('direccion', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '200',
             ));
        $this->hasColumn('telefonos', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('tipoprecio', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('orden', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('emision', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('recepcion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('vence', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('ult_interes', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('fechacrea', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('totcosto', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totcomi', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totbruto', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totneto', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totpagos', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totalfinal', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totimpuest', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totdescuen', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('recargos', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('dsctoend1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('dsctoend2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('dsctolinea', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('notas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('estatusdoc', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('ultimopag', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('diascred', 'float', 5, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '5',
             ));
        $this->hasColumn('vendedor', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('factorcamb', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('multi_div', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('factorreferencial', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('fechanul', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('uanulador', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('uemisor', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('estacion', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('sinimpuest', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('almacen', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('sector', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('formafis', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('al_libro', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('codigoret', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('retencion', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('aux1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('aux2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('aplicadoa', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '11',
             ));
        $this->hasColumn('referencia', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('operac', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('motanul', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('seimporto', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('dbcr', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('horadocum', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '5',
             ));
        $this->hasColumn('ampm', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('tranferido', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('procedecre', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('entregado', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('vuelto', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('integrado', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('escredito', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('seq_nodo', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('tipo_nc', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('porbackord', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('chequedev', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('ordentrab', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('compcont', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('planillacob', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('nodoremoto', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('turno', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('codvend_a', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('codvend_b', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('codvend_c', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('codvend_d', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('baseimpo1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('baseimpo2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('baseimpo3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('iddocumento', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('imp_nacional', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('imp_producc', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('retencioniva', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('fechayhora', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('tipopersona', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('idvalidacion', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '12',
             ));
        $this->hasColumn('nosujeto', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('serialprintf', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('documentofiscal', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '12',
             ));
        $this->hasColumn('ubica', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '30',
             ));
        $this->hasColumn('usa_despacho', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('despachador', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('despacho_nro', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}