<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ctascon', 'premium');

/**
 * BaseCtascon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $codigo
 * @property string $descrip
 * @property float $tipo
 * @property string $cuentacont
 * 
 * @method string  getIdEmpresa()  Returns the current record's "id_empresa" value
 * @method string  getAgencia()    Returns the current record's "agencia" value
 * @method string  getCodigo()     Returns the current record's "codigo" value
 * @method string  getDescrip()    Returns the current record's "descrip" value
 * @method float   getTipo()       Returns the current record's "tipo" value
 * @method string  getCuentacont() Returns the current record's "cuentacont" value
 * @method Ctascon setIdEmpresa()  Sets the current record's "id_empresa" value
 * @method Ctascon setAgencia()    Sets the current record's "agencia" value
 * @method Ctascon setCodigo()     Sets the current record's "codigo" value
 * @method Ctascon setDescrip()    Sets the current record's "descrip" value
 * @method Ctascon setTipo()       Sets the current record's "tipo" value
 * @method Ctascon setCuentacont() Sets the current record's "cuentacont" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCtascon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ctascon');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('codigo', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('descrip', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('tipo', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('cuentacont', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '40',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}