<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Retenc', 'premium');

/**
 * BaseRetenc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $codigo
 * @property string $descrip
 * @property float $beneficiar
 * @property float $base
 * @property float $ret
 * @property float $sustraend
 * @property float $pago
 * @property float $tabla
 * @property string $cuentacon
 * 
 * @method string getIdEmpresa()  Returns the current record's "id_empresa" value
 * @method string getAgencia()    Returns the current record's "agencia" value
 * @method string getCodigo()     Returns the current record's "codigo" value
 * @method string getDescrip()    Returns the current record's "descrip" value
 * @method float  getBeneficiar() Returns the current record's "beneficiar" value
 * @method float  getBase()       Returns the current record's "base" value
 * @method float  getRet()        Returns the current record's "ret" value
 * @method float  getSustraend()  Returns the current record's "sustraend" value
 * @method float  getPago()       Returns the current record's "pago" value
 * @method float  getTabla()      Returns the current record's "tabla" value
 * @method string getCuentacon()  Returns the current record's "cuentacon" value
 * @method Retenc setIdEmpresa()  Sets the current record's "id_empresa" value
 * @method Retenc setAgencia()    Sets the current record's "agencia" value
 * @method Retenc setCodigo()     Sets the current record's "codigo" value
 * @method Retenc setDescrip()    Sets the current record's "descrip" value
 * @method Retenc setBeneficiar() Sets the current record's "beneficiar" value
 * @method Retenc setBase()       Sets the current record's "base" value
 * @method Retenc setRet()        Sets the current record's "ret" value
 * @method Retenc setSustraend()  Sets the current record's "sustraend" value
 * @method Retenc setPago()       Sets the current record's "pago" value
 * @method Retenc setTabla()      Sets the current record's "tabla" value
 * @method Retenc setCuentacon()  Sets the current record's "cuentacon" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRetenc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('retenc');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('codigo', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('descrip', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '80',
             ));
        $this->hasColumn('beneficiar', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('base', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('ret', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('sustraend', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('pago', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('tabla', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('cuentacon', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}