<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Reportes', 'premium');

/**
 * BaseReportes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $id_empresa
 * @property string $agencia
 * @property string $tipo
 * @property string $namereport
 * @property string $titulo
 * @property string $descrip
 * @property string $condicion
 * @property float $tipocond
 * 
 * @method integer  getId()         Returns the current record's "id" value
 * @method string   getIdEmpresa()  Returns the current record's "id_empresa" value
 * @method string   getAgencia()    Returns the current record's "agencia" value
 * @method string   getTipo()       Returns the current record's "tipo" value
 * @method string   getNamereport() Returns the current record's "namereport" value
 * @method string   getTitulo()     Returns the current record's "titulo" value
 * @method string   getDescrip()    Returns the current record's "descrip" value
 * @method string   getCondicion()  Returns the current record's "condicion" value
 * @method float    getTipocond()   Returns the current record's "tipocond" value
 * @method Reportes setId()         Sets the current record's "id" value
 * @method Reportes setIdEmpresa()  Sets the current record's "id_empresa" value
 * @method Reportes setAgencia()    Sets the current record's "agencia" value
 * @method Reportes setTipo()       Sets the current record's "tipo" value
 * @method Reportes setNamereport() Sets the current record's "namereport" value
 * @method Reportes setTitulo()     Sets the current record's "titulo" value
 * @method Reportes setDescrip()    Sets the current record's "descrip" value
 * @method Reportes setCondicion()  Sets the current record's "condicion" value
 * @method Reportes setTipocond()   Sets the current record's "tipocond" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseReportes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reportes');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('tipo', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('namereport', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('titulo', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '80',
             ));
        $this->hasColumn('descrip', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('condicion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tipocond', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}