<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NotascreAplic', 'premium');

/**
 * BaseNotascreAplic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $id_empresa
 * @property string $agencia
 * @property string $tipodoc
 * @property string $documento
 * @property timestamp $fecha_aplic
 * @property float $monto_aplic
 * @property string $id_empresa_h
 * @property string $agencia_h
 * @property string $tipodoc_h
 * @property string $documento_h
 * @property string $recibo
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method string        getIdEmpresa()    Returns the current record's "id_empresa" value
 * @method string        getAgencia()      Returns the current record's "agencia" value
 * @method string        getTipodoc()      Returns the current record's "tipodoc" value
 * @method string        getDocumento()    Returns the current record's "documento" value
 * @method timestamp     getFechaAplic()   Returns the current record's "fecha_aplic" value
 * @method float         getMontoAplic()   Returns the current record's "monto_aplic" value
 * @method string        getIdEmpresaH()   Returns the current record's "id_empresa_h" value
 * @method string        getAgenciaH()     Returns the current record's "agencia_h" value
 * @method string        getTipodocH()     Returns the current record's "tipodoc_h" value
 * @method string        getDocumentoH()   Returns the current record's "documento_h" value
 * @method string        getRecibo()       Returns the current record's "recibo" value
 * @method NotascreAplic setId()           Sets the current record's "id" value
 * @method NotascreAplic setIdEmpresa()    Sets the current record's "id_empresa" value
 * @method NotascreAplic setAgencia()      Sets the current record's "agencia" value
 * @method NotascreAplic setTipodoc()      Sets the current record's "tipodoc" value
 * @method NotascreAplic setDocumento()    Sets the current record's "documento" value
 * @method NotascreAplic setFechaAplic()   Sets the current record's "fecha_aplic" value
 * @method NotascreAplic setMontoAplic()   Sets the current record's "monto_aplic" value
 * @method NotascreAplic setIdEmpresaH()   Sets the current record's "id_empresa_h" value
 * @method NotascreAplic setAgenciaH()     Sets the current record's "agencia_h" value
 * @method NotascreAplic setTipodocH()     Sets the current record's "tipodoc_h" value
 * @method NotascreAplic setDocumentoH()   Sets the current record's "documento_h" value
 * @method NotascreAplic setRecibo()       Sets the current record's "recibo" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseNotascreAplic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notascre_aplic');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('tipodoc', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('documento', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('fecha_aplic', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('monto_aplic', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('id_empresa_h', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia_h', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('tipodoc_h', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('documento_h', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('recibo', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}