<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Config2', 'premium');

/**
 * BaseConfig2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $id_empresa
 * @property string $msg_login_sms
 * @property string $msg_password_sms
 * @property string $id_despachadors
 * @property string $id_despachadorp
 * @property integer $decimales_impuesto
 * @property integer $redondear_impuesto
 * @property integer $actcecom
 * 
 * @method integer getId()                 Returns the current record's "id" value
 * @method string  getIdEmpresa()          Returns the current record's "id_empresa" value
 * @method string  getMsgLoginSms()        Returns the current record's "msg_login_sms" value
 * @method string  getMsgPasswordSms()     Returns the current record's "msg_password_sms" value
 * @method string  getIdDespachadors()     Returns the current record's "id_despachadors" value
 * @method string  getIdDespachadorp()     Returns the current record's "id_despachadorp" value
 * @method integer getDecimalesImpuesto()  Returns the current record's "decimales_impuesto" value
 * @method integer getRedondearImpuesto()  Returns the current record's "redondear_impuesto" value
 * @method integer getActcecom()           Returns the current record's "actcecom" value
 * @method Config2 setId()                 Sets the current record's "id" value
 * @method Config2 setIdEmpresa()          Sets the current record's "id_empresa" value
 * @method Config2 setMsgLoginSms()        Sets the current record's "msg_login_sms" value
 * @method Config2 setMsgPasswordSms()     Sets the current record's "msg_password_sms" value
 * @method Config2 setIdDespachadors()     Sets the current record's "id_despachadors" value
 * @method Config2 setIdDespachadorp()     Sets the current record's "id_despachadorp" value
 * @method Config2 setDecimalesImpuesto()  Sets the current record's "decimales_impuesto" value
 * @method Config2 setRedondearImpuesto()  Sets the current record's "redondear_impuesto" value
 * @method Config2 setActcecom()           Sets the current record's "actcecom" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseConfig2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('config2');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('msg_login_sms', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '60',
             ));
        $this->hasColumn('msg_password_sms', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '60',
             ));
        $this->hasColumn('id_despachadors', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('id_despachadorp', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('decimales_impuesto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '4',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('redondear_impuesto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('actcecom', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}