connection: premium

AlmConf:
  tableName: almconf
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    almmatpri:
      type: string(2)
      notnull: true
    almpropro:
      type: string(2)
      notnull: true
    almproter:
      type: string(2)
      notnull: true
    usuario:
      type: string(20)
      notnull: true
    condoc:
      type: integer(4)
      primary: false
    tipent:
      type: string(6)
      notnull: true
    tipsal:
      type: string(6)
      notnull: true
  relations:
    MatPri:
      class: Almacene
      local: almmatpri
      foreign: codigo
    ProPro:
      class: Almacene
      local: almpropro
      foreign: codigo
    ProTer:
      class: Almacene
      local: almproter
      foreign: codigo
    Usuarios:
      class: Usuarios
      local: usuario
      foreign: username
    TipoEntrada:
      class: Tipoentradasalida
      local: tipent
      foreign: codigo
    TipoSalida:
      class: Tipoentradasalida
      local: tipsal
      foreign: codigo

OrdPro:
  tableName: ordpro
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    numord:
      type: integer(4)
      notnull: true
      unique: true
    desord:
      type: string(100)
      notnull: true
    fecord:
      type: timestamp
      notnull: true
    anulada:
      type: boolean
      default: 0
    fecanu:
      type: timestamp
      notnull: false
    reportada:
      type: boolean
      default: 0
    fecrep:
      type: timestamp
      notnull: false
    documento:
      type: string(10)
      notnull: false
    documentopro:
      type: string(10)
      notnull: false
  indexes:
    numord_idx:
      fields: [numord]
    anulada_idx:
      fields: [anulada]
  relations:
    productos:
      class: OrdProPro
      local: id
      foreign: ordpro_id
      type: many
      onDelete: CASCADE
    materia_prima:
      class: OrdProMatPri
      local: id
      foreign: ordpro_id
      type: many
      onDelete: CASCADE
    docmatpri:
      class: Cargoenc
      local: documento
      foreign: documento
      type: one
    docpro:
      class: Cargoenc
      local: documentopro
      foreign: documento
      type: one

OrdProPro:
  tableName: ordpropro
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    ordpro_id:
      type: integer(4)
      notnull: true
    artcomp:
      type: string(25)
      notnull: true
    cantidad:
      type: integer(4)
      notnull: true
    resultado:
      type: integer(4)
      notnull: true
  relations:
    ArticuloCompuesto:
      class: Articulo
      local: artcomp
      foreign: codigo
      type: one

OrdProMatPri:
  tableName: ordpromatpri
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    ordpro_id:
      type: integer(4)
      notnull: true
    artcomp:
      type: string(25)
      notnull: true
    cantidad:
      type: float
      notnull: true
    resultado:
      type: float
      notnull: true
  relations:
    MateriaPrima:
      class: Articulo
      local: artcomp
      foreign: codigo
      type: one
