generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrdPro
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ord_pro_informenes
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        numord:  { label: "Nro. Orden" }
        desord:  { label: "Descripción" }
        fecord:  { label: "Fecha Creación" }
        fecanu:  { label: "Fecha" }
        created_at:  { label: "Creación" }
        anulada: { attributes: { disabled: true } }
        documento: { label: "Sal. Materia Prima", attributes: { disabled: true } }
        documentopro: { label: "Ent. Producto Terminado", attributes: { disabled: true } }
        esta_anulado: { label: "¿Anulada?" }
        new_materia_prima: { label: "Materia Prima" }
        new_productos: { label: "Productos" }
        list_materia_prima: { label: "Detalle Materia Prima" }
        list_productos: { label: "Detalle Productos" }
      list:
        title: Informenes de Producción
        display: [numord, desord, fecord, esta_anulado, a_producir]
        batch_actions: { }
        object_actions:
          _informe:
            action: informe
            label: Informe
      filter:
        fields:
          anulada: { attributes: { disabled: false } }
        display: [numord, desord, fecord, anulada]
      form:    ~
      edit:    ~
      new:     ~