<?php

/**
 * OrdPro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class OrdPro extends BaseOrdPro
{
  public function getaProducir()
  {
    $aproducir = '';

    foreach($this->getProductos() as $index => $prod) $aproducir .= $prod->getNombre(). (($index+1)<(count($this->getProductos())) ? ' y ' : '');
    return $aproducir;
  }

  public function getEstaAnulado()
  {
    if($this->anulada==1) return 'Sí';
    else return 'No';
  }
}
