<?php

/**
 * AlmConf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class AlmConf extends BaseAlmConf
{
  public static function getConfig()
  {
    return Doctrine_Query::create()->from('AlmConf')->fetchOne(array());
  }
}
