<?php

/**
 * Usuarios form base class.
 *
 * @method Usuarios getObject() Returns the current form's model object
 *
 * @package    exproaqua
 * @subpackage form
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 24171 2009-11-19 16:37:50Z Kris.Wallsmith $
 */
abstract class BaseUsuariosForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id_empresa'              => new sfWidgetFormInputText(),
      'nombre'                  => new sfWidgetFormInputText(),
      'cedula'                  => new sfWidgetFormInputText(),
      'direccion'               => new sfWidgetFormInputText(),
      'telefono'                => new sfWidgetFormInputText(),
      'email'                   => new sfWidgetFormInputText(),
      'website'                 => new sfWidgetFormInputText(),
      'username'                => new sfWidgetFormInputHidden(),
      'nickname'                => new sfWidgetFormInputText(),
      'userid'                  => new sfWidgetFormInputText(),
      'fechanac'                => new sfWidgetFormDate(),
      'uaddinfo'                => new sfWidgetFormInputText(),
      'umodinfo'                => new sfWidgetFormInputText(),
      'ukillinfo'               => new sfWidgetFormInputText(),
      'uversalban'              => new sfWidgetFormInputText(),
      'uaccecosto'              => new sfWidgetFormInputText(),
      'uaccdepina'              => new sfWidgetFormInputText(),
      'ualterprec'              => new sfWidgetFormInputText(),
      'ualtnomart'              => new sfWidgetFormInputText(),
      'uimpordocv'              => new sfWidgetFormInputText(),
      'uimpordocc'              => new sfWidgetFormInputText(),
      'ucreclient'              => new sfWidgetFormInputText(),
      'ucambvend'               => new sfWidgetFormInputText(),
      'umodipre'                => new sfWidgetFormInputText(),
      'useltippre'              => new sfWidgetFormInputText(),
      'uconsimpu'               => new sfWidgetFormInputText(),
      'uperfsuper'              => new sfWidgetFormInputText(),
      'uacceconf'               => new sfWidgetFormInputText(),
      'ucreauser'               => new sfWidgetFormInputText(),
      'umodiform'               => new sfWidgetFormInputText(),
      'useldeposi'              => new sfWidgetFormInputText(),
      'uprecio1'                => new sfWidgetFormInputText(),
      'uprecio2'                => new sfWidgetFormInputText(),
      'uprecio3'                => new sfWidgetFormInputText(),
      'uprecio4'                => new sfWidgetFormInputText(),
      'uprecio5'                => new sfWidgetFormInputText(),
      'uprecio6'                => new sfWidgetFormInputText(),
      'uprecio7'                => new sfWidgetFormInputText(),
      'uprecio8'                => new sfWidgetFormInputText(),
      'udesl1'                  => new sfWidgetFormInputText(),
      'udesl2'                  => new sfWidgetFormInputText(),
      'udesl3'                  => new sfWidgetFormInputText(),
      'udesl4'                  => new sfWidgetFormInputText(),
      'udesl5'                  => new sfWidgetFormInputText(),
      'udesl6'                  => new sfWidgetFormInputText(),
      'udesl7'                  => new sfWidgetFormInputText(),
      'udesl8'                  => new sfWidgetFormInputText(),
      'novaldscto'              => new sfWidgetFormInputText(),
      'udesfin1'                => new sfWidgetFormInputText(),
      'udesfin2'                => new sfWidgetFormInputText(),
      'uautoriza'               => new sfWidgetFormInputText(),
      'ufacnoexis'              => new sfWidgetFormInputText(),
      'ulimitever'              => new sfWidgetFormInputText(),
      'urecargos'               => new sfWidgetFormInputText(),
      'unombcli'                => new sfWidgetFormInputText(),
      'urif'                    => new sfWidgetFormInputText(),
      'unit'                    => new sfWidgetFormInputText(),
      'uperscont'               => new sfWidgetFormInputText(),
      'ufechaemi'               => new sfWidgetFormInputText(),
      'unumord'                 => new sfWidgetFormInputText(),
      'udiascred'               => new sfWidgetFormInputText(),
      'uimprirec'               => new sfWidgetFormInputText(),
      'uinivend'                => new sfWidgetFormInputText(),
      'uavisreord'              => new sfWidgetFormInputText(),
      'ureferenc'               => new sfWidgetFormInputText(),
      'cliente'                 => new sfWidgetFormInputText(),
      'vendedor'                => new sfWidgetFormInputText(),
      'almacen'                 => new sfWidgetFormInputText(),
      'clavborrar'              => new sfWidgetFormInputText(),
      'clavmodif'               => new sfWidgetFormInputText(),
      'clavaborta'              => new sfWidgetFormInputText(),
      'pregcantid'              => new sfWidgetFormInputText(),
      'pregconcep'              => new sfWidgetFormInputText(),
      'numpuertovisor'          => new sfWidgetFormInputText(),
      'portvisor'               => new sfWidgetFormInputText(),
      'numpuerto'               => new sfWidgetFormInputText(),
      'portgaveta'              => new sfWidgetFormInputText(),
      'formatofac'              => new sfWidgetFormInputText(),
      'formatofac2'             => new sfWidgetFormInputText(),
      'multicomis'              => new sfWidgetFormInputText(),
      'upushenter'              => new sfWidgetFormInputText(),
      'upushvend'               => new sfWidgetFormInputText(),
      'rutainv'                 => new sfWidgetFormInputText(),
      'pagagas'                 => new sfWidgetFormInputText(),
      'imprimefac'              => new sfWidgetFormInputText(),
      'tipoconsul'              => new sfWidgetFormInputText(),
      'serialcall'              => new sfWidgetFormInputText(),
      'serialcallc'             => new sfWidgetFormInputText(),
      'serialval'               => new sfWidgetFormInputText(),
      'consefac'                => new sfWidgetFormInputText(),
      'umanualfac'              => new sfWidgetFormInputText(),
      'opc_cxc'                 => new sfWidgetFormInputText(),
      'opc_cxp'                 => new sfWidgetFormInputText(),
      'integracob'              => new sfWidgetFormInputText(),
      'cobracombi'              => new sfWidgetFormInputText(),
      'udet_impu'               => new sfWidgetFormInputText(),
      'metodobus'               => new sfWidgetFormInputText(),
      'sale_pven'               => new sfWidgetFormInputText(),
      'deja_pend'               => new sfWidgetFormInputText(),
      'validacont'              => new sfWidgetFormInputText(),
      'opc_cyber'               => new sfWidgetFormInputText(),
      'vigenciadesde'           => new sfWidgetFormDate(),
      'vigenciahasta'           => new sfWidgetFormDate(),
      'sevence'                 => new sfWidgetFormInputText(),
      'desactivo'               => new sfWidgetFormInputText(),
      'hacedevolucion'          => new sfWidgetFormInputText(),
      'cargainv'                => new sfWidgetFormInputText(),
      'descargainv'             => new sfWidgetFormInputText(),
      'abonaespera'             => new sfWidgetFormInputText(),
      'veraexistencia'          => new sfWidgetFormInputText(),
      'gennotaent'              => new sfWidgetFormInputText(),
      'usatutor'                => new sfWidgetFormInputText(),
      'hablatutor'              => new sfWidgetFormInputText(),
      'rutatutor'               => new sfWidgetFormInputText(),
      'editatotlin'             => new sfWidgetFormInputText(),
      'topeajuste'              => new sfWidgetFormInputText(),
      'espguardar'              => new sfWidgetFormInputText(),
      'espsinefecto'            => new sfWidgetFormInputText(),
      'espprint'                => new sfWidgetFormInputText(),
      'esptotalizar'            => new sfWidgetFormInputText(),
      'esptrasladar'            => new sfWidgetFormInputText(),
      'serie_b'                 => new sfWidgetFormInputText(),
      'serie_c'                 => new sfWidgetFormInputText(),
      'serie_d'                 => new sfWidgetFormInputText(),
      'serie_e'                 => new sfWidgetFormInputText(),
      'serie_1_fac'             => new sfWidgetFormInputText(),
      'serie_2_fac'             => new sfWidgetFormInputText(),
      'usaunidagrup'            => new sfWidgetFormInputText(),
      'usauniddinamica'         => new sfWidgetFormInputText(),
      'pregdatoscli'            => new sfWidgetFormInputText(),
      'dejarsinefecto'          => new sfWidgetFormInputText(),
      'cerrarespera'            => new sfWidgetFormInputText(),
      'maxvuelto'               => new sfWidgetFormInputText(),
      'keyinscreen'             => new sfWidgetFormInputText(),
      'rest_precios'            => new sfWidgetFormInputText(),
      'rest_saldos'             => new sfWidgetFormInputText(),
      'rest_gaveta'             => new sfWidgetFormInputText(),
      'rest_reportes'           => new sfWidgetFormInputText(),
      'rest_guardar'            => new sfWidgetFormInputText(),
      'rest_aborta'             => new sfWidgetFormInputText(),
      'rest_print'              => new sfWidgetFormInputText(),
      'rest_trasladar'          => new sfWidgetFormInputText(),
      'rest_totalizar'          => new sfWidgetFormInputText(),
      'validabancos'            => new sfWidgetFormInputText(),
      'vende_agrup'             => new sfWidgetFormInputText(),
      'compra_agrup'            => new sfWidgetFormInputText(),
      'transacesp'              => new sfWidgetFormInputText(),
      'nroseriepven'            => new sfWidgetFormInputText(),
      'auditapven'              => new sfWidgetFormInputText(),
      'btnpven'                 => new sfWidgetFormInputText(),
      'copiasfac'               => new sfWidgetFormInputText(),
      'copiasfac2'              => new sfWidgetFormInputText(),
      'tipopven'                => new sfWidgetFormInputText(),
      'cobroelectron'           => new sfWidgetFormInputText(),
      'printpinpad'             => new sfWidgetFormInputText(),
      'habcobroelec'            => new sfWidgetFormInputText(),
      'resumlineas'             => new sfWidgetFormInputText(),
      'printcomandas'           => new sfWidgetFormInputText(),
      'formatorec'              => new sfWidgetFormInputText(),
      'formatoneg'              => new sfWidgetFormInputText(),
      'empresa'                 => new sfWidgetFormInputText(),
      'agencia'                 => new sfWidgetFormInputText(),
      'grupodefault'            => new sfWidgetFormInputText(),
      'omitiroferta'            => new sfWidgetFormInputText(),
      'cliente_espera'          => new sfWidgetFormInputText(),
      'omitirconvenioscli'      => new sfWidgetFormInputText(),
      'rutaquery'               => new sfWidgetFormInputText(),
      'rutareporte'             => new sfWidgetFormInputText(),
      'ctrl_legal_vta'          => new sfWidgetFormInputText(),
      'ordentouch'              => new sfWidgetFormInputText(),
      'ocultabotonsearchinv'    => new sfWidgetFormInputText(),
      'lineasfac'               => new sfWidgetFormInputText(),
      'mail_servidor'           => new sfWidgetFormInputText(),
      'mail_puerto'             => new sfWidgetFormInputText(),
      'mail_login'              => new sfWidgetFormInputText(),
      'mail_password'           => new sfWidgetFormInputText(),
      'mail_autenticacion'      => new sfWidgetFormInputText(),
      'deskfinancial'           => new sfWidgetFormInputText(),
      'aplicaranc'              => new sfWidgetFormInputText(),
      'printcomandafiscal'      => new sfWidgetFormInputText(),
      'printcomandaunica'       => new sfWidgetFormInputText(),
      'frmcomanda'              => new sfWidgetFormInputText(),
      'copiascomanda'           => new sfWidgetFormInputText(),
      'activavencimientoalerta' => new sfWidgetFormInputText(),
      'serie_fac_normal'        => new sfWidgetFormInputText(),
      'serie_fac_pven'          => new sfWidgetFormInputText(),
      'serie_fac_fiscal'        => new sfWidgetFormInputText(),
    ));

    $this->setValidators(array(
      'id_empresa'              => new sfValidatorString(array('max_length' => 6)),
      'nombre'                  => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'cedula'                  => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'direccion'               => new sfValidatorString(array('max_length' => 70, 'required' => false)),
      'telefono'                => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'email'                   => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'website'                 => new sfValidatorString(array('max_length' => 70, 'required' => false)),
      'username'                => new sfValidatorDoctrineChoice(array('model' => $this->getModelName(), 'column' => 'username', 'required' => false)),
      'nickname'                => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'userid'                  => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'fechanac'                => new sfValidatorDate(array('required' => false)),
      'uaddinfo'                => new sfValidatorNumber(array('required' => false)),
      'umodinfo'                => new sfValidatorNumber(array('required' => false)),
      'ukillinfo'               => new sfValidatorNumber(array('required' => false)),
      'uversalban'              => new sfValidatorNumber(array('required' => false)),
      'uaccecosto'              => new sfValidatorNumber(array('required' => false)),
      'uaccdepina'              => new sfValidatorNumber(array('required' => false)),
      'ualterprec'              => new sfValidatorNumber(array('required' => false)),
      'ualtnomart'              => new sfValidatorNumber(array('required' => false)),
      'uimpordocv'              => new sfValidatorNumber(array('required' => false)),
      'uimpordocc'              => new sfValidatorNumber(array('required' => false)),
      'ucreclient'              => new sfValidatorNumber(array('required' => false)),
      'ucambvend'               => new sfValidatorNumber(array('required' => false)),
      'umodipre'                => new sfValidatorNumber(array('required' => false)),
      'useltippre'              => new sfValidatorNumber(array('required' => false)),
      'uconsimpu'               => new sfValidatorNumber(array('required' => false)),
      'uperfsuper'              => new sfValidatorNumber(array('required' => false)),
      'uacceconf'               => new sfValidatorNumber(array('required' => false)),
      'ucreauser'               => new sfValidatorNumber(array('required' => false)),
      'umodiform'               => new sfValidatorNumber(array('required' => false)),
      'useldeposi'              => new sfValidatorNumber(array('required' => false)),
      'uprecio1'                => new sfValidatorNumber(array('required' => false)),
      'uprecio2'                => new sfValidatorNumber(array('required' => false)),
      'uprecio3'                => new sfValidatorNumber(array('required' => false)),
      'uprecio4'                => new sfValidatorNumber(array('required' => false)),
      'uprecio5'                => new sfValidatorNumber(array('required' => false)),
      'uprecio6'                => new sfValidatorNumber(array('required' => false)),
      'uprecio7'                => new sfValidatorNumber(array('required' => false)),
      'uprecio8'                => new sfValidatorNumber(array('required' => false)),
      'udesl1'                  => new sfValidatorNumber(array('required' => false)),
      'udesl2'                  => new sfValidatorNumber(array('required' => false)),
      'udesl3'                  => new sfValidatorNumber(array('required' => false)),
      'udesl4'                  => new sfValidatorNumber(array('required' => false)),
      'udesl5'                  => new sfValidatorNumber(array('required' => false)),
      'udesl6'                  => new sfValidatorNumber(array('required' => false)),
      'udesl7'                  => new sfValidatorNumber(array('required' => false)),
      'udesl8'                  => new sfValidatorNumber(array('required' => false)),
      'novaldscto'              => new sfValidatorNumber(array('required' => false)),
      'udesfin1'                => new sfValidatorNumber(array('required' => false)),
      'udesfin2'                => new sfValidatorNumber(array('required' => false)),
      'uautoriza'               => new sfValidatorNumber(array('required' => false)),
      'ufacnoexis'              => new sfValidatorNumber(array('required' => false)),
      'ulimitever'              => new sfValidatorNumber(array('required' => false)),
      'urecargos'               => new sfValidatorNumber(array('required' => false)),
      'unombcli'                => new sfValidatorNumber(array('required' => false)),
      'urif'                    => new sfValidatorNumber(array('required' => false)),
      'unit'                    => new sfValidatorNumber(array('required' => false)),
      'uperscont'               => new sfValidatorNumber(array('required' => false)),
      'ufechaemi'               => new sfValidatorNumber(array('required' => false)),
      'unumord'                 => new sfValidatorNumber(array('required' => false)),
      'udiascred'               => new sfValidatorNumber(array('required' => false)),
      'uimprirec'               => new sfValidatorNumber(array('required' => false)),
      'uinivend'                => new sfValidatorNumber(array('required' => false)),
      'uavisreord'              => new sfValidatorNumber(array('required' => false)),
      'ureferenc'               => new sfValidatorNumber(array('required' => false)),
      'cliente'                 => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'vendedor'                => new sfValidatorString(array('max_length' => 8, 'required' => false)),
      'almacen'                 => new sfValidatorString(array('max_length' => 2, 'required' => false)),
      'clavborrar'              => new sfValidatorNumber(array('required' => false)),
      'clavmodif'               => new sfValidatorNumber(array('required' => false)),
      'clavaborta'              => new sfValidatorNumber(array('required' => false)),
      'pregcantid'              => new sfValidatorNumber(array('required' => false)),
      'pregconcep'              => new sfValidatorNumber(array('required' => false)),
      'numpuertovisor'          => new sfValidatorNumber(array('required' => false)),
      'portvisor'               => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'numpuerto'               => new sfValidatorNumber(array('required' => false)),
      'portgaveta'              => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'formatofac'              => new sfValidatorString(array('max_length' => 13, 'required' => false)),
      'formatofac2'             => new sfValidatorString(array('max_length' => 13, 'required' => false)),
      'multicomis'              => new sfValidatorNumber(array('required' => false)),
      'upushenter'              => new sfValidatorNumber(array('required' => false)),
      'upushvend'               => new sfValidatorNumber(array('required' => false)),
      'rutainv'                 => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'pagagas'                 => new sfValidatorNumber(array('required' => false)),
      'imprimefac'              => new sfValidatorNumber(array('required' => false)),
      'tipoconsul'              => new sfValidatorNumber(array('required' => false)),
      'serialcall'              => new sfValidatorNumber(array('required' => false)),
      'serialcallc'             => new sfValidatorNumber(array('required' => false)),
      'serialval'               => new sfValidatorNumber(array('required' => false)),
      'consefac'                => new sfValidatorNumber(array('required' => false)),
      'umanualfac'              => new sfValidatorNumber(array('required' => false)),
      'opc_cxc'                 => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'opc_cxp'                 => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'integracob'              => new sfValidatorNumber(array('required' => false)),
      'cobracombi'              => new sfValidatorNumber(array('required' => false)),
      'udet_impu'               => new sfValidatorNumber(array('required' => false)),
      'metodobus'               => new sfValidatorNumber(array('required' => false)),
      'sale_pven'               => new sfValidatorNumber(array('required' => false)),
      'deja_pend'               => new sfValidatorNumber(array('required' => false)),
      'validacont'              => new sfValidatorNumber(array('required' => false)),
      'opc_cyber'               => new sfValidatorString(array('max_length' => 14, 'required' => false)),
      'vigenciadesde'           => new sfValidatorDate(array('required' => false)),
      'vigenciahasta'           => new sfValidatorDate(array('required' => false)),
      'sevence'                 => new sfValidatorNumber(array('required' => false)),
      'desactivo'               => new sfValidatorNumber(array('required' => false)),
      'hacedevolucion'          => new sfValidatorNumber(array('required' => false)),
      'cargainv'                => new sfValidatorNumber(array('required' => false)),
      'descargainv'             => new sfValidatorNumber(array('required' => false)),
      'abonaespera'             => new sfValidatorNumber(array('required' => false)),
      'veraexistencia'          => new sfValidatorNumber(array('required' => false)),
      'gennotaent'              => new sfValidatorNumber(array('required' => false)),
      'usatutor'                => new sfValidatorNumber(array('required' => false)),
      'hablatutor'              => new sfValidatorNumber(array('required' => false)),
      'rutatutor'               => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'editatotlin'             => new sfValidatorNumber(array('required' => false)),
      'topeajuste'              => new sfValidatorNumber(array('required' => false)),
      'espguardar'              => new sfValidatorNumber(array('required' => false)),
      'espsinefecto'            => new sfValidatorNumber(array('required' => false)),
      'espprint'                => new sfValidatorNumber(array('required' => false)),
      'esptotalizar'            => new sfValidatorNumber(array('required' => false)),
      'esptrasladar'            => new sfValidatorNumber(array('required' => false)),
      'serie_b'                 => new sfValidatorNumber(array('required' => false)),
      'serie_c'                 => new sfValidatorNumber(array('required' => false)),
      'serie_d'                 => new sfValidatorNumber(array('required' => false)),
      'serie_e'                 => new sfValidatorNumber(array('required' => false)),
      'serie_1_fac'             => new sfValidatorNumber(array('required' => false)),
      'serie_2_fac'             => new sfValidatorNumber(array('required' => false)),
      'usaunidagrup'            => new sfValidatorNumber(array('required' => false)),
      'usauniddinamica'         => new sfValidatorNumber(array('required' => false)),
      'pregdatoscli'            => new sfValidatorNumber(array('required' => false)),
      'dejarsinefecto'          => new sfValidatorNumber(array('required' => false)),
      'cerrarespera'            => new sfValidatorNumber(array('required' => false)),
      'maxvuelto'               => new sfValidatorNumber(array('required' => false)),
      'keyinscreen'             => new sfValidatorNumber(array('required' => false)),
      'rest_precios'            => new sfValidatorNumber(array('required' => false)),
      'rest_saldos'             => new sfValidatorNumber(array('required' => false)),
      'rest_gaveta'             => new sfValidatorNumber(array('required' => false)),
      'rest_reportes'           => new sfValidatorNumber(array('required' => false)),
      'rest_guardar'            => new sfValidatorNumber(array('required' => false)),
      'rest_aborta'             => new sfValidatorNumber(array('required' => false)),
      'rest_print'              => new sfValidatorNumber(array('required' => false)),
      'rest_trasladar'          => new sfValidatorNumber(array('required' => false)),
      'rest_totalizar'          => new sfValidatorNumber(array('required' => false)),
      'validabancos'            => new sfValidatorNumber(array('required' => false)),
      'vende_agrup'             => new sfValidatorNumber(array('required' => false)),
      'compra_agrup'            => new sfValidatorNumber(array('required' => false)),
      'transacesp'              => new sfValidatorNumber(array('required' => false)),
      'nroseriepven'            => new sfValidatorNumber(array('required' => false)),
      'auditapven'              => new sfValidatorNumber(array('required' => false)),
      'btnpven'                 => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'copiasfac'               => new sfValidatorNumber(array('required' => false)),
      'copiasfac2'              => new sfValidatorNumber(array('required' => false)),
      'tipopven'                => new sfValidatorNumber(array('required' => false)),
      'cobroelectron'           => new sfValidatorNumber(array('required' => false)),
      'printpinpad'             => new sfValidatorNumber(array('required' => false)),
      'habcobroelec'            => new sfValidatorNumber(array('required' => false)),
      'resumlineas'             => new sfValidatorNumber(array('required' => false)),
      'printcomandas'           => new sfValidatorNumber(array('required' => false)),
      'formatorec'              => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'formatoneg'              => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'empresa'                 => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'agencia'                 => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'grupodefault'            => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'omitiroferta'            => new sfValidatorNumber(),
      'cliente_espera'          => new sfValidatorNumber(),
      'omitirconvenioscli'      => new sfValidatorNumber(),
      'rutaquery'               => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'rutareporte'             => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'ctrl_legal_vta'          => new sfValidatorNumber(array('required' => false)),
      'ordentouch'              => new sfValidatorNumber(array('required' => false)),
      'ocultabotonsearchinv'    => new sfValidatorNumber(array('required' => false)),
      'lineasfac'               => new sfValidatorNumber(array('required' => false)),
      'mail_servidor'           => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'mail_puerto'             => new sfValidatorNumber(array('required' => false)),
      'mail_login'              => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'mail_password'           => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'mail_autenticacion'      => new sfValidatorNumber(array('required' => false)),
      'deskfinancial'           => new sfValidatorNumber(array('required' => false)),
      'aplicaranc'              => new sfValidatorNumber(array('required' => false)),
      'printcomandafiscal'      => new sfValidatorNumber(array('required' => false)),
      'printcomandaunica'       => new sfValidatorNumber(array('required' => false)),
      'frmcomanda'              => new sfValidatorString(array('max_length' => 13, 'required' => false)),
      'copiascomanda'           => new sfValidatorNumber(array('required' => false)),
      'activavencimientoalerta' => new sfValidatorNumber(array('required' => false)),
      'serie_fac_normal'        => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'serie_fac_pven'          => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'serie_fac_fiscal'        => new sfValidatorString(array('max_length' => 6, 'required' => false)),
    ));

    $this->widgetSchema->setNameFormat('usuarios[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Usuarios';
  }

}
