generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Articulo
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          articulo
    with_doctrine_route:   true
    actions_base_class:    sfActions
    type: list

    config:
      actions: ~
      fields:  ~
      list:
        title: Artículos
        display: [=codigo, =grupo, =nombre, unidad, costo, existencia]
        max_per_page: 10
        actions:  { }
        batch_actions: { }
        object_actions:
          _edit: ~

      filter:
        display: [codigo, nombre, existencia] 
      form:    ~
      edit:
        title: Artículos
        display: [=codigo, =grupo, =nombre, unidad, costo, existencia]
        actions:  { _list: ~ }
      new:     ~
