<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Corteszeta', 'premium');

/**
 * BaseCorteszeta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $serial
 * @property string $codigo
 * @property string $nombre
 * @property string $marca
 * @property string $modelo
 * @property string $estacion
 * @property string $ubicacion
 * @property string $numeroz
 * @property date $fechaz
 * @property string $horaz
 * @property string $razonsocial
 * @property string $rif
 * @property float $facexenta
 * @property float $cantidadfac
 * @property float $bifacalicgen
 * @property float $ivafacalicgen
 * @property float $bifacalicred
 * @property float $ivafacalicred
 * @property float $bifacalicaum
 * @property float $ivafacalicaum
 * @property float $ncexenta
 * @property float $cantidadnc
 * @property float $bincalicgen
 * @property float $ivancalicgen
 * @property float $bincalicred
 * @property float $ivancalicred
 * @property float $bincalicaum
 * @property float $ivancalicaum
 * @property float $descexento
 * @property float $cantidaddesc
 * @property float $bidescalicgen
 * @property float $ivadescalicgen
 * @property float $bidescalicred
 * @property float $ivadescalicred
 * @property float $bidescalicaum
 * @property float $ivadescalicaum
 * @property string $primfact
 * @property string $ultifact
 * @property date $fechultfac
 * @property string $horaultfac
 * 
 * @method string     getIdEmpresa()      Returns the current record's "id_empresa" value
 * @method string     getAgencia()        Returns the current record's "agencia" value
 * @method string     getSerial()         Returns the current record's "serial" value
 * @method string     getCodigo()         Returns the current record's "codigo" value
 * @method string     getNombre()         Returns the current record's "nombre" value
 * @method string     getMarca()          Returns the current record's "marca" value
 * @method string     getModelo()         Returns the current record's "modelo" value
 * @method string     getEstacion()       Returns the current record's "estacion" value
 * @method string     getUbicacion()      Returns the current record's "ubicacion" value
 * @method string     getNumeroz()        Returns the current record's "numeroz" value
 * @method date       getFechaz()         Returns the current record's "fechaz" value
 * @method string     getHoraz()          Returns the current record's "horaz" value
 * @method string     getRazonsocial()    Returns the current record's "razonsocial" value
 * @method string     getRif()            Returns the current record's "rif" value
 * @method float      getFacexenta()      Returns the current record's "facexenta" value
 * @method float      getCantidadfac()    Returns the current record's "cantidadfac" value
 * @method float      getBifacalicgen()   Returns the current record's "bifacalicgen" value
 * @method float      getIvafacalicgen()  Returns the current record's "ivafacalicgen" value
 * @method float      getBifacalicred()   Returns the current record's "bifacalicred" value
 * @method float      getIvafacalicred()  Returns the current record's "ivafacalicred" value
 * @method float      getBifacalicaum()   Returns the current record's "bifacalicaum" value
 * @method float      getIvafacalicaum()  Returns the current record's "ivafacalicaum" value
 * @method float      getNcexenta()       Returns the current record's "ncexenta" value
 * @method float      getCantidadnc()     Returns the current record's "cantidadnc" value
 * @method float      getBincalicgen()    Returns the current record's "bincalicgen" value
 * @method float      getIvancalicgen()   Returns the current record's "ivancalicgen" value
 * @method float      getBincalicred()    Returns the current record's "bincalicred" value
 * @method float      getIvancalicred()   Returns the current record's "ivancalicred" value
 * @method float      getBincalicaum()    Returns the current record's "bincalicaum" value
 * @method float      getIvancalicaum()   Returns the current record's "ivancalicaum" value
 * @method float      getDescexento()     Returns the current record's "descexento" value
 * @method float      getCantidaddesc()   Returns the current record's "cantidaddesc" value
 * @method float      getBidescalicgen()  Returns the current record's "bidescalicgen" value
 * @method float      getIvadescalicgen() Returns the current record's "ivadescalicgen" value
 * @method float      getBidescalicred()  Returns the current record's "bidescalicred" value
 * @method float      getIvadescalicred() Returns the current record's "ivadescalicred" value
 * @method float      getBidescalicaum()  Returns the current record's "bidescalicaum" value
 * @method float      getIvadescalicaum() Returns the current record's "ivadescalicaum" value
 * @method string     getPrimfact()       Returns the current record's "primfact" value
 * @method string     getUltifact()       Returns the current record's "ultifact" value
 * @method date       getFechultfac()     Returns the current record's "fechultfac" value
 * @method string     getHoraultfac()     Returns the current record's "horaultfac" value
 * @method Corteszeta setIdEmpresa()      Sets the current record's "id_empresa" value
 * @method Corteszeta setAgencia()        Sets the current record's "agencia" value
 * @method Corteszeta setSerial()         Sets the current record's "serial" value
 * @method Corteszeta setCodigo()         Sets the current record's "codigo" value
 * @method Corteszeta setNombre()         Sets the current record's "nombre" value
 * @method Corteszeta setMarca()          Sets the current record's "marca" value
 * @method Corteszeta setModelo()         Sets the current record's "modelo" value
 * @method Corteszeta setEstacion()       Sets the current record's "estacion" value
 * @method Corteszeta setUbicacion()      Sets the current record's "ubicacion" value
 * @method Corteszeta setNumeroz()        Sets the current record's "numeroz" value
 * @method Corteszeta setFechaz()         Sets the current record's "fechaz" value
 * @method Corteszeta setHoraz()          Sets the current record's "horaz" value
 * @method Corteszeta setRazonsocial()    Sets the current record's "razonsocial" value
 * @method Corteszeta setRif()            Sets the current record's "rif" value
 * @method Corteszeta setFacexenta()      Sets the current record's "facexenta" value
 * @method Corteszeta setCantidadfac()    Sets the current record's "cantidadfac" value
 * @method Corteszeta setBifacalicgen()   Sets the current record's "bifacalicgen" value
 * @method Corteszeta setIvafacalicgen()  Sets the current record's "ivafacalicgen" value
 * @method Corteszeta setBifacalicred()   Sets the current record's "bifacalicred" value
 * @method Corteszeta setIvafacalicred()  Sets the current record's "ivafacalicred" value
 * @method Corteszeta setBifacalicaum()   Sets the current record's "bifacalicaum" value
 * @method Corteszeta setIvafacalicaum()  Sets the current record's "ivafacalicaum" value
 * @method Corteszeta setNcexenta()       Sets the current record's "ncexenta" value
 * @method Corteszeta setCantidadnc()     Sets the current record's "cantidadnc" value
 * @method Corteszeta setBincalicgen()    Sets the current record's "bincalicgen" value
 * @method Corteszeta setIvancalicgen()   Sets the current record's "ivancalicgen" value
 * @method Corteszeta setBincalicred()    Sets the current record's "bincalicred" value
 * @method Corteszeta setIvancalicred()   Sets the current record's "ivancalicred" value
 * @method Corteszeta setBincalicaum()    Sets the current record's "bincalicaum" value
 * @method Corteszeta setIvancalicaum()   Sets the current record's "ivancalicaum" value
 * @method Corteszeta setDescexento()     Sets the current record's "descexento" value
 * @method Corteszeta setCantidaddesc()   Sets the current record's "cantidaddesc" value
 * @method Corteszeta setBidescalicgen()  Sets the current record's "bidescalicgen" value
 * @method Corteszeta setIvadescalicgen() Sets the current record's "ivadescalicgen" value
 * @method Corteszeta setBidescalicred()  Sets the current record's "bidescalicred" value
 * @method Corteszeta setIvadescalicred() Sets the current record's "ivadescalicred" value
 * @method Corteszeta setBidescalicaum()  Sets the current record's "bidescalicaum" value
 * @method Corteszeta setIvadescalicaum() Sets the current record's "ivadescalicaum" value
 * @method Corteszeta setPrimfact()       Sets the current record's "primfact" value
 * @method Corteszeta setUltifact()       Sets the current record's "ultifact" value
 * @method Corteszeta setFechultfac()     Sets the current record's "fechultfac" value
 * @method Corteszeta setHoraultfac()     Sets the current record's "horaultfac" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCorteszeta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('corteszeta');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('serial', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('codigo', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('marca', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('modelo', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('estacion', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('ubicacion', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '80',
             ));
        $this->hasColumn('numeroz', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('fechaz', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('horaz', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '5',
             ));
        $this->hasColumn('razonsocial', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '100',
             ));
        $this->hasColumn('rif', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('facexenta', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('cantidadfac', 'float', 10, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('bifacalicgen', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ivafacalicgen', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('bifacalicred', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ivafacalicred', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('bifacalicaum', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ivafacalicaum', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ncexenta', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('cantidadnc', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('bincalicgen', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ivancalicgen', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('bincalicred', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ivancalicred', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('bincalicaum', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ivancalicaum', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('descexento', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('cantidaddesc', 'float', 10, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('bidescalicgen', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ivadescalicgen', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('bidescalicred', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ivadescalicred', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('bidescalicaum', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ivadescalicaum', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('primfact', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('ultifact', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('fechultfac', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('horaultfac', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '5',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}