<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Presupmv', 'premium');

/**
 * BasePresupmv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $documento
 * @property string $placa
 * @property string $pid
 * @property string $codclien
 * @property string $nomclien
 * @property string $almacen
 * @property string $grupo
 * @property string $subgrupo
 * @property float $usaexist
 * @property float $escompuest
 * @property float $esagrupado
 * @property float $eshijo
 * @property string $codhijo
 * @property string $codigo
 * @property string $nombre
 * @property string $notas
 * @property string $unidad
 * @property float $tipoprecio
 * @property float $preciounit
 * @property float $preciofin
 * @property float $descunit
 * @property float $descprc
 * @property float $cantsoli
 * @property float $cantentr
 * @property float $cantpedi
 * @property float $montoneto
 * @property float $montoimpu
 * @property float $montototal
 * @property string $codtecnico
 * @property string $nomtecnico
 * @property float $clasifica
 * @property float $impuesto1
 * @property float $impuesto2
 * @property float $impuesto3
 * @property float $impuesto4
 * @property float $impuesto5
 * @property float $impuesto6
 * @property string $uemisor
 * @property string $estacion
 * 
 * @method string   getIdEmpresa()  Returns the current record's "id_empresa" value
 * @method string   getAgencia()    Returns the current record's "agencia" value
 * @method string   getDocumento()  Returns the current record's "documento" value
 * @method string   getPlaca()      Returns the current record's "placa" value
 * @method string   getPid()        Returns the current record's "pid" value
 * @method string   getCodclien()   Returns the current record's "codclien" value
 * @method string   getNomclien()   Returns the current record's "nomclien" value
 * @method string   getAlmacen()    Returns the current record's "almacen" value
 * @method string   getGrupo()      Returns the current record's "grupo" value
 * @method string   getSubgrupo()   Returns the current record's "subgrupo" value
 * @method float    getUsaexist()   Returns the current record's "usaexist" value
 * @method float    getEscompuest() Returns the current record's "escompuest" value
 * @method float    getEsagrupado() Returns the current record's "esagrupado" value
 * @method float    getEshijo()     Returns the current record's "eshijo" value
 * @method string   getCodhijo()    Returns the current record's "codhijo" value
 * @method string   getCodigo()     Returns the current record's "codigo" value
 * @method string   getNombre()     Returns the current record's "nombre" value
 * @method string   getNotas()      Returns the current record's "notas" value
 * @method string   getUnidad()     Returns the current record's "unidad" value
 * @method float    getTipoprecio() Returns the current record's "tipoprecio" value
 * @method float    getPreciounit() Returns the current record's "preciounit" value
 * @method float    getPreciofin()  Returns the current record's "preciofin" value
 * @method float    getDescunit()   Returns the current record's "descunit" value
 * @method float    getDescprc()    Returns the current record's "descprc" value
 * @method float    getCantsoli()   Returns the current record's "cantsoli" value
 * @method float    getCantentr()   Returns the current record's "cantentr" value
 * @method float    getCantpedi()   Returns the current record's "cantpedi" value
 * @method float    getMontoneto()  Returns the current record's "montoneto" value
 * @method float    getMontoimpu()  Returns the current record's "montoimpu" value
 * @method float    getMontototal() Returns the current record's "montototal" value
 * @method string   getCodtecnico() Returns the current record's "codtecnico" value
 * @method string   getNomtecnico() Returns the current record's "nomtecnico" value
 * @method float    getClasifica()  Returns the current record's "clasifica" value
 * @method float    getImpuesto1()  Returns the current record's "impuesto1" value
 * @method float    getImpuesto2()  Returns the current record's "impuesto2" value
 * @method float    getImpuesto3()  Returns the current record's "impuesto3" value
 * @method float    getImpuesto4()  Returns the current record's "impuesto4" value
 * @method float    getImpuesto5()  Returns the current record's "impuesto5" value
 * @method float    getImpuesto6()  Returns the current record's "impuesto6" value
 * @method string   getUemisor()    Returns the current record's "uemisor" value
 * @method string   getEstacion()   Returns the current record's "estacion" value
 * @method Presupmv setIdEmpresa()  Sets the current record's "id_empresa" value
 * @method Presupmv setAgencia()    Sets the current record's "agencia" value
 * @method Presupmv setDocumento()  Sets the current record's "documento" value
 * @method Presupmv setPlaca()      Sets the current record's "placa" value
 * @method Presupmv setPid()        Sets the current record's "pid" value
 * @method Presupmv setCodclien()   Sets the current record's "codclien" value
 * @method Presupmv setNomclien()   Sets the current record's "nomclien" value
 * @method Presupmv setAlmacen()    Sets the current record's "almacen" value
 * @method Presupmv setGrupo()      Sets the current record's "grupo" value
 * @method Presupmv setSubgrupo()   Sets the current record's "subgrupo" value
 * @method Presupmv setUsaexist()   Sets the current record's "usaexist" value
 * @method Presupmv setEscompuest() Sets the current record's "escompuest" value
 * @method Presupmv setEsagrupado() Sets the current record's "esagrupado" value
 * @method Presupmv setEshijo()     Sets the current record's "eshijo" value
 * @method Presupmv setCodhijo()    Sets the current record's "codhijo" value
 * @method Presupmv setCodigo()     Sets the current record's "codigo" value
 * @method Presupmv setNombre()     Sets the current record's "nombre" value
 * @method Presupmv setNotas()      Sets the current record's "notas" value
 * @method Presupmv setUnidad()     Sets the current record's "unidad" value
 * @method Presupmv setTipoprecio() Sets the current record's "tipoprecio" value
 * @method Presupmv setPreciounit() Sets the current record's "preciounit" value
 * @method Presupmv setPreciofin()  Sets the current record's "preciofin" value
 * @method Presupmv setDescunit()   Sets the current record's "descunit" value
 * @method Presupmv setDescprc()    Sets the current record's "descprc" value
 * @method Presupmv setCantsoli()   Sets the current record's "cantsoli" value
 * @method Presupmv setCantentr()   Sets the current record's "cantentr" value
 * @method Presupmv setCantpedi()   Sets the current record's "cantpedi" value
 * @method Presupmv setMontoneto()  Sets the current record's "montoneto" value
 * @method Presupmv setMontoimpu()  Sets the current record's "montoimpu" value
 * @method Presupmv setMontototal() Sets the current record's "montototal" value
 * @method Presupmv setCodtecnico() Sets the current record's "codtecnico" value
 * @method Presupmv setNomtecnico() Sets the current record's "nomtecnico" value
 * @method Presupmv setClasifica()  Sets the current record's "clasifica" value
 * @method Presupmv setImpuesto1()  Sets the current record's "impuesto1" value
 * @method Presupmv setImpuesto2()  Sets the current record's "impuesto2" value
 * @method Presupmv setImpuesto3()  Sets the current record's "impuesto3" value
 * @method Presupmv setImpuesto4()  Sets the current record's "impuesto4" value
 * @method Presupmv setImpuesto5()  Sets the current record's "impuesto5" value
 * @method Presupmv setImpuesto6()  Sets the current record's "impuesto6" value
 * @method Presupmv setUemisor()    Sets the current record's "uemisor" value
 * @method Presupmv setEstacion()   Sets the current record's "estacion" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePresupmv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('presupmv');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('documento', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('placa', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('pid', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '12',
             ));
        $this->hasColumn('codclien', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('nomclien', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('almacen', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('grupo', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('subgrupo', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('usaexist', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('escompuest', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('esagrupado', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('eshijo', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('codhijo', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('codigo', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('notas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('unidad', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('tipoprecio', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('preciounit', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('preciofin', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('descunit', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('descprc', 'float', 8, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('cantsoli', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cantentr', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('cantpedi', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('montoneto', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('montoimpu', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('montototal', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('codtecnico', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('nomtecnico', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('clasifica', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('impuesto1', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto2', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto3', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto4', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto5', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto6', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('uemisor', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('estacion', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}