<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Concil', 'premium');

/**
 * BaseConcil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $codbanco
 * @property string $mes
 * @property float $nmes
 * @property float $saldo
 * 
 * @method string getIdEmpresa()  Returns the current record's "id_empresa" value
 * @method string getAgencia()    Returns the current record's "agencia" value
 * @method string getCodbanco()   Returns the current record's "codbanco" value
 * @method string getMes()        Returns the current record's "mes" value
 * @method float  getNmes()       Returns the current record's "nmes" value
 * @method float  getSaldo()      Returns the current record's "saldo" value
 * @method Concil setIdEmpresa()  Sets the current record's "id_empresa" value
 * @method Concil setAgencia()    Sets the current record's "agencia" value
 * @method Concil setCodbanco()   Sets the current record's "codbanco" value
 * @method Concil setMes()        Sets the current record's "mes" value
 * @method Concil setNmes()       Sets the current record's "nmes" value
 * @method Concil setSaldo()      Sets the current record's "saldo" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseConcil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('concil');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('codbanco', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('mes', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('nmes', 'float', 3, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('saldo', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}