<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Deptarjeta', 'premium');

/**
 * BaseDeptarjeta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $id_enlace
 * @property string $tipotarjeta
 * @property string $codtarjeta
 * @property float $monto
 * @property float $comision
 * @property float $impuesto
 * @property float $saldo
 * @property string $id_interno
 * 
 * @method string     getIdEmpresa()   Returns the current record's "id_empresa" value
 * @method string     getAgencia()     Returns the current record's "agencia" value
 * @method string     getIdEnlace()    Returns the current record's "id_enlace" value
 * @method string     getTipotarjeta() Returns the current record's "tipotarjeta" value
 * @method string     getCodtarjeta()  Returns the current record's "codtarjeta" value
 * @method float      getMonto()       Returns the current record's "monto" value
 * @method float      getComision()    Returns the current record's "comision" value
 * @method float      getImpuesto()    Returns the current record's "impuesto" value
 * @method float      getSaldo()       Returns the current record's "saldo" value
 * @method string     getIdInterno()   Returns the current record's "id_interno" value
 * @method Deptarjeta setIdEmpresa()   Sets the current record's "id_empresa" value
 * @method Deptarjeta setAgencia()     Sets the current record's "agencia" value
 * @method Deptarjeta setIdEnlace()    Sets the current record's "id_enlace" value
 * @method Deptarjeta setTipotarjeta() Sets the current record's "tipotarjeta" value
 * @method Deptarjeta setCodtarjeta()  Sets the current record's "codtarjeta" value
 * @method Deptarjeta setMonto()       Sets the current record's "monto" value
 * @method Deptarjeta setComision()    Sets the current record's "comision" value
 * @method Deptarjeta setImpuesto()    Sets the current record's "impuesto" value
 * @method Deptarjeta setSaldo()       Sets the current record's "saldo" value
 * @method Deptarjeta setIdInterno()   Sets the current record's "id_interno" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDeptarjeta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('deptarjeta');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('id_enlace', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '32',
             ));
        $this->hasColumn('tipotarjeta', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('codtarjeta', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('monto', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('comision', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('impuesto', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('saldo', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('id_interno', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '12',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}