<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Artiprov', 'premium');

/**
 * BaseArtiprov
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $codigo
 * @property string $proveedor
 * @property string $nombre
 * @property float $costonac
 * @property float $costoex
 * @property date $fechalista
 * @property string $referencia
 * @property float $marca
 * 
 * @method string   getIdEmpresa()  Returns the current record's "id_empresa" value
 * @method string   getAgencia()    Returns the current record's "agencia" value
 * @method string   getCodigo()     Returns the current record's "codigo" value
 * @method string   getProveedor()  Returns the current record's "proveedor" value
 * @method string   getNombre()     Returns the current record's "nombre" value
 * @method float    getCostonac()   Returns the current record's "costonac" value
 * @method float    getCostoex()    Returns the current record's "costoex" value
 * @method date     getFechalista() Returns the current record's "fechalista" value
 * @method string   getReferencia() Returns the current record's "referencia" value
 * @method float    getMarca()      Returns the current record's "marca" value
 * @method Artiprov setIdEmpresa()  Sets the current record's "id_empresa" value
 * @method Artiprov setAgencia()    Sets the current record's "agencia" value
 * @method Artiprov setCodigo()     Sets the current record's "codigo" value
 * @method Artiprov setProveedor()  Sets the current record's "proveedor" value
 * @method Artiprov setNombre()     Sets the current record's "nombre" value
 * @method Artiprov setCostonac()   Sets the current record's "costonac" value
 * @method Artiprov setCostoex()    Sets the current record's "costoex" value
 * @method Artiprov setFechalista() Sets the current record's "fechalista" value
 * @method Artiprov setReferencia() Sets the current record's "referencia" value
 * @method Artiprov setMarca()      Sets the current record's "marca" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseArtiprov extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artiprov');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('codigo', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('proveedor', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('nombre', 'string', 35, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '35',
             ));
        $this->hasColumn('costonac', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('costoex', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('fechalista', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('referencia', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('marca', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}