<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Clicomp', 'premium');

/**
 * BaseClicomp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $codigo
 * @property string $nombre
 * @property string $cedula
 * @property string $rutafoto
 * @property date $fechanac
 * @property string $clasificacion
 * @property string $referencia
 * @property date $fvence
 * @property string $direccion
 * @property string $telefono_movil
 * 
 * @method string  getIdEmpresa()      Returns the current record's "id_empresa" value
 * @method string  getAgencia()        Returns the current record's "agencia" value
 * @method string  getCodigo()         Returns the current record's "codigo" value
 * @method string  getNombre()         Returns the current record's "nombre" value
 * @method string  getCedula()         Returns the current record's "cedula" value
 * @method string  getRutafoto()       Returns the current record's "rutafoto" value
 * @method date    getFechanac()       Returns the current record's "fechanac" value
 * @method string  getClasificacion()  Returns the current record's "clasificacion" value
 * @method string  getReferencia()     Returns the current record's "referencia" value
 * @method date    getFvence()         Returns the current record's "fvence" value
 * @method string  getDireccion()      Returns the current record's "direccion" value
 * @method string  getTelefonoMovil()  Returns the current record's "telefono_movil" value
 * @method Clicomp setIdEmpresa()      Sets the current record's "id_empresa" value
 * @method Clicomp setAgencia()        Sets the current record's "agencia" value
 * @method Clicomp setCodigo()         Sets the current record's "codigo" value
 * @method Clicomp setNombre()         Sets the current record's "nombre" value
 * @method Clicomp setCedula()         Sets the current record's "cedula" value
 * @method Clicomp setRutafoto()       Sets the current record's "rutafoto" value
 * @method Clicomp setFechanac()       Sets the current record's "fechanac" value
 * @method Clicomp setClasificacion()  Sets the current record's "clasificacion" value
 * @method Clicomp setReferencia()     Sets the current record's "referencia" value
 * @method Clicomp setFvence()         Sets the current record's "fvence" value
 * @method Clicomp setDireccion()      Sets the current record's "direccion" value
 * @method Clicomp setTelefonoMovil()  Sets the current record's "telefono_movil" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClicomp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clicomp');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('codigo', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('nombre', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('cedula', 'string', 14, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '14',
             ));
        $this->hasColumn('rutafoto', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '100',
             ));
        $this->hasColumn('fechanac', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('clasificacion', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('referencia', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('fvence', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('direccion', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '150',
             ));
        $this->hasColumn('telefono_movil', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '100',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}