<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Relretenciones', 'premium');

/**
 * BaseRelretenciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nroretencion
 * @property string $documento
 * @property float $montoretenido
 * 
 * @method string         getNroretencion()  Returns the current record's "nroretencion" value
 * @method string         getDocumento()     Returns the current record's "documento" value
 * @method float          getMontoretenido() Returns the current record's "montoretenido" value
 * @method Relretenciones setNroretencion()  Sets the current record's "nroretencion" value
 * @method Relretenciones setDocumento()     Sets the current record's "documento" value
 * @method Relretenciones setMontoretenido() Sets the current record's "montoretenido" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRelretenciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('relretenciones');
        $this->hasColumn('nroretencion', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('documento', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('montoretenido', 'float', 19, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '19',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}