<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Agendamv', 'premium');

/**
 * BaseAgendamv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $id_empresa
 * @property string $agencia
 * @property date $fecha
 * @property string $hora
 * @property string $descrip
 * @property string $usuario
 * @property float $confiden
 * 
 * @method integer  getId()         Returns the current record's "id" value
 * @method string   getIdEmpresa()  Returns the current record's "id_empresa" value
 * @method string   getAgencia()    Returns the current record's "agencia" value
 * @method date     getFecha()      Returns the current record's "fecha" value
 * @method string   getHora()       Returns the current record's "hora" value
 * @method string   getDescrip()    Returns the current record's "descrip" value
 * @method string   getUsuario()    Returns the current record's "usuario" value
 * @method float    getConfiden()   Returns the current record's "confiden" value
 * @method Agendamv setId()         Sets the current record's "id" value
 * @method Agendamv setIdEmpresa()  Sets the current record's "id_empresa" value
 * @method Agendamv setAgencia()    Sets the current record's "agencia" value
 * @method Agendamv setFecha()      Sets the current record's "fecha" value
 * @method Agendamv setHora()       Sets the current record's "hora" value
 * @method Agendamv setDescrip()    Sets the current record's "descrip" value
 * @method Agendamv setUsuario()    Sets the current record's "usuario" value
 * @method Agendamv setConfiden()   Sets the current record's "confiden" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAgendamv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agendamv');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('hora', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('descrip', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '200',
             ));
        $this->hasColumn('usuario', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('confiden', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}