<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ordenesti', 'premium');

/**
 * BaseOrdenesti
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_empresa
 * @property string $agencia
 * @property string $documento
 * @property float $status
 * @property string $factura
 * @property date $fechafac
 * @property string $tipoorden
 * @property string $placa
 * @property string $codmarca
 * @property string $nommarca
 * @property string $codmodelo
 * @property string $nommodelo
 * @property string $codclien
 * @property string $nomclien
 * @property string $rifcli
 * @property string $nitcli
 * @property float $kilometros
 * @property string $codrespo
 * @property string $nomrespo
 * @property string $rifresp
 * @property string $nitresp
 * @property date $fecha
 * @property string $hora
 * @property string $referencia
 * @property float $tipoprecio
 * @property string $codtecnico
 * @property string $nomtecnico
 * @property string $codalmacen
 * @property string $nomalmacen
 * @property float $totneto
 * @property float $totimpu
 * @property float $totcargos
 * @property float $totdescu
 * @property float $totgeneral
 * @property float $montorep
 * @property float $montomobra
 * @property float $montotot
 * @property float $totpagado
 * @property string $notas
 * @property string $uemisor
 * @property string $estacion
 * @property date $fechacierr
 * @property string $horacierr
 * @property string $usercierr
 * @property string $estacierr
 * 
 * @method string    getIdEmpresa()  Returns the current record's "id_empresa" value
 * @method string    getAgencia()    Returns the current record's "agencia" value
 * @method string    getDocumento()  Returns the current record's "documento" value
 * @method float     getStatus()     Returns the current record's "status" value
 * @method string    getFactura()    Returns the current record's "factura" value
 * @method date      getFechafac()   Returns the current record's "fechafac" value
 * @method string    getTipoorden()  Returns the current record's "tipoorden" value
 * @method string    getPlaca()      Returns the current record's "placa" value
 * @method string    getCodmarca()   Returns the current record's "codmarca" value
 * @method string    getNommarca()   Returns the current record's "nommarca" value
 * @method string    getCodmodelo()  Returns the current record's "codmodelo" value
 * @method string    getNommodelo()  Returns the current record's "nommodelo" value
 * @method string    getCodclien()   Returns the current record's "codclien" value
 * @method string    getNomclien()   Returns the current record's "nomclien" value
 * @method string    getRifcli()     Returns the current record's "rifcli" value
 * @method string    getNitcli()     Returns the current record's "nitcli" value
 * @method float     getKilometros() Returns the current record's "kilometros" value
 * @method string    getCodrespo()   Returns the current record's "codrespo" value
 * @method string    getNomrespo()   Returns the current record's "nomrespo" value
 * @method string    getRifresp()    Returns the current record's "rifresp" value
 * @method string    getNitresp()    Returns the current record's "nitresp" value
 * @method date      getFecha()      Returns the current record's "fecha" value
 * @method string    getHora()       Returns the current record's "hora" value
 * @method string    getReferencia() Returns the current record's "referencia" value
 * @method float     getTipoprecio() Returns the current record's "tipoprecio" value
 * @method string    getCodtecnico() Returns the current record's "codtecnico" value
 * @method string    getNomtecnico() Returns the current record's "nomtecnico" value
 * @method string    getCodalmacen() Returns the current record's "codalmacen" value
 * @method string    getNomalmacen() Returns the current record's "nomalmacen" value
 * @method float     getTotneto()    Returns the current record's "totneto" value
 * @method float     getTotimpu()    Returns the current record's "totimpu" value
 * @method float     getTotcargos()  Returns the current record's "totcargos" value
 * @method float     getTotdescu()   Returns the current record's "totdescu" value
 * @method float     getTotgeneral() Returns the current record's "totgeneral" value
 * @method float     getMontorep()   Returns the current record's "montorep" value
 * @method float     getMontomobra() Returns the current record's "montomobra" value
 * @method float     getMontotot()   Returns the current record's "montotot" value
 * @method float     getTotpagado()  Returns the current record's "totpagado" value
 * @method string    getNotas()      Returns the current record's "notas" value
 * @method string    getUemisor()    Returns the current record's "uemisor" value
 * @method string    getEstacion()   Returns the current record's "estacion" value
 * @method date      getFechacierr() Returns the current record's "fechacierr" value
 * @method string    getHoracierr()  Returns the current record's "horacierr" value
 * @method string    getUsercierr()  Returns the current record's "usercierr" value
 * @method string    getEstacierr()  Returns the current record's "estacierr" value
 * @method Ordenesti setIdEmpresa()  Sets the current record's "id_empresa" value
 * @method Ordenesti setAgencia()    Sets the current record's "agencia" value
 * @method Ordenesti setDocumento()  Sets the current record's "documento" value
 * @method Ordenesti setStatus()     Sets the current record's "status" value
 * @method Ordenesti setFactura()    Sets the current record's "factura" value
 * @method Ordenesti setFechafac()   Sets the current record's "fechafac" value
 * @method Ordenesti setTipoorden()  Sets the current record's "tipoorden" value
 * @method Ordenesti setPlaca()      Sets the current record's "placa" value
 * @method Ordenesti setCodmarca()   Sets the current record's "codmarca" value
 * @method Ordenesti setNommarca()   Sets the current record's "nommarca" value
 * @method Ordenesti setCodmodelo()  Sets the current record's "codmodelo" value
 * @method Ordenesti setNommodelo()  Sets the current record's "nommodelo" value
 * @method Ordenesti setCodclien()   Sets the current record's "codclien" value
 * @method Ordenesti setNomclien()   Sets the current record's "nomclien" value
 * @method Ordenesti setRifcli()     Sets the current record's "rifcli" value
 * @method Ordenesti setNitcli()     Sets the current record's "nitcli" value
 * @method Ordenesti setKilometros() Sets the current record's "kilometros" value
 * @method Ordenesti setCodrespo()   Sets the current record's "codrespo" value
 * @method Ordenesti setNomrespo()   Sets the current record's "nomrespo" value
 * @method Ordenesti setRifresp()    Sets the current record's "rifresp" value
 * @method Ordenesti setNitresp()    Sets the current record's "nitresp" value
 * @method Ordenesti setFecha()      Sets the current record's "fecha" value
 * @method Ordenesti setHora()       Sets the current record's "hora" value
 * @method Ordenesti setReferencia() Sets the current record's "referencia" value
 * @method Ordenesti setTipoprecio() Sets the current record's "tipoprecio" value
 * @method Ordenesti setCodtecnico() Sets the current record's "codtecnico" value
 * @method Ordenesti setNomtecnico() Sets the current record's "nomtecnico" value
 * @method Ordenesti setCodalmacen() Sets the current record's "codalmacen" value
 * @method Ordenesti setNomalmacen() Sets the current record's "nomalmacen" value
 * @method Ordenesti setTotneto()    Sets the current record's "totneto" value
 * @method Ordenesti setTotimpu()    Sets the current record's "totimpu" value
 * @method Ordenesti setTotcargos()  Sets the current record's "totcargos" value
 * @method Ordenesti setTotdescu()   Sets the current record's "totdescu" value
 * @method Ordenesti setTotgeneral() Sets the current record's "totgeneral" value
 * @method Ordenesti setMontorep()   Sets the current record's "montorep" value
 * @method Ordenesti setMontomobra() Sets the current record's "montomobra" value
 * @method Ordenesti setMontotot()   Sets the current record's "montotot" value
 * @method Ordenesti setTotpagado()  Sets the current record's "totpagado" value
 * @method Ordenesti setNotas()      Sets the current record's "notas" value
 * @method Ordenesti setUemisor()    Sets the current record's "uemisor" value
 * @method Ordenesti setEstacion()   Sets the current record's "estacion" value
 * @method Ordenesti setFechacierr() Sets the current record's "fechacierr" value
 * @method Ordenesti setHoracierr()  Sets the current record's "horacierr" value
 * @method Ordenesti setUsercierr()  Sets the current record's "usercierr" value
 * @method Ordenesti setEstacierr()  Sets the current record's "estacierr" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOrdenesti extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ordenesti');
        $this->hasColumn('id_empresa', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('agencia', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('documento', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('status', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('factura', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('fechafac', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('tipoorden', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('placa', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('codmarca', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('nommarca', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('codmodelo', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('nommodelo', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('codclien', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('nomclien', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('rifcli', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('nitcli', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('kilometros', 'float', 11, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '11',
             ));
        $this->hasColumn('codrespo', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('nomrespo', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('rifresp', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('nitresp', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('hora', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('referencia', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('tipoprecio', 'float', 2, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('codtecnico', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('nomtecnico', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('codalmacen', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('nomalmacen', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('totneto', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totimpu', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totcargos', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totdescu', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totgeneral', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('montorep', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('montomobra', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('montotot', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('totpagado', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('notas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('uemisor', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('estacion', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('fechacierr', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('horacierr', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('usercierr', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('estacierr', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}