<?php

/**
 * Config form base class.
 *
 * @method Config getObject() Returns the current form's model object
 *
 * @package    exproaqua
 * @subpackage form
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 24171 2009-11-19 16:37:50Z Kris.Wallsmith $
 */
abstract class BaseConfigForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'                => new sfWidgetFormInputHidden(),
      'id_empresa'        => new sfWidgetFormInputText(),
      'nrofiscal1'        => new sfWidgetFormInputText(),
      'nrofiscal2'        => new sfWidgetFormInputText(),
      'nomfiscal1'        => new sfWidgetFormInputText(),
      'nomfiscal2'        => new sfWidgetFormInputText(),
      'direccion'         => new sfWidgetFormInputText(),
      'telefonos'         => new sfWidgetFormInputText(),
      'fax'               => new sfWidgetFormInputText(),
      'email'             => new sfWidgetFormInputText(),
      'website'           => new sfWidgetFormInputText(),
      'impuesto1'         => new sfWidgetFormInputText(),
      'impuesto2'         => new sfWidgetFormInputText(),
      'impuesto3'         => new sfWidgetFormInputText(),
      'impuesto4'         => new sfWidgetFormInputText(),
      'impuesto5'         => new sfWidgetFormInputText(),
      'impuesto6'         => new sfWidgetFormInputText(),
      'monnac'            => new sfWidgetFormInputText(),
      'monnacsimb'        => new sfWidgetFormInputText(),
      'monex'             => new sfWidgetFormInputText(),
      'monexsimb'         => new sfWidgetFormInputText(),
      'monnac2'           => new sfWidgetFormInputText(),
      'monnacsimb2'       => new sfWidgetFormInputText(),
      'dividemultiplica'  => new sfWidgetFormInputText(),
      'monedafactor'      => new sfWidgetFormInputText(),
      'aplicabsfuerte'    => new sfWidgetFormInputText(),
      'filefondo'         => new sfWidgetFormInputText(),
      'fondoscr'          => new sfWidgetFormInputText(),
      'logoemp'           => new sfWidgetFormInputText(),
      'redonimpu'         => new sfWidgetFormInputText(),
      'decimales'         => new sfWidgetFormInputText(),
      'metodoround'       => new sfWidgetFormInputText(),
      'tasacambio'        => new sfWidgetFormInputText(),
      'ssector'           => new sfWidgetFormInputText(),
      'psector'           => new sfWidgetFormInputText(),
      'scliente'          => new sfWidgetFormInputText(),
      'pcliente'          => new sfWidgetFormInputText(),
      'sagencia'          => new sfWidgetFormInputText(),
      'pagencia'          => new sfWidgetFormInputText(),
      'scomision'         => new sfWidgetFormInputText(),
      'pcomision'         => new sfWidgetFormInputText(),
      'scomprador'        => new sfWidgetFormInputText(),
      'pcomprador'        => new sfWidgetFormInputText(),
      'namecedula'        => new sfWidgetFormInputText(),
      'namerif'           => new sfWidgetFormInputText(),
      'namenit'           => new sfWidgetFormInputText(),
      'nameref1'          => new sfWidgetFormInputText(),
      'nameref2'          => new sfWidgetFormInputText(),
      'ssuplidor'         => new sfWidgetFormInputText(),
      'psuplidor'         => new sfWidgetFormInputText(),
      'sbanco'            => new sfWidgetFormInputText(),
      'pbanco'            => new sfWidgetFormInputText(),
      'pseccion'          => new sfWidgetFormInputText(),
      'sseccion'          => new sfWidgetFormInputText(),
      'pdepo'             => new sfWidgetFormInputText(),
      'sdepo'             => new sfWidgetFormInputText(),
      'ssubgrupo'         => new sfWidgetFormInputText(),
      'psubgrupo'         => new sfWidgetFormInputText(),
      'usa_tyc'           => new sfWidgetFormInputText(),
      'ptallas'           => new sfWidgetFormInputText(),
      'stallas'           => new sfWidgetFormInputText(),
      'pcolores'          => new sfWidgetFormInputText(),
      'scolores'          => new sfWidgetFormInputText(),
      'multicomis'        => new sfWidgetFormInputText(),
      'namefac'           => new sfWidgetFormInputText(),
      'namepre'           => new sfWidgetFormInputText(),
      'namenot'           => new sfWidgetFormInputText(),
      'namerec'           => new sfWidgetFormInputText(),
      'nametrans'         => new sfWidgetFormInputText(),
      'namerecc'          => new sfWidgetFormInputText(),
      'namereq'           => new sfWidgetFormInputText(),
      'namepedv'          => new sfWidgetFormInputText(),
      'pvende'            => new sfWidgetFormInputText(),
      'svende'            => new sfWidgetFormInputText(),
      'sarticulo'         => new sfWidgetFormInputText(),
      'particulo'         => new sfWidgetFormInputText(),
      'comiscob'          => new sfWidgetFormInputText(),
      'integrapag'        => new sfWidgetFormInputText(),
      'integracob'        => new sfWidgetFormInputText(),
      'creferenci'        => new sfWidgetFormInputText(),
      'prcutilfac'        => new sfWidgetFormInputText(),
      'prcutilpre'        => new sfWidgetFormInputText(),
      'prcutilnot'        => new sfWidgetFormInputText(),
      'ecostoprom'        => new sfWidgetFormInputText(),
      'metodoutil'        => new sfWidgetFormInputText(),
      'integrado'         => new sfWidgetFormInputText(),
      'ruta_cont'         => new sfWidgetFormInputText(),
      'ruta_rep'          => new sfWidgetFormInputText(),
      'detallagas'        => new sfWidgetFormInputText(),
      'compragas'         => new sfWidgetFormInputText(),
      'preciodef'         => new sfWidgetFormInputText(),
      'cimpuesto1'        => new sfWidgetFormInputText(),
      'cimpuesto2'        => new sfWidgetFormInputText(),
      'cimpuesto3'        => new sfWidgetFormInputText(),
      'ecampo1'           => new sfWidgetFormInputText(),
      'ecampo2'           => new sfWidgetFormInputText(),
      'ecampo3'           => new sfWidgetFormInputText(),
      'ecampo4'           => new sfWidgetFormInputText(),
      'ecampo5'           => new sfWidgetFormInputText(),
      'eaplicfac'         => new sfWidgetFormInputText(),
      'eaplicnot'         => new sfWidgetFormInputText(),
      'eaplicpre'         => new sfWidgetFormInputText(),
      'eaplictran'        => new sfWidgetFormInputText(),
      'eapliccob'         => new sfWidgetFormInputText(),
      'lcampo1'           => new sfWidgetFormInputText(),
      'lcampo2'           => new sfWidgetFormInputText(),
      'lcampo3'           => new sfWidgetFormInputText(),
      'lcampo4'           => new sfWidgetFormInputText(),
      'lcampo5'           => new sfWidgetFormInputText(),
      'laplicfac'         => new sfWidgetFormInputText(),
      'laplicnot'         => new sfWidgetFormInputText(),
      'lapliccob'         => new sfWidgetFormInputText(),
      'laplicpre'         => new sfWidgetFormInputText(),
      'laplictran'        => new sfWidgetFormInputText(),
      'eencab'            => new sfWidgetFormInputText(),
      'lencab'            => new sfWidgetFormInputText(),
      'contrato'          => new sfWidgetFormInputText(),
      'homematriz'        => new sfWidgetFormInputText(),
      'fectranfer'        => new sfWidgetFormDate(),
      'balanza'           => new sfWidgetFormInputText(),
      'comiparam'         => new sfWidgetFormInputText(),
      'preficon1'         => new sfWidgetFormInputText(),
      'preficon2'         => new sfWidgetFormInputText(),
      'suficon1'          => new sfWidgetFormInputText(),
      'suficon2'          => new sfWidgetFormInputText(),
      'prog_cal'          => new sfWidgetFormInputText(),
      'prog_back'         => new sfWidgetFormInputText(),
      'conservdep'        => new sfWidgetFormInputText(),
      'impuestomaster'    => new sfWidgetFormInputText(),
      'nameotro'          => new sfWidgetFormInputText(),
      'codcontivavent'    => new sfWidgetFormInputText(),
      'codcontventaneta'  => new sfWidgetFormInputText(),
      'codcontndven'      => new sfWidgetFormInputText(),
      'codcontncven'      => new sfWidgetFormInputText(),
      'codcontcaja'       => new sfWidgetFormInputText(),
      'codcontivacomp'    => new sfWidgetFormInputText(),
      'codcontnetocomp'   => new sfWidgetFormInputText(),
      'codcontndcomp'     => new sfWidgetFormInputText(),
      'codcontnccomp'     => new sfWidgetFormInputText(),
      'codcontinvbal'     => new sfWidgetFormInputText(),
      'codcontinvgyp'     => new sfWidgetFormInputText(),
      'lagencia'          => new sfWidgetFormInputText(),
      'ldeposito'         => new sfWidgetFormInputText(),
      'ltallas'           => new sfWidgetFormInputText(),
      'lcolores'          => new sfWidgetFormInputText(),
      'lgrupos'           => new sfWidgetFormInputText(),
      'larticulos'        => new sfWidgetFormInputText(),
      'lzonas'            => new sfWidgetFormInputText(),
      'ltipoprov'         => new sfWidgetFormInputText(),
      'lproveedor'        => new sfWidgetFormInputText(),
      'ltipocli'          => new sfWidgetFormInputText(),
      'lclientes'         => new sfWidgetFormInputText(),
      'llistaban'         => new sfWidgetFormInputText(),
      'ltarcred'          => new sfWidgetFormInputText(),
      'ltardeb'           => new sfWidgetFormInputText(),
      'ltipooper'         => new sfWidgetFormInputText(),
      'ltiporeten'        => new sfWidgetFormInputText(),
      'ini_periodo'       => new sfWidgetFormDate(),
      'fin_periodo'       => new sfWidgetFormDate(),
      'int_linea_cont'    => new sfWidgetFormInputText(),
      'cons_cont'         => new sfWidgetFormInputText(),
      'consing'           => new sfWidgetFormInputText(),
      'consajt'           => new sfWidgetFormInputText(),
      'conschq'           => new sfWidgetFormInputText(),
      'distribdsctofinal' => new sfWidgetFormInputText(),
      'comisobreutil'     => new sfWidgetFormInputText(),
      'formatofac1'       => new sfWidgetFormInputText(),
      'formatofac2'       => new sfWidgetFormInputText(),
      'formatofacb'       => new sfWidgetFormInputText(),
      'formatofacc'       => new sfWidgetFormInputText(),
      'formatofacd'       => new sfWidgetFormInputText(),
      'formatoface'       => new sfWidgetFormInputText(),
      'formatopre'        => new sfWidgetFormInputText(),
      'formatonot'        => new sfWidgetFormInputText(),
      'ali_normal'        => new sfWidgetFormInputText(),
      'ali_reducida'      => new sfWidgetFormInputText(),
      'ali_extendida'     => new sfWidgetFormInputText(),
      'tipocob1name'      => new sfWidgetFormInputText(),
      'rutacob1pict'      => new sfWidgetFormInputText(),
      'tipocob2name'      => new sfWidgetFormInputText(),
      'rutacob2pict'      => new sfWidgetFormInputText(),
      'tipocob3name'      => new sfWidgetFormInputText(),
      'rutacob3pict'      => new sfWidgetFormInputText(),
      'tipocob4name'      => new sfWidgetFormInputText(),
      'rutacob4pict'      => new sfWidgetFormInputText(),
      'tipocob5name'      => new sfWidgetFormInputText(),
      'rutacob5pict'      => new sfWidgetFormInputText(),
      'tipocob6name'      => new sfWidgetFormInputText(),
      'rutacob6pict'      => new sfWidgetFormInputText(),
      'esrestaurant'      => new sfWidgetFormInputText(),
      'recargo'           => new sfWidgetFormInputText(),
      'idconsumo'         => new sfWidgetFormInputText(),
      'sidconsumo'        => new sfWidgetFormInputText(),
      'cfgvisorlinea1'    => new sfWidgetFormInputText(),
      'cfgvisorlinea2'    => new sfWidgetFormInputText(),
      'cfgvisorlinea3'    => new sfWidgetFormInputText(),
      'cfgvisorlinea4'    => new sfWidgetFormInputText(),
      'faddinv1'          => new sfWidgetFormInputText(),
      'faddinv2'          => new sfWidgetFormInputText(),
      'faddinv3'          => new sfWidgetFormInputText(),
      'faddinv4'          => new sfWidgetFormInputText(),
      'faddinv5'          => new sfWidgetFormInputText(),
      'faddinv6'          => new sfWidgetFormInputText(),
      'faddinv7'          => new sfWidgetFormInputText(),
      'faddinv8'          => new sfWidgetFormInputText(),
      'faddinv9'          => new sfWidgetFormInputText(),
      'faddinv0'          => new sfWidgetFormInputText(),
      'faddcli1'          => new sfWidgetFormInputText(),
      'faddcli2'          => new sfWidgetFormInputText(),
      'faddcli3'          => new sfWidgetFormInputText(),
      'faddcli4'          => new sfWidgetFormInputText(),
      'faddcli5'          => new sfWidgetFormInputText(),
      'faddven1'          => new sfWidgetFormInputText(),
      'faddven2'          => new sfWidgetFormInputText(),
      'faddven3'          => new sfWidgetFormInputText(),
      'faddven4'          => new sfWidgetFormInputText(),
      'faddven5'          => new sfWidgetFormInputText(),
      'faddprov1'         => new sfWidgetFormInputText(),
      'faddprov2'         => new sfWidgetFormInputText(),
      'faddprov3'         => new sfWidgetFormInputText(),
      'faddprov4'         => new sfWidgetFormInputText(),
      'faddprov5'         => new sfWidgetFormInputText(),
      'rutareporte'       => new sfWidgetFormInputText(),
      'rutaquery'         => new sfWidgetFormInputText(),
      'rutaservidor'      => new sfWidgetFormInputText(),
      'cfgdecimales'      => new sfWidgetFormInputText(),
      'version'           => new sfWidgetFormInputText(),
      'patrocinado'       => new sfWidgetFormInputText(),
      'sservidor'         => new sfWidgetFormInputText(),
      'pservidor'         => new sfWidgetFormInputText(),
      'series_name'       => new sfWidgetFormInputText(),
    ));

    $this->setValidators(array(
      'id'                => new sfValidatorDoctrineChoice(array('model' => $this->getModelName(), 'column' => 'id', 'required' => false)),
      'id_empresa'        => new sfValidatorString(array('max_length' => 6)),
      'nrofiscal1'        => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'nrofiscal2'        => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'nomfiscal1'        => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'nomfiscal2'        => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'direccion'         => new sfValidatorString(array('max_length' => 160, 'required' => false)),
      'telefonos'         => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'fax'               => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'email'             => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'website'           => new sfValidatorString(array('max_length' => 90, 'required' => false)),
      'impuesto1'         => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'impuesto2'         => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'impuesto3'         => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'impuesto4'         => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'impuesto5'         => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'impuesto6'         => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'monnac'            => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'monnacsimb'        => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'monex'             => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'monexsimb'         => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'monnac2'           => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'monnacsimb2'       => new sfValidatorString(array('max_length' => 5, 'required' => false)),
      'dividemultiplica'  => new sfValidatorNumber(array('required' => false)),
      'monedafactor'      => new sfValidatorNumber(array('required' => false)),
      'aplicabsfuerte'    => new sfValidatorNumber(array('required' => false)),
      'filefondo'         => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'fondoscr'          => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'logoemp'           => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'redonimpu'         => new sfValidatorNumber(array('required' => false)),
      'decimales'         => new sfValidatorNumber(array('required' => false)),
      'metodoround'       => new sfValidatorNumber(array('required' => false)),
      'tasacambio'        => new sfValidatorNumber(array('required' => false)),
      'ssector'           => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'psector'           => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'scliente'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'pcliente'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'sagencia'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'pagencia'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'scomision'         => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'pcomision'         => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'scomprador'        => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'pcomprador'        => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'namecedula'        => new sfValidatorString(array('max_length' => 14, 'required' => false)),
      'namerif'           => new sfValidatorString(array('max_length' => 14, 'required' => false)),
      'namenit'           => new sfValidatorString(array('max_length' => 14, 'required' => false)),
      'nameref1'          => new sfValidatorString(array('max_length' => 14, 'required' => false)),
      'nameref2'          => new sfValidatorString(array('max_length' => 14, 'required' => false)),
      'ssuplidor'         => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'psuplidor'         => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'sbanco'            => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'pbanco'            => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'pseccion'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'sseccion'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'pdepo'             => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'sdepo'             => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'ssubgrupo'         => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'psubgrupo'         => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'usa_tyc'           => new sfValidatorNumber(array('required' => false)),
      'ptallas'           => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'stallas'           => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'pcolores'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'scolores'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'multicomis'        => new sfValidatorNumber(array('required' => false)),
      'namefac'           => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'namepre'           => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'namenot'           => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'namerec'           => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'nametrans'         => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'namerecc'          => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'namereq'           => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'namepedv'          => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'pvende'            => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'svende'            => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'sarticulo'         => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'particulo'         => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'comiscob'          => new sfValidatorNumber(array('required' => false)),
      'integrapag'        => new sfValidatorNumber(array('required' => false)),
      'integracob'        => new sfValidatorNumber(array('required' => false)),
      'creferenci'        => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'prcutilfac'        => new sfValidatorNumber(array('required' => false)),
      'prcutilpre'        => new sfValidatorNumber(array('required' => false)),
      'prcutilnot'        => new sfValidatorNumber(array('required' => false)),
      'ecostoprom'        => new sfValidatorNumber(array('required' => false)),
      'metodoutil'        => new sfValidatorNumber(array('required' => false)),
      'integrado'         => new sfValidatorNumber(array('required' => false)),
      'ruta_cont'         => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'ruta_rep'          => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'detallagas'        => new sfValidatorNumber(array('required' => false)),
      'compragas'         => new sfValidatorNumber(array('required' => false)),
      'preciodef'         => new sfValidatorNumber(array('required' => false)),
      'cimpuesto1'        => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'cimpuesto2'        => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'cimpuesto3'        => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'ecampo1'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'ecampo2'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'ecampo3'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'ecampo4'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'ecampo5'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'eaplicfac'         => new sfValidatorNumber(array('required' => false)),
      'eaplicnot'         => new sfValidatorNumber(array('required' => false)),
      'eaplicpre'         => new sfValidatorNumber(array('required' => false)),
      'eaplictran'        => new sfValidatorNumber(array('required' => false)),
      'eapliccob'         => new sfValidatorNumber(array('required' => false)),
      'lcampo1'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'lcampo2'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'lcampo3'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'lcampo4'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'lcampo5'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'laplicfac'         => new sfValidatorNumber(array('required' => false)),
      'laplicnot'         => new sfValidatorNumber(array('required' => false)),
      'lapliccob'         => new sfValidatorNumber(array('required' => false)),
      'laplicpre'         => new sfValidatorNumber(array('required' => false)),
      'laplictran'        => new sfValidatorNumber(array('required' => false)),
      'eencab'            => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'lencab'            => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'contrato'          => new sfValidatorNumber(array('required' => false)),
      'homematriz'        => new sfValidatorNumber(array('required' => false)),
      'fectranfer'        => new sfValidatorDate(array('required' => false)),
      'balanza'           => new sfValidatorNumber(array('required' => false)),
      'comiparam'         => new sfValidatorNumber(array('required' => false)),
      'preficon1'         => new sfValidatorNumber(array('required' => false)),
      'preficon2'         => new sfValidatorNumber(array('required' => false)),
      'suficon1'          => new sfValidatorNumber(array('required' => false)),
      'suficon2'          => new sfValidatorNumber(array('required' => false)),
      'prog_cal'          => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'prog_back'         => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'conservdep'        => new sfValidatorNumber(array('required' => false)),
      'impuestomaster'    => new sfValidatorNumber(array('required' => false)),
      'nameotro'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'codcontivavent'    => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'codcontventaneta'  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'codcontndven'      => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'codcontncven'      => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'codcontcaja'       => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'codcontivacomp'    => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'codcontnetocomp'   => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'codcontndcomp'     => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'codcontnccomp'     => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'codcontinvbal'     => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'codcontinvgyp'     => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'lagencia'          => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'ldeposito'         => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'ltallas'           => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'lcolores'          => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'lgrupos'           => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'larticulos'        => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'lzonas'            => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'ltipoprov'         => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'lproveedor'        => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'ltipocli'          => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'lclientes'         => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'llistaban'         => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'ltarcred'          => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'ltardeb'           => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'ltipooper'         => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'ltiporeten'        => new sfValidatorString(array('max_length' => 28, 'required' => false)),
      'ini_periodo'       => new sfValidatorDate(array('required' => false)),
      'fin_periodo'       => new sfValidatorDate(array('required' => false)),
      'int_linea_cont'    => new sfValidatorNumber(array('required' => false)),
      'cons_cont'         => new sfValidatorNumber(array('required' => false)),
      'consing'           => new sfValidatorString(array('max_length' => 8, 'required' => false)),
      'consajt'           => new sfValidatorString(array('max_length' => 8, 'required' => false)),
      'conschq'           => new sfValidatorString(array('max_length' => 8, 'required' => false)),
      'distribdsctofinal' => new sfValidatorNumber(array('required' => false)),
      'comisobreutil'     => new sfValidatorNumber(array('required' => false)),
      'formatofac1'       => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'formatofac2'       => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'formatofacb'       => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'formatofacc'       => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'formatofacd'       => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'formatoface'       => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'formatopre'        => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'formatonot'        => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'ali_normal'        => new sfValidatorNumber(array('required' => false)),
      'ali_reducida'      => new sfValidatorNumber(array('required' => false)),
      'ali_extendida'     => new sfValidatorNumber(array('required' => false)),
      'tipocob1name'      => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'rutacob1pict'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'tipocob2name'      => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'rutacob2pict'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'tipocob3name'      => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'rutacob3pict'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'tipocob4name'      => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'rutacob4pict'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'tipocob5name'      => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'rutacob5pict'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'tipocob6name'      => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'rutacob6pict'      => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'esrestaurant'      => new sfValidatorNumber(array('required' => false)),
      'recargo'           => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'idconsumo'         => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'sidconsumo'        => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'cfgvisorlinea1'    => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'cfgvisorlinea2'    => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'cfgvisorlinea3'    => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'cfgvisorlinea4'    => new sfValidatorNumber(array('required' => false)),
      'faddinv1'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddinv2'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddinv3'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddinv4'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddinv5'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddinv6'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddinv7'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddinv8'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddinv9'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddinv0'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddcli1'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddcli2'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddcli3'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddcli4'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddcli5'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddven1'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddven2'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddven3'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddven4'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddven5'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddprov1'         => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddprov2'         => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddprov3'         => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddprov4'         => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faddprov5'         => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'rutareporte'       => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'rutaquery'         => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'rutaservidor'      => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'cfgdecimales'      => new sfValidatorString(array('max_length' => 12, 'required' => false)),
      'version'           => new sfValidatorNumber(array('required' => false)),
      'patrocinado'       => new sfValidatorNumber(array('required' => false)),
      'sservidor'         => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'pservidor'         => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'series_name'       => new sfValidatorString(array('max_length' => 60, 'required' => false)),
    ));

    $this->widgetSchema->setNameFormat('config[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Config';
  }

}
