generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrdPro
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ord_pro
    with_doctrine_route:   true
    actions_base_class:    sfActions
    layout:                stacked

    config:
      actions: ~
      fields:
        numord:  { label: "Nro. Orden" }
        desord:  { label: "Descripción" }
        fecord:  { label: "Fecha Creación" }
        fecanu:  { label: "Fecha" }
        created_at:  { label: "Creación" }
        anulada: { attributes: { disabled: true } }
        esta_anulado: { label: "¿Anulada?" }
        new_materia_prima: { label: "Materia Prima" }
        new_productos: { label: "Productos" }
        list_materia_prima: { label: "Detalle Materia Prima" }
        list_productos: { label: "Detalle Productos" }
      list:
        title: Ordenes de Producción
        display: [=numord, =desord, fecord, esta_anulado, a_producir]
      filter:
        fields:
          anulada: { attributes: { disabled: false } }
        display: [numord, desord, fecord, anulada]
      form:    ~
      edit:
        fields:
          numord: { attributes: { readonly: true } }
        title: Editando Orden de Producción
        display: [numord, desord, anulada, _list_productos, _list_materia_prima]
        actions:
          _delete: ~
          _list: ~
      new:
        title: Nueva Orden de Producción
        display:
          Orden: [numord, desord ]
          Selección Producto: [_new_productos ]
          Productos Requeridos: [_list_productos ]
          Selección Materia Prima: [_new_materia_prima ]
          Artículos Requeridos: [_list_materia_prima ]
