<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OrdPro', 'premium');

/**
 * BaseOrdPro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $numord
 * @property string $desord
 * @property timestamp $fecord
 * @property boolean $anulada
 * @property timestamp $fecanu
 * @property boolean $reportada
 * @property timestamp $fecrep
 * @property string $documento
 * @property string $documentopro
 * @property Doctrine_Collection $productos
 * @property Doctrine_Collection $materia_prima
 * @property Cargoenc $docmatpri
 * @property Cargoenc $docpro
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getNumord()        Returns the current record's "numord" value
 * @method string              getDesord()        Returns the current record's "desord" value
 * @method timestamp           getFecord()        Returns the current record's "fecord" value
 * @method boolean             getAnulada()       Returns the current record's "anulada" value
 * @method timestamp           getFecanu()        Returns the current record's "fecanu" value
 * @method boolean             getReportada()     Returns the current record's "reportada" value
 * @method timestamp           getFecrep()        Returns the current record's "fecrep" value
 * @method string              getDocumento()     Returns the current record's "documento" value
 * @method string              getDocumentopro()  Returns the current record's "documentopro" value
 * @method Doctrine_Collection getProductos()     Returns the current record's "productos" collection
 * @method Doctrine_Collection getMateriaPrima()  Returns the current record's "materia_prima" collection
 * @method Cargoenc            getDocmatpri()     Returns the current record's "docmatpri" value
 * @method Cargoenc            getDocpro()        Returns the current record's "docpro" value
 * @method OrdPro              setId()            Sets the current record's "id" value
 * @method OrdPro              setNumord()        Sets the current record's "numord" value
 * @method OrdPro              setDesord()        Sets the current record's "desord" value
 * @method OrdPro              setFecord()        Sets the current record's "fecord" value
 * @method OrdPro              setAnulada()       Sets the current record's "anulada" value
 * @method OrdPro              setFecanu()        Sets the current record's "fecanu" value
 * @method OrdPro              setReportada()     Sets the current record's "reportada" value
 * @method OrdPro              setFecrep()        Sets the current record's "fecrep" value
 * @method OrdPro              setDocumento()     Sets the current record's "documento" value
 * @method OrdPro              setDocumentopro()  Sets the current record's "documentopro" value
 * @method OrdPro              setProductos()     Sets the current record's "productos" collection
 * @method OrdPro              setMateriaPrima()  Sets the current record's "materia_prima" collection
 * @method OrdPro              setDocmatpri()     Sets the current record's "docmatpri" value
 * @method OrdPro              setDocpro()        Sets the current record's "docpro" value
 * 
 * @package    exproaqua
 * @subpackage model
 * @author     Luis Hernández
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOrdPro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ordpro');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('numord', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             'length' => '4',
             ));
        $this->hasColumn('desord', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('fecord', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('anulada', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('fecanu', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('reportada', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('fecrep', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('documento', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '10',
             ));
        $this->hasColumn('documentopro', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '10',
             ));


        $this->index('numord_idx', array(
             'fields' => 
             array(
              0 => 'numord',
             ),
             ));
        $this->index('anulada_idx', array(
             'fields' => 
             array(
              0 => 'anulada',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OrdProPro as productos', array(
             'local' => 'id',
             'foreign' => 'ordpro_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('OrdProMatPri as materia_prima', array(
             'local' => 'id',
             'foreign' => 'ordpro_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Cargoenc as docmatpri', array(
             'local' => 'documento',
             'foreign' => 'documento'));

        $this->hasOne('Cargoenc as docpro', array(
             'local' => 'documentopro',
             'foreign' => 'documento'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}