<?php

/**
 * Usuarios filter form base class.
 *
 * @package    exproaqua
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 24171 2009-11-19 16:37:50Z Kris.Wallsmith $
 */
abstract class BaseUsuariosFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id_empresa'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nombre'                  => new sfWidgetFormFilterInput(),
      'cedula'                  => new sfWidgetFormFilterInput(),
      'direccion'               => new sfWidgetFormFilterInput(),
      'telefono'                => new sfWidgetFormFilterInput(),
      'email'                   => new sfWidgetFormFilterInput(),
      'website'                 => new sfWidgetFormFilterInput(),
      'nickname'                => new sfWidgetFormFilterInput(),
      'userid'                  => new sfWidgetFormFilterInput(),
      'fechanac'                => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'uaddinfo'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'umodinfo'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ukillinfo'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uversalban'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uaccecosto'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uaccdepina'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ualterprec'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ualtnomart'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uimpordocv'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uimpordocc'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ucreclient'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ucambvend'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'umodipre'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'useltippre'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uconsimpu'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uperfsuper'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uacceconf'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ucreauser'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'umodiform'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'useldeposi'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uprecio1'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uprecio2'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uprecio3'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uprecio4'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uprecio5'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uprecio6'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uprecio7'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uprecio8'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udesl1'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udesl2'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udesl3'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udesl4'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udesl5'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udesl6'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udesl7'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udesl8'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'novaldscto'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udesfin1'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udesfin2'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uautoriza'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ufacnoexis'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ulimitever'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'urecargos'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'unombcli'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'urif'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'unit'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uperscont'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ufechaemi'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'unumord'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udiascred'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uimprirec'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uinivend'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'uavisreord'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ureferenc'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cliente'                 => new sfWidgetFormFilterInput(),
      'vendedor'                => new sfWidgetFormFilterInput(),
      'almacen'                 => new sfWidgetFormFilterInput(),
      'clavborrar'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'clavmodif'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'clavaborta'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'pregcantid'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'pregconcep'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'numpuertovisor'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'portvisor'               => new sfWidgetFormFilterInput(),
      'numpuerto'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'portgaveta'              => new sfWidgetFormFilterInput(),
      'formatofac'              => new sfWidgetFormFilterInput(),
      'formatofac2'             => new sfWidgetFormFilterInput(),
      'multicomis'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'upushenter'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'upushvend'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rutainv'                 => new sfWidgetFormFilterInput(),
      'pagagas'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'imprimefac'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tipoconsul'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serialcall'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serialcallc'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serialval'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'consefac'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'umanualfac'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'opc_cxc'                 => new sfWidgetFormFilterInput(),
      'opc_cxp'                 => new sfWidgetFormFilterInput(),
      'integracob'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobracombi'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'udet_impu'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'metodobus'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'sale_pven'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'deja_pend'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'validacont'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'opc_cyber'               => new sfWidgetFormFilterInput(),
      'vigenciadesde'           => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'vigenciahasta'           => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'sevence'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desactivo'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'hacedevolucion'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cargainv'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'descargainv'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'abonaespera'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'veraexistencia'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'gennotaent'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'usatutor'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'hablatutor'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rutatutor'               => new sfWidgetFormFilterInput(),
      'editatotlin'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'topeajuste'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'espguardar'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'espsinefecto'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'espprint'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'esptotalizar'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'esptrasladar'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serie_b'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serie_c'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serie_d'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serie_e'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serie_1_fac'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serie_2_fac'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'usaunidagrup'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'usauniddinamica'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'pregdatoscli'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dejarsinefecto'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cerrarespera'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'maxvuelto'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'keyinscreen'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rest_precios'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rest_saldos'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rest_gaveta'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rest_reportes'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rest_guardar'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rest_aborta'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rest_print'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rest_trasladar'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rest_totalizar'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'validabancos'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'vende_agrup'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'compra_agrup'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'transacesp'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nroseriepven'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'auditapven'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'btnpven'                 => new sfWidgetFormFilterInput(),
      'copiasfac'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'copiasfac2'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tipopven'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobroelectron'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'printpinpad'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'habcobroelec'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'resumlineas'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'printcomandas'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'formatorec'              => new sfWidgetFormFilterInput(),
      'formatoneg'              => new sfWidgetFormFilterInput(),
      'empresa'                 => new sfWidgetFormFilterInput(),
      'agencia'                 => new sfWidgetFormFilterInput(),
      'grupodefault'            => new sfWidgetFormFilterInput(),
      'omitiroferta'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cliente_espera'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'omitirconvenioscli'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'rutaquery'               => new sfWidgetFormFilterInput(),
      'rutareporte'             => new sfWidgetFormFilterInput(),
      'ctrl_legal_vta'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ordentouch'              => new sfWidgetFormFilterInput(),
      'ocultabotonsearchinv'    => new sfWidgetFormFilterInput(),
      'lineasfac'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'mail_servidor'           => new sfWidgetFormFilterInput(),
      'mail_puerto'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'mail_login'              => new sfWidgetFormFilterInput(),
      'mail_password'           => new sfWidgetFormFilterInput(),
      'mail_autenticacion'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'deskfinancial'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aplicaranc'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'printcomandafiscal'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'printcomandaunica'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'frmcomanda'              => new sfWidgetFormFilterInput(),
      'copiascomanda'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'activavencimientoalerta' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'serie_fac_normal'        => new sfWidgetFormFilterInput(),
      'serie_fac_pven'          => new sfWidgetFormFilterInput(),
      'serie_fac_fiscal'        => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'id_empresa'              => new sfValidatorPass(array('required' => false)),
      'nombre'                  => new sfValidatorPass(array('required' => false)),
      'cedula'                  => new sfValidatorPass(array('required' => false)),
      'direccion'               => new sfValidatorPass(array('required' => false)),
      'telefono'                => new sfValidatorPass(array('required' => false)),
      'email'                   => new sfValidatorPass(array('required' => false)),
      'website'                 => new sfValidatorPass(array('required' => false)),
      'nickname'                => new sfValidatorPass(array('required' => false)),
      'userid'                  => new sfValidatorPass(array('required' => false)),
      'fechanac'                => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'uaddinfo'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'umodinfo'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ukillinfo'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uversalban'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uaccecosto'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uaccdepina'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ualterprec'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ualtnomart'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uimpordocv'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uimpordocc'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ucreclient'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ucambvend'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'umodipre'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'useltippre'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uconsimpu'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uperfsuper'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uacceconf'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ucreauser'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'umodiform'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'useldeposi'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uprecio1'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uprecio2'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uprecio3'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uprecio4'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uprecio5'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uprecio6'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uprecio7'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uprecio8'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udesl1'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udesl2'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udesl3'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udesl4'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udesl5'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udesl6'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udesl7'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udesl8'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'novaldscto'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udesfin1'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udesfin2'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uautoriza'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ufacnoexis'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ulimitever'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'urecargos'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'unombcli'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'urif'                    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'unit'                    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uperscont'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ufechaemi'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'unumord'                 => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udiascred'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uimprirec'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uinivend'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'uavisreord'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ureferenc'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cliente'                 => new sfValidatorPass(array('required' => false)),
      'vendedor'                => new sfValidatorPass(array('required' => false)),
      'almacen'                 => new sfValidatorPass(array('required' => false)),
      'clavborrar'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'clavmodif'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'clavaborta'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'pregcantid'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'pregconcep'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'numpuertovisor'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'portvisor'               => new sfValidatorPass(array('required' => false)),
      'numpuerto'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'portgaveta'              => new sfValidatorPass(array('required' => false)),
      'formatofac'              => new sfValidatorPass(array('required' => false)),
      'formatofac2'             => new sfValidatorPass(array('required' => false)),
      'multicomis'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'upushenter'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'upushvend'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rutainv'                 => new sfValidatorPass(array('required' => false)),
      'pagagas'                 => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'imprimefac'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tipoconsul'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'serialcall'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'serialcallc'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'serialval'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'consefac'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'umanualfac'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'opc_cxc'                 => new sfValidatorPass(array('required' => false)),
      'opc_cxp'                 => new sfValidatorPass(array('required' => false)),
      'integracob'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobracombi'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'udet_impu'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'metodobus'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'sale_pven'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'deja_pend'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'validacont'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'opc_cyber'               => new sfValidatorPass(array('required' => false)),
      'vigenciadesde'           => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'vigenciahasta'           => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'sevence'                 => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'desactivo'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'hacedevolucion'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cargainv'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'descargainv'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'abonaespera'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'veraexistencia'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'gennotaent'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'usatutor'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'hablatutor'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rutatutor'               => new sfValidatorPass(array('required' => false)),
      'editatotlin'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'topeajuste'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'espguardar'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'espsinefecto'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'espprint'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'esptotalizar'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'esptrasladar'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'serie_b'                 => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'serie_c'                 => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'serie_d'                 => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'serie_e'                 => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'serie_1_fac'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'serie_2_fac'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'usaunidagrup'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'usauniddinamica'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'pregdatoscli'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'dejarsinefecto'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cerrarespera'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'maxvuelto'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'keyinscreen'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rest_precios'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rest_saldos'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rest_gaveta'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rest_reportes'           => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rest_guardar'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rest_aborta'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rest_print'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rest_trasladar'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rest_totalizar'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'validabancos'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'vende_agrup'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'compra_agrup'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'transacesp'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'nroseriepven'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'auditapven'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'btnpven'                 => new sfValidatorPass(array('required' => false)),
      'copiasfac'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'copiasfac2'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tipopven'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobroelectron'           => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'printpinpad'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'habcobroelec'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'resumlineas'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'printcomandas'           => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'formatorec'              => new sfValidatorPass(array('required' => false)),
      'formatoneg'              => new sfValidatorPass(array('required' => false)),
      'empresa'                 => new sfValidatorPass(array('required' => false)),
      'agencia'                 => new sfValidatorPass(array('required' => false)),
      'grupodefault'            => new sfValidatorPass(array('required' => false)),
      'omitiroferta'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cliente_espera'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'omitirconvenioscli'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rutaquery'               => new sfValidatorPass(array('required' => false)),
      'rutareporte'             => new sfValidatorPass(array('required' => false)),
      'ctrl_legal_vta'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ordentouch'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ocultabotonsearchinv'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'lineasfac'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'mail_servidor'           => new sfValidatorPass(array('required' => false)),
      'mail_puerto'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'mail_login'              => new sfValidatorPass(array('required' => false)),
      'mail_password'           => new sfValidatorPass(array('required' => false)),
      'mail_autenticacion'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'deskfinancial'           => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'aplicaranc'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'printcomandafiscal'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'printcomandaunica'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'frmcomanda'              => new sfValidatorPass(array('required' => false)),
      'copiascomanda'           => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'activavencimientoalerta' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'serie_fac_normal'        => new sfValidatorPass(array('required' => false)),
      'serie_fac_pven'          => new sfValidatorPass(array('required' => false)),
      'serie_fac_fiscal'        => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('usuarios_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Usuarios';
  }

  public function getFields()
  {
    return array(
      'id_empresa'              => 'Text',
      'nombre'                  => 'Text',
      'cedula'                  => 'Text',
      'direccion'               => 'Text',
      'telefono'                => 'Text',
      'email'                   => 'Text',
      'website'                 => 'Text',
      'username'                => 'Text',
      'nickname'                => 'Text',
      'userid'                  => 'Text',
      'fechanac'                => 'Date',
      'uaddinfo'                => 'Number',
      'umodinfo'                => 'Number',
      'ukillinfo'               => 'Number',
      'uversalban'              => 'Number',
      'uaccecosto'              => 'Number',
      'uaccdepina'              => 'Number',
      'ualterprec'              => 'Number',
      'ualtnomart'              => 'Number',
      'uimpordocv'              => 'Number',
      'uimpordocc'              => 'Number',
      'ucreclient'              => 'Number',
      'ucambvend'               => 'Number',
      'umodipre'                => 'Number',
      'useltippre'              => 'Number',
      'uconsimpu'               => 'Number',
      'uperfsuper'              => 'Number',
      'uacceconf'               => 'Number',
      'ucreauser'               => 'Number',
      'umodiform'               => 'Number',
      'useldeposi'              => 'Number',
      'uprecio1'                => 'Number',
      'uprecio2'                => 'Number',
      'uprecio3'                => 'Number',
      'uprecio4'                => 'Number',
      'uprecio5'                => 'Number',
      'uprecio6'                => 'Number',
      'uprecio7'                => 'Number',
      'uprecio8'                => 'Number',
      'udesl1'                  => 'Number',
      'udesl2'                  => 'Number',
      'udesl3'                  => 'Number',
      'udesl4'                  => 'Number',
      'udesl5'                  => 'Number',
      'udesl6'                  => 'Number',
      'udesl7'                  => 'Number',
      'udesl8'                  => 'Number',
      'novaldscto'              => 'Number',
      'udesfin1'                => 'Number',
      'udesfin2'                => 'Number',
      'uautoriza'               => 'Number',
      'ufacnoexis'              => 'Number',
      'ulimitever'              => 'Number',
      'urecargos'               => 'Number',
      'unombcli'                => 'Number',
      'urif'                    => 'Number',
      'unit'                    => 'Number',
      'uperscont'               => 'Number',
      'ufechaemi'               => 'Number',
      'unumord'                 => 'Number',
      'udiascred'               => 'Number',
      'uimprirec'               => 'Number',
      'uinivend'                => 'Number',
      'uavisreord'              => 'Number',
      'ureferenc'               => 'Number',
      'cliente'                 => 'Text',
      'vendedor'                => 'Text',
      'almacen'                 => 'Text',
      'clavborrar'              => 'Number',
      'clavmodif'               => 'Number',
      'clavaborta'              => 'Number',
      'pregcantid'              => 'Number',
      'pregconcep'              => 'Number',
      'numpuertovisor'          => 'Number',
      'portvisor'               => 'Text',
      'numpuerto'               => 'Number',
      'portgaveta'              => 'Text',
      'formatofac'              => 'Text',
      'formatofac2'             => 'Text',
      'multicomis'              => 'Number',
      'upushenter'              => 'Number',
      'upushvend'               => 'Number',
      'rutainv'                 => 'Text',
      'pagagas'                 => 'Number',
      'imprimefac'              => 'Number',
      'tipoconsul'              => 'Number',
      'serialcall'              => 'Number',
      'serialcallc'             => 'Number',
      'serialval'               => 'Number',
      'consefac'                => 'Number',
      'umanualfac'              => 'Number',
      'opc_cxc'                 => 'Text',
      'opc_cxp'                 => 'Text',
      'integracob'              => 'Number',
      'cobracombi'              => 'Number',
      'udet_impu'               => 'Number',
      'metodobus'               => 'Number',
      'sale_pven'               => 'Number',
      'deja_pend'               => 'Number',
      'validacont'              => 'Number',
      'opc_cyber'               => 'Text',
      'vigenciadesde'           => 'Date',
      'vigenciahasta'           => 'Date',
      'sevence'                 => 'Number',
      'desactivo'               => 'Number',
      'hacedevolucion'          => 'Number',
      'cargainv'                => 'Number',
      'descargainv'             => 'Number',
      'abonaespera'             => 'Number',
      'veraexistencia'          => 'Number',
      'gennotaent'              => 'Number',
      'usatutor'                => 'Number',
      'hablatutor'              => 'Number',
      'rutatutor'               => 'Text',
      'editatotlin'             => 'Number',
      'topeajuste'              => 'Number',
      'espguardar'              => 'Number',
      'espsinefecto'            => 'Number',
      'espprint'                => 'Number',
      'esptotalizar'            => 'Number',
      'esptrasladar'            => 'Number',
      'serie_b'                 => 'Number',
      'serie_c'                 => 'Number',
      'serie_d'                 => 'Number',
      'serie_e'                 => 'Number',
      'serie_1_fac'             => 'Number',
      'serie_2_fac'             => 'Number',
      'usaunidagrup'            => 'Number',
      'usauniddinamica'         => 'Number',
      'pregdatoscli'            => 'Number',
      'dejarsinefecto'          => 'Number',
      'cerrarespera'            => 'Number',
      'maxvuelto'               => 'Number',
      'keyinscreen'             => 'Number',
      'rest_precios'            => 'Number',
      'rest_saldos'             => 'Number',
      'rest_gaveta'             => 'Number',
      'rest_reportes'           => 'Number',
      'rest_guardar'            => 'Number',
      'rest_aborta'             => 'Number',
      'rest_print'              => 'Number',
      'rest_trasladar'          => 'Number',
      'rest_totalizar'          => 'Number',
      'validabancos'            => 'Number',
      'vende_agrup'             => 'Number',
      'compra_agrup'            => 'Number',
      'transacesp'              => 'Number',
      'nroseriepven'            => 'Number',
      'auditapven'              => 'Number',
      'btnpven'                 => 'Text',
      'copiasfac'               => 'Number',
      'copiasfac2'              => 'Number',
      'tipopven'                => 'Number',
      'cobroelectron'           => 'Number',
      'printpinpad'             => 'Number',
      'habcobroelec'            => 'Number',
      'resumlineas'             => 'Number',
      'printcomandas'           => 'Number',
      'formatorec'              => 'Text',
      'formatoneg'              => 'Text',
      'empresa'                 => 'Text',
      'agencia'                 => 'Text',
      'grupodefault'            => 'Text',
      'omitiroferta'            => 'Number',
      'cliente_espera'          => 'Number',
      'omitirconvenioscli'      => 'Number',
      'rutaquery'               => 'Text',
      'rutareporte'             => 'Text',
      'ctrl_legal_vta'          => 'Number',
      'ordentouch'              => 'Number',
      'ocultabotonsearchinv'    => 'Number',
      'lineasfac'               => 'Number',
      'mail_servidor'           => 'Text',
      'mail_puerto'             => 'Number',
      'mail_login'              => 'Text',
      'mail_password'           => 'Text',
      'mail_autenticacion'      => 'Number',
      'deskfinancial'           => 'Number',
      'aplicaranc'              => 'Number',
      'printcomandafiscal'      => 'Number',
      'printcomandaunica'       => 'Number',
      'frmcomanda'              => 'Text',
      'copiascomanda'           => 'Number',
      'activavencimientoalerta' => 'Number',
      'serie_fac_normal'        => 'Text',
      'serie_fac_pven'          => 'Text',
      'serie_fac_fiscal'        => 'Text',
    );
  }
}
