<?php

/**
 * Listvend filter form base class.
 *
 * @package    exproaqua
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 24171 2009-11-19 16:37:50Z Kris.Wallsmith $
 */
abstract class BaseListvendFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id_empresa'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'agencia'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nombre'         => new sfWidgetFormFilterInput(),
      'direccion'      => new sfWidgetFormFilterInput(),
      'comision'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'sector'         => new sfWidgetFormFilterInput(),
      'fecha'          => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'cedula'         => new sfWidgetFormFilterInput(),
      'telefonos'      => new sfWidgetFormFilterInput(),
      'telefono_movil' => new sfWidgetFormFilterInput(),
      'cobranza'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'expediente'     => new sfWidgetFormFilterInput(),
      'codigocont'     => new sfWidgetFormFilterInput(),
      'activcomi'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desde1'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desde2'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desde3'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desde4'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desde5'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desde6'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'hasta1'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'hasta2'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'hasta3'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'hasta4'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'hasta5'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'hasta6'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prccomi1'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prccomi2'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prccomi3'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prccomi4'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prccomi5'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prccomi6'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'bono1'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'bono2'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'bono3'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'bono4'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'bono5'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'bono6'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'utilvent'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aplicaramendoc' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobdesde1'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobdesde2'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobdesde3'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobdesde4'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobdesde5'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobdesde6'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobhasta1'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobhasta2'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobhasta3'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobhasta4'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobhasta5'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobhasta6'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobprccomi1'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobprccomi2'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobprccomi3'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobprccomi4'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobprccomi5'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobprccomi6'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobbono1'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobbono2'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobbono3'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobbono4'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobbono5'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cobbono6'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'valoraporcent'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'no_comi_art'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'art_prc_1'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'art_prc_2'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'art_prc_3'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'art_prc_4'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'art_prc_5'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'art_prc_6'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'art_prc_7'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'email'          => new sfWidgetFormFilterInput(),
      'campo1'         => new sfWidgetFormFilterInput(),
      'campo2'         => new sfWidgetFormFilterInput(),
      'campo3'         => new sfWidgetFormFilterInput(),
      'campo4'         => new sfWidgetFormFilterInput(),
      'campo5'         => new sfWidgetFormFilterInput(),
      'claverest'      => new sfWidgetFormFilterInput(),
      'es_servidor'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
    ));

    $this->setValidators(array(
      'id_empresa'     => new sfValidatorPass(array('required' => false)),
      'agencia'        => new sfValidatorPass(array('required' => false)),
      'nombre'         => new sfValidatorPass(array('required' => false)),
      'direccion'      => new sfValidatorPass(array('required' => false)),
      'comision'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'sector'         => new sfValidatorPass(array('required' => false)),
      'fecha'          => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'cedula'         => new sfValidatorPass(array('required' => false)),
      'telefonos'      => new sfValidatorPass(array('required' => false)),
      'telefono_movil' => new sfValidatorPass(array('required' => false)),
      'cobranza'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'expediente'     => new sfValidatorPass(array('required' => false)),
      'codigocont'     => new sfValidatorPass(array('required' => false)),
      'activcomi'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'desde1'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'desde2'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'desde3'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'desde4'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'desde5'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'desde6'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'hasta1'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'hasta2'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'hasta3'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'hasta4'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'hasta5'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'hasta6'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'prccomi1'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'prccomi2'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'prccomi3'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'prccomi4'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'prccomi5'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'prccomi6'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'bono1'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'bono2'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'bono3'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'bono4'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'bono5'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'bono6'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'utilvent'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'aplicaramendoc' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobdesde1'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobdesde2'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobdesde3'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobdesde4'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobdesde5'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobdesde6'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobhasta1'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobhasta2'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobhasta3'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobhasta4'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobhasta5'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobhasta6'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobprccomi1'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobprccomi2'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobprccomi3'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobprccomi4'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobprccomi5'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobprccomi6'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobbono1'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobbono2'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobbono3'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobbono4'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobbono5'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cobbono6'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'valoraporcent'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'no_comi_art'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'art_prc_1'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'art_prc_2'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'art_prc_3'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'art_prc_4'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'art_prc_5'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'art_prc_6'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'art_prc_7'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'email'          => new sfValidatorPass(array('required' => false)),
      'campo1'         => new sfValidatorPass(array('required' => false)),
      'campo2'         => new sfValidatorPass(array('required' => false)),
      'campo3'         => new sfValidatorPass(array('required' => false)),
      'campo4'         => new sfValidatorPass(array('required' => false)),
      'campo5'         => new sfValidatorPass(array('required' => false)),
      'claverest'      => new sfValidatorPass(array('required' => false)),
      'es_servidor'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
    ));

    $this->widgetSchema->setNameFormat('listvend_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Listvend';
  }

  public function getFields()
  {
    return array(
      'id_empresa'     => 'Text',
      'agencia'        => 'Text',
      'codigo'         => 'Text',
      'nombre'         => 'Text',
      'direccion'      => 'Text',
      'comision'       => 'Number',
      'sector'         => 'Text',
      'fecha'          => 'Date',
      'cedula'         => 'Text',
      'telefonos'      => 'Text',
      'telefono_movil' => 'Text',
      'cobranza'       => 'Number',
      'expediente'     => 'Text',
      'codigocont'     => 'Text',
      'activcomi'      => 'Number',
      'desde1'         => 'Number',
      'desde2'         => 'Number',
      'desde3'         => 'Number',
      'desde4'         => 'Number',
      'desde5'         => 'Number',
      'desde6'         => 'Number',
      'hasta1'         => 'Number',
      'hasta2'         => 'Number',
      'hasta3'         => 'Number',
      'hasta4'         => 'Number',
      'hasta5'         => 'Number',
      'hasta6'         => 'Number',
      'prccomi1'       => 'Number',
      'prccomi2'       => 'Number',
      'prccomi3'       => 'Number',
      'prccomi4'       => 'Number',
      'prccomi5'       => 'Number',
      'prccomi6'       => 'Number',
      'bono1'          => 'Number',
      'bono2'          => 'Number',
      'bono3'          => 'Number',
      'bono4'          => 'Number',
      'bono5'          => 'Number',
      'bono6'          => 'Number',
      'utilvent'       => 'Number',
      'aplicaramendoc' => 'Number',
      'cobdesde1'      => 'Number',
      'cobdesde2'      => 'Number',
      'cobdesde3'      => 'Number',
      'cobdesde4'      => 'Number',
      'cobdesde5'      => 'Number',
      'cobdesde6'      => 'Number',
      'cobhasta1'      => 'Number',
      'cobhasta2'      => 'Number',
      'cobhasta3'      => 'Number',
      'cobhasta4'      => 'Number',
      'cobhasta5'      => 'Number',
      'cobhasta6'      => 'Number',
      'cobprccomi1'    => 'Number',
      'cobprccomi2'    => 'Number',
      'cobprccomi3'    => 'Number',
      'cobprccomi4'    => 'Number',
      'cobprccomi5'    => 'Number',
      'cobprccomi6'    => 'Number',
      'cobbono1'       => 'Number',
      'cobbono2'       => 'Number',
      'cobbono3'       => 'Number',
      'cobbono4'       => 'Number',
      'cobbono5'       => 'Number',
      'cobbono6'       => 'Number',
      'valoraporcent'  => 'Number',
      'no_comi_art'    => 'Number',
      'art_prc_1'      => 'Number',
      'art_prc_2'      => 'Number',
      'art_prc_3'      => 'Number',
      'art_prc_4'      => 'Number',
      'art_prc_5'      => 'Number',
      'art_prc_6'      => 'Number',
      'art_prc_7'      => 'Number',
      'email'          => 'Text',
      'campo1'         => 'Text',
      'campo2'         => 'Text',
      'campo3'         => 'Text',
      'campo4'         => 'Text',
      'campo5'         => 'Text',
      'claverest'      => 'Text',
      'es_servidor'    => 'Number',
    );
  }
}
