<?php

/**
 * Tmpmv filter form base class.
 *
 * @package    exproaqua
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 24171 2009-11-19 16:37:50Z Kris.Wallsmith $
 */
abstract class BaseTmpmvFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id_empresa' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'agencia'    => new sfWidgetFormFilterInput(),
      'tipodoc'    => new sfWidgetFormFilterInput(),
      'documento'  => new sfWidgetFormFilterInput(),
      'grupo'      => new sfWidgetFormFilterInput(),
      'subgrupo'   => new sfWidgetFormFilterInput(),
      'origen'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'codigo'     => new sfWidgetFormFilterInput(),
      'codhijo'    => new sfWidgetFormFilterInput(),
      'pid'        => new sfWidgetFormFilterInput(),
      'nombre'     => new sfWidgetFormFilterInput(),
      'costounit'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'preciounit' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'diferencia' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dsctounit'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dsctoprc'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dsctoendm'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'dsctoendp'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'preciofin'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prcrecargo' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'recargouni' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'precioorig' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cantidad'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cntdevuelt' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cntentrega' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tallas'     => new sfWidgetFormFilterInput(),
      'colores'    => new sfWidgetFormFilterInput(),
      'montoneto'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'montototal' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'almacen'    => new sfWidgetFormFilterInput(),
      'proveedor'  => new sfWidgetFormFilterInput(),
      'fechadoc'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'impuesto1'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'impuesto2'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'impuesto3'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'impuesto4'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'impuesto5'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'impuesto6'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'timpueprc'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'impu_mto'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comision'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comisprc'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'vendedor'   => new sfWidgetFormFilterInput(),
      'emisor'     => new sfWidgetFormFilterInput(),
      'usaserial'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tipoprecio' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'unidad'     => new sfWidgetFormFilterInput(),
      'agrupado'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cntagrupad' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'seimporto'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desdeimpor' => new sfWidgetFormFilterInput(),
      'notas'      => new sfWidgetFormFilterInput(),
      'oferta'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'compuesto'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'usaexist'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'marca'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aux1'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'estacion'   => new sfWidgetFormFilterInput(),
      'clasifica'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cuentacont' => new sfWidgetFormFilterInput(),
      'placa'      => new sfWidgetFormFilterInput(),
      'udinamica'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cantref'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'unidadref'  => new sfWidgetFormFilterInput(),
      'baseimpo1'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'baseimpo2'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'baseimpo3'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'lote'       => new sfWidgetFormFilterInput(),
      'imp_nacion' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'imp_produc' => new sfWidgetFormFilterInput(array('with_empty' => false)),
    ));

    $this->setValidators(array(
      'id_empresa' => new sfValidatorPass(array('required' => false)),
      'agencia'    => new sfValidatorPass(array('required' => false)),
      'tipodoc'    => new sfValidatorPass(array('required' => false)),
      'documento'  => new sfValidatorPass(array('required' => false)),
      'grupo'      => new sfValidatorPass(array('required' => false)),
      'subgrupo'   => new sfValidatorPass(array('required' => false)),
      'origen'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'codigo'     => new sfValidatorPass(array('required' => false)),
      'codhijo'    => new sfValidatorPass(array('required' => false)),
      'pid'        => new sfValidatorPass(array('required' => false)),
      'nombre'     => new sfValidatorPass(array('required' => false)),
      'costounit'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'preciounit' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'diferencia' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'dsctounit'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'dsctoprc'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'dsctoendm'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'dsctoendp'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'preciofin'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'prcrecargo' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'recargouni' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'precioorig' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cantidad'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cntdevuelt' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cntentrega' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tallas'     => new sfValidatorPass(array('required' => false)),
      'colores'    => new sfValidatorPass(array('required' => false)),
      'montoneto'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'montototal' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'almacen'    => new sfValidatorPass(array('required' => false)),
      'proveedor'  => new sfValidatorPass(array('required' => false)),
      'fechadoc'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'impuesto1'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'impuesto2'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'impuesto3'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'impuesto4'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'impuesto5'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'impuesto6'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'timpueprc'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'impu_mto'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comision'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comisprc'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'vendedor'   => new sfValidatorPass(array('required' => false)),
      'emisor'     => new sfValidatorPass(array('required' => false)),
      'usaserial'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tipoprecio' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'unidad'     => new sfValidatorPass(array('required' => false)),
      'agrupado'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cntagrupad' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'seimporto'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'desdeimpor' => new sfValidatorPass(array('required' => false)),
      'notas'      => new sfValidatorPass(array('required' => false)),
      'oferta'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'compuesto'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'usaexist'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'marca'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'aux1'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'estacion'   => new sfValidatorPass(array('required' => false)),
      'clasifica'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cuentacont' => new sfValidatorPass(array('required' => false)),
      'placa'      => new sfValidatorPass(array('required' => false)),
      'udinamica'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cantref'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'unidadref'  => new sfValidatorPass(array('required' => false)),
      'baseimpo1'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'baseimpo2'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'baseimpo3'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'lote'       => new sfValidatorPass(array('required' => false)),
      'imp_nacion' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'imp_produc' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
    ));

    $this->widgetSchema->setNameFormat('tmpmv_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Tmpmv';
  }

  public function getFields()
  {
    return array(
      'id'         => 'Number',
      'id_empresa' => 'Text',
      'agencia'    => 'Text',
      'tipodoc'    => 'Text',
      'documento'  => 'Text',
      'grupo'      => 'Text',
      'subgrupo'   => 'Text',
      'origen'     => 'Number',
      'codigo'     => 'Text',
      'codhijo'    => 'Text',
      'pid'        => 'Text',
      'nombre'     => 'Text',
      'costounit'  => 'Number',
      'preciounit' => 'Number',
      'diferencia' => 'Number',
      'dsctounit'  => 'Number',
      'dsctoprc'   => 'Number',
      'dsctoendm'  => 'Number',
      'dsctoendp'  => 'Number',
      'preciofin'  => 'Number',
      'prcrecargo' => 'Number',
      'recargouni' => 'Number',
      'precioorig' => 'Number',
      'cantidad'   => 'Number',
      'cntdevuelt' => 'Number',
      'cntentrega' => 'Number',
      'tallas'     => 'Text',
      'colores'    => 'Text',
      'montoneto'  => 'Number',
      'montototal' => 'Number',
      'almacen'    => 'Text',
      'proveedor'  => 'Text',
      'fechadoc'   => 'Date',
      'impuesto1'  => 'Number',
      'impuesto2'  => 'Number',
      'impuesto3'  => 'Number',
      'impuesto4'  => 'Number',
      'impuesto5'  => 'Number',
      'impuesto6'  => 'Number',
      'timpueprc'  => 'Number',
      'impu_mto'   => 'Number',
      'comision'   => 'Number',
      'comisprc'   => 'Number',
      'vendedor'   => 'Text',
      'emisor'     => 'Text',
      'usaserial'  => 'Number',
      'tipoprecio' => 'Number',
      'unidad'     => 'Text',
      'agrupado'   => 'Number',
      'cntagrupad' => 'Number',
      'seimporto'  => 'Number',
      'desdeimpor' => 'Text',
      'notas'      => 'Text',
      'oferta'     => 'Number',
      'compuesto'  => 'Number',
      'usaexist'   => 'Number',
      'marca'      => 'Number',
      'aux1'       => 'Number',
      'estacion'   => 'Text',
      'clasifica'  => 'Number',
      'cuentacont' => 'Text',
      'placa'      => 'Text',
      'udinamica'  => 'Number',
      'cantref'    => 'Number',
      'unidadref'  => 'Text',
      'baseimpo1'  => 'Number',
      'baseimpo2'  => 'Number',
      'baseimpo3'  => 'Number',
      'lote'       => 'Text',
      'imp_nacion' => 'Number',
      'imp_produc' => 'Number',
    );
  }
}
