<?php

/**
 * Config filter form base class.
 *
 * @package    exproaqua
 * @subpackage filter
 * @author     Luis Hernández
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 24171 2009-11-19 16:37:50Z Kris.Wallsmith $
 */
abstract class BaseConfigFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id_empresa'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nrofiscal1'        => new sfWidgetFormFilterInput(),
      'nrofiscal2'        => new sfWidgetFormFilterInput(),
      'nomfiscal1'        => new sfWidgetFormFilterInput(),
      'nomfiscal2'        => new sfWidgetFormFilterInput(),
      'direccion'         => new sfWidgetFormFilterInput(),
      'telefonos'         => new sfWidgetFormFilterInput(),
      'fax'               => new sfWidgetFormFilterInput(),
      'email'             => new sfWidgetFormFilterInput(),
      'website'           => new sfWidgetFormFilterInput(),
      'impuesto1'         => new sfWidgetFormFilterInput(),
      'impuesto2'         => new sfWidgetFormFilterInput(),
      'impuesto3'         => new sfWidgetFormFilterInput(),
      'impuesto4'         => new sfWidgetFormFilterInput(),
      'impuesto5'         => new sfWidgetFormFilterInput(),
      'impuesto6'         => new sfWidgetFormFilterInput(),
      'monnac'            => new sfWidgetFormFilterInput(),
      'monnacsimb'        => new sfWidgetFormFilterInput(),
      'monex'             => new sfWidgetFormFilterInput(),
      'monexsimb'         => new sfWidgetFormFilterInput(),
      'monnac2'           => new sfWidgetFormFilterInput(),
      'monnacsimb2'       => new sfWidgetFormFilterInput(),
      'dividemultiplica'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'monedafactor'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'aplicabsfuerte'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'filefondo'         => new sfWidgetFormFilterInput(),
      'fondoscr'          => new sfWidgetFormFilterInput(),
      'logoemp'           => new sfWidgetFormFilterInput(),
      'redonimpu'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'decimales'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'metodoround'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tasacambio'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ssector'           => new sfWidgetFormFilterInput(),
      'psector'           => new sfWidgetFormFilterInput(),
      'scliente'          => new sfWidgetFormFilterInput(),
      'pcliente'          => new sfWidgetFormFilterInput(),
      'sagencia'          => new sfWidgetFormFilterInput(),
      'pagencia'          => new sfWidgetFormFilterInput(),
      'scomision'         => new sfWidgetFormFilterInput(),
      'pcomision'         => new sfWidgetFormFilterInput(),
      'scomprador'        => new sfWidgetFormFilterInput(),
      'pcomprador'        => new sfWidgetFormFilterInput(),
      'namecedula'        => new sfWidgetFormFilterInput(),
      'namerif'           => new sfWidgetFormFilterInput(),
      'namenit'           => new sfWidgetFormFilterInput(),
      'nameref1'          => new sfWidgetFormFilterInput(),
      'nameref2'          => new sfWidgetFormFilterInput(),
      'ssuplidor'         => new sfWidgetFormFilterInput(),
      'psuplidor'         => new sfWidgetFormFilterInput(),
      'sbanco'            => new sfWidgetFormFilterInput(),
      'pbanco'            => new sfWidgetFormFilterInput(),
      'pseccion'          => new sfWidgetFormFilterInput(),
      'sseccion'          => new sfWidgetFormFilterInput(),
      'pdepo'             => new sfWidgetFormFilterInput(),
      'sdepo'             => new sfWidgetFormFilterInput(),
      'ssubgrupo'         => new sfWidgetFormFilterInput(),
      'psubgrupo'         => new sfWidgetFormFilterInput(),
      'usa_tyc'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ptallas'           => new sfWidgetFormFilterInput(),
      'stallas'           => new sfWidgetFormFilterInput(),
      'pcolores'          => new sfWidgetFormFilterInput(),
      'scolores'          => new sfWidgetFormFilterInput(),
      'multicomis'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'namefac'           => new sfWidgetFormFilterInput(),
      'namepre'           => new sfWidgetFormFilterInput(),
      'namenot'           => new sfWidgetFormFilterInput(),
      'namerec'           => new sfWidgetFormFilterInput(),
      'nametrans'         => new sfWidgetFormFilterInput(),
      'namerecc'          => new sfWidgetFormFilterInput(),
      'namereq'           => new sfWidgetFormFilterInput(),
      'namepedv'          => new sfWidgetFormFilterInput(),
      'pvende'            => new sfWidgetFormFilterInput(),
      'svende'            => new sfWidgetFormFilterInput(),
      'sarticulo'         => new sfWidgetFormFilterInput(),
      'particulo'         => new sfWidgetFormFilterInput(),
      'comiscob'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'integrapag'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'integracob'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'creferenci'        => new sfWidgetFormFilterInput(),
      'prcutilfac'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prcutilpre'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prcutilnot'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ecostoprom'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'metodoutil'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'integrado'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ruta_cont'         => new sfWidgetFormFilterInput(),
      'ruta_rep'          => new sfWidgetFormFilterInput(),
      'detallagas'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'compragas'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'preciodef'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cimpuesto1'        => new sfWidgetFormFilterInput(),
      'cimpuesto2'        => new sfWidgetFormFilterInput(),
      'cimpuesto3'        => new sfWidgetFormFilterInput(),
      'ecampo1'           => new sfWidgetFormFilterInput(),
      'ecampo2'           => new sfWidgetFormFilterInput(),
      'ecampo3'           => new sfWidgetFormFilterInput(),
      'ecampo4'           => new sfWidgetFormFilterInput(),
      'ecampo5'           => new sfWidgetFormFilterInput(),
      'eaplicfac'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'eaplicnot'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'eaplicpre'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'eaplictran'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'eapliccob'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'lcampo1'           => new sfWidgetFormFilterInput(),
      'lcampo2'           => new sfWidgetFormFilterInput(),
      'lcampo3'           => new sfWidgetFormFilterInput(),
      'lcampo4'           => new sfWidgetFormFilterInput(),
      'lcampo5'           => new sfWidgetFormFilterInput(),
      'laplicfac'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'laplicnot'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'lapliccob'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'laplicpre'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'laplictran'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'eencab'            => new sfWidgetFormFilterInput(),
      'lencab'            => new sfWidgetFormFilterInput(),
      'contrato'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'homematriz'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'fectranfer'        => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'balanza'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comiparam'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'preficon1'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'preficon2'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'suficon1'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'suficon2'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'prog_cal'          => new sfWidgetFormFilterInput(),
      'prog_back'         => new sfWidgetFormFilterInput(),
      'conservdep'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'impuestomaster'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nameotro'          => new sfWidgetFormFilterInput(),
      'codcontivavent'    => new sfWidgetFormFilterInput(),
      'codcontventaneta'  => new sfWidgetFormFilterInput(),
      'codcontndven'      => new sfWidgetFormFilterInput(),
      'codcontncven'      => new sfWidgetFormFilterInput(),
      'codcontcaja'       => new sfWidgetFormFilterInput(),
      'codcontivacomp'    => new sfWidgetFormFilterInput(),
      'codcontnetocomp'   => new sfWidgetFormFilterInput(),
      'codcontndcomp'     => new sfWidgetFormFilterInput(),
      'codcontnccomp'     => new sfWidgetFormFilterInput(),
      'codcontinvbal'     => new sfWidgetFormFilterInput(),
      'codcontinvgyp'     => new sfWidgetFormFilterInput(),
      'lagencia'          => new sfWidgetFormFilterInput(),
      'ldeposito'         => new sfWidgetFormFilterInput(),
      'ltallas'           => new sfWidgetFormFilterInput(),
      'lcolores'          => new sfWidgetFormFilterInput(),
      'lgrupos'           => new sfWidgetFormFilterInput(),
      'larticulos'        => new sfWidgetFormFilterInput(),
      'lzonas'            => new sfWidgetFormFilterInput(),
      'ltipoprov'         => new sfWidgetFormFilterInput(),
      'lproveedor'        => new sfWidgetFormFilterInput(),
      'ltipocli'          => new sfWidgetFormFilterInput(),
      'lclientes'         => new sfWidgetFormFilterInput(),
      'llistaban'         => new sfWidgetFormFilterInput(),
      'ltarcred'          => new sfWidgetFormFilterInput(),
      'ltardeb'           => new sfWidgetFormFilterInput(),
      'ltipooper'         => new sfWidgetFormFilterInput(),
      'ltiporeten'        => new sfWidgetFormFilterInput(),
      'ini_periodo'       => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'fin_periodo'       => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'int_linea_cont'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cons_cont'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'consing'           => new sfWidgetFormFilterInput(),
      'consajt'           => new sfWidgetFormFilterInput(),
      'conschq'           => new sfWidgetFormFilterInput(),
      'distribdsctofinal' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'comisobreutil'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'formatofac1'       => new sfWidgetFormFilterInput(),
      'formatofac2'       => new sfWidgetFormFilterInput(),
      'formatofacb'       => new sfWidgetFormFilterInput(),
      'formatofacc'       => new sfWidgetFormFilterInput(),
      'formatofacd'       => new sfWidgetFormFilterInput(),
      'formatoface'       => new sfWidgetFormFilterInput(),
      'formatopre'        => new sfWidgetFormFilterInput(),
      'formatonot'        => new sfWidgetFormFilterInput(),
      'ali_normal'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ali_reducida'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'ali_extendida'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'tipocob1name'      => new sfWidgetFormFilterInput(),
      'rutacob1pict'      => new sfWidgetFormFilterInput(),
      'tipocob2name'      => new sfWidgetFormFilterInput(),
      'rutacob2pict'      => new sfWidgetFormFilterInput(),
      'tipocob3name'      => new sfWidgetFormFilterInput(),
      'rutacob3pict'      => new sfWidgetFormFilterInput(),
      'tipocob4name'      => new sfWidgetFormFilterInput(),
      'rutacob4pict'      => new sfWidgetFormFilterInput(),
      'tipocob5name'      => new sfWidgetFormFilterInput(),
      'rutacob5pict'      => new sfWidgetFormFilterInput(),
      'tipocob6name'      => new sfWidgetFormFilterInput(),
      'rutacob6pict'      => new sfWidgetFormFilterInput(),
      'esrestaurant'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'recargo'           => new sfWidgetFormFilterInput(),
      'idconsumo'         => new sfWidgetFormFilterInput(),
      'sidconsumo'        => new sfWidgetFormFilterInput(),
      'cfgvisorlinea1'    => new sfWidgetFormFilterInput(),
      'cfgvisorlinea2'    => new sfWidgetFormFilterInput(),
      'cfgvisorlinea3'    => new sfWidgetFormFilterInput(),
      'cfgvisorlinea4'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'faddinv1'          => new sfWidgetFormFilterInput(),
      'faddinv2'          => new sfWidgetFormFilterInput(),
      'faddinv3'          => new sfWidgetFormFilterInput(),
      'faddinv4'          => new sfWidgetFormFilterInput(),
      'faddinv5'          => new sfWidgetFormFilterInput(),
      'faddinv6'          => new sfWidgetFormFilterInput(),
      'faddinv7'          => new sfWidgetFormFilterInput(),
      'faddinv8'          => new sfWidgetFormFilterInput(),
      'faddinv9'          => new sfWidgetFormFilterInput(),
      'faddinv0'          => new sfWidgetFormFilterInput(),
      'faddcli1'          => new sfWidgetFormFilterInput(),
      'faddcli2'          => new sfWidgetFormFilterInput(),
      'faddcli3'          => new sfWidgetFormFilterInput(),
      'faddcli4'          => new sfWidgetFormFilterInput(),
      'faddcli5'          => new sfWidgetFormFilterInput(),
      'faddven1'          => new sfWidgetFormFilterInput(),
      'faddven2'          => new sfWidgetFormFilterInput(),
      'faddven3'          => new sfWidgetFormFilterInput(),
      'faddven4'          => new sfWidgetFormFilterInput(),
      'faddven5'          => new sfWidgetFormFilterInput(),
      'faddprov1'         => new sfWidgetFormFilterInput(),
      'faddprov2'         => new sfWidgetFormFilterInput(),
      'faddprov3'         => new sfWidgetFormFilterInput(),
      'faddprov4'         => new sfWidgetFormFilterInput(),
      'faddprov5'         => new sfWidgetFormFilterInput(),
      'rutareporte'       => new sfWidgetFormFilterInput(),
      'rutaquery'         => new sfWidgetFormFilterInput(),
      'rutaservidor'      => new sfWidgetFormFilterInput(),
      'cfgdecimales'      => new sfWidgetFormFilterInput(),
      'version'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'patrocinado'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'sservidor'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'pservidor'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'series_name'       => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'id_empresa'        => new sfValidatorPass(array('required' => false)),
      'nrofiscal1'        => new sfValidatorPass(array('required' => false)),
      'nrofiscal2'        => new sfValidatorPass(array('required' => false)),
      'nomfiscal1'        => new sfValidatorPass(array('required' => false)),
      'nomfiscal2'        => new sfValidatorPass(array('required' => false)),
      'direccion'         => new sfValidatorPass(array('required' => false)),
      'telefonos'         => new sfValidatorPass(array('required' => false)),
      'fax'               => new sfValidatorPass(array('required' => false)),
      'email'             => new sfValidatorPass(array('required' => false)),
      'website'           => new sfValidatorPass(array('required' => false)),
      'impuesto1'         => new sfValidatorPass(array('required' => false)),
      'impuesto2'         => new sfValidatorPass(array('required' => false)),
      'impuesto3'         => new sfValidatorPass(array('required' => false)),
      'impuesto4'         => new sfValidatorPass(array('required' => false)),
      'impuesto5'         => new sfValidatorPass(array('required' => false)),
      'impuesto6'         => new sfValidatorPass(array('required' => false)),
      'monnac'            => new sfValidatorPass(array('required' => false)),
      'monnacsimb'        => new sfValidatorPass(array('required' => false)),
      'monex'             => new sfValidatorPass(array('required' => false)),
      'monexsimb'         => new sfValidatorPass(array('required' => false)),
      'monnac2'           => new sfValidatorPass(array('required' => false)),
      'monnacsimb2'       => new sfValidatorPass(array('required' => false)),
      'dividemultiplica'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monedafactor'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'aplicabsfuerte'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'filefondo'         => new sfValidatorPass(array('required' => false)),
      'fondoscr'          => new sfValidatorPass(array('required' => false)),
      'logoemp'           => new sfValidatorPass(array('required' => false)),
      'redonimpu'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'decimales'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'metodoround'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tasacambio'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ssector'           => new sfValidatorPass(array('required' => false)),
      'psector'           => new sfValidatorPass(array('required' => false)),
      'scliente'          => new sfValidatorPass(array('required' => false)),
      'pcliente'          => new sfValidatorPass(array('required' => false)),
      'sagencia'          => new sfValidatorPass(array('required' => false)),
      'pagencia'          => new sfValidatorPass(array('required' => false)),
      'scomision'         => new sfValidatorPass(array('required' => false)),
      'pcomision'         => new sfValidatorPass(array('required' => false)),
      'scomprador'        => new sfValidatorPass(array('required' => false)),
      'pcomprador'        => new sfValidatorPass(array('required' => false)),
      'namecedula'        => new sfValidatorPass(array('required' => false)),
      'namerif'           => new sfValidatorPass(array('required' => false)),
      'namenit'           => new sfValidatorPass(array('required' => false)),
      'nameref1'          => new sfValidatorPass(array('required' => false)),
      'nameref2'          => new sfValidatorPass(array('required' => false)),
      'ssuplidor'         => new sfValidatorPass(array('required' => false)),
      'psuplidor'         => new sfValidatorPass(array('required' => false)),
      'sbanco'            => new sfValidatorPass(array('required' => false)),
      'pbanco'            => new sfValidatorPass(array('required' => false)),
      'pseccion'          => new sfValidatorPass(array('required' => false)),
      'sseccion'          => new sfValidatorPass(array('required' => false)),
      'pdepo'             => new sfValidatorPass(array('required' => false)),
      'sdepo'             => new sfValidatorPass(array('required' => false)),
      'ssubgrupo'         => new sfValidatorPass(array('required' => false)),
      'psubgrupo'         => new sfValidatorPass(array('required' => false)),
      'usa_tyc'           => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ptallas'           => new sfValidatorPass(array('required' => false)),
      'stallas'           => new sfValidatorPass(array('required' => false)),
      'pcolores'          => new sfValidatorPass(array('required' => false)),
      'scolores'          => new sfValidatorPass(array('required' => false)),
      'multicomis'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'namefac'           => new sfValidatorPass(array('required' => false)),
      'namepre'           => new sfValidatorPass(array('required' => false)),
      'namenot'           => new sfValidatorPass(array('required' => false)),
      'namerec'           => new sfValidatorPass(array('required' => false)),
      'nametrans'         => new sfValidatorPass(array('required' => false)),
      'namerecc'          => new sfValidatorPass(array('required' => false)),
      'namereq'           => new sfValidatorPass(array('required' => false)),
      'namepedv'          => new sfValidatorPass(array('required' => false)),
      'pvende'            => new sfValidatorPass(array('required' => false)),
      'svende'            => new sfValidatorPass(array('required' => false)),
      'sarticulo'         => new sfValidatorPass(array('required' => false)),
      'particulo'         => new sfValidatorPass(array('required' => false)),
      'comiscob'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'integrapag'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'integracob'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'creferenci'        => new sfValidatorPass(array('required' => false)),
      'prcutilfac'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'prcutilpre'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'prcutilnot'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ecostoprom'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'metodoutil'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'integrado'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ruta_cont'         => new sfValidatorPass(array('required' => false)),
      'ruta_rep'          => new sfValidatorPass(array('required' => false)),
      'detallagas'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'compragas'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'preciodef'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cimpuesto1'        => new sfValidatorPass(array('required' => false)),
      'cimpuesto2'        => new sfValidatorPass(array('required' => false)),
      'cimpuesto3'        => new sfValidatorPass(array('required' => false)),
      'ecampo1'           => new sfValidatorPass(array('required' => false)),
      'ecampo2'           => new sfValidatorPass(array('required' => false)),
      'ecampo3'           => new sfValidatorPass(array('required' => false)),
      'ecampo4'           => new sfValidatorPass(array('required' => false)),
      'ecampo5'           => new sfValidatorPass(array('required' => false)),
      'eaplicfac'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'eaplicnot'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'eaplicpre'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'eaplictran'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'eapliccob'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'lcampo1'           => new sfValidatorPass(array('required' => false)),
      'lcampo2'           => new sfValidatorPass(array('required' => false)),
      'lcampo3'           => new sfValidatorPass(array('required' => false)),
      'lcampo4'           => new sfValidatorPass(array('required' => false)),
      'lcampo5'           => new sfValidatorPass(array('required' => false)),
      'laplicfac'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'laplicnot'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'lapliccob'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'laplicpre'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'laplictran'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'eencab'            => new sfValidatorPass(array('required' => false)),
      'lencab'            => new sfValidatorPass(array('required' => false)),
      'contrato'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'homematriz'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'fectranfer'        => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'balanza'           => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comiparam'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'preficon1'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'preficon2'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'suficon1'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'suficon2'          => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'prog_cal'          => new sfValidatorPass(array('required' => false)),
      'prog_back'         => new sfValidatorPass(array('required' => false)),
      'conservdep'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'impuestomaster'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'nameotro'          => new sfValidatorPass(array('required' => false)),
      'codcontivavent'    => new sfValidatorPass(array('required' => false)),
      'codcontventaneta'  => new sfValidatorPass(array('required' => false)),
      'codcontndven'      => new sfValidatorPass(array('required' => false)),
      'codcontncven'      => new sfValidatorPass(array('required' => false)),
      'codcontcaja'       => new sfValidatorPass(array('required' => false)),
      'codcontivacomp'    => new sfValidatorPass(array('required' => false)),
      'codcontnetocomp'   => new sfValidatorPass(array('required' => false)),
      'codcontndcomp'     => new sfValidatorPass(array('required' => false)),
      'codcontnccomp'     => new sfValidatorPass(array('required' => false)),
      'codcontinvbal'     => new sfValidatorPass(array('required' => false)),
      'codcontinvgyp'     => new sfValidatorPass(array('required' => false)),
      'lagencia'          => new sfValidatorPass(array('required' => false)),
      'ldeposito'         => new sfValidatorPass(array('required' => false)),
      'ltallas'           => new sfValidatorPass(array('required' => false)),
      'lcolores'          => new sfValidatorPass(array('required' => false)),
      'lgrupos'           => new sfValidatorPass(array('required' => false)),
      'larticulos'        => new sfValidatorPass(array('required' => false)),
      'lzonas'            => new sfValidatorPass(array('required' => false)),
      'ltipoprov'         => new sfValidatorPass(array('required' => false)),
      'lproveedor'        => new sfValidatorPass(array('required' => false)),
      'ltipocli'          => new sfValidatorPass(array('required' => false)),
      'lclientes'         => new sfValidatorPass(array('required' => false)),
      'llistaban'         => new sfValidatorPass(array('required' => false)),
      'ltarcred'          => new sfValidatorPass(array('required' => false)),
      'ltardeb'           => new sfValidatorPass(array('required' => false)),
      'ltipooper'         => new sfValidatorPass(array('required' => false)),
      'ltiporeten'        => new sfValidatorPass(array('required' => false)),
      'ini_periodo'       => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'fin_periodo'       => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'int_linea_cont'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cons_cont'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'consing'           => new sfValidatorPass(array('required' => false)),
      'consajt'           => new sfValidatorPass(array('required' => false)),
      'conschq'           => new sfValidatorPass(array('required' => false)),
      'distribdsctofinal' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comisobreutil'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'formatofac1'       => new sfValidatorPass(array('required' => false)),
      'formatofac2'       => new sfValidatorPass(array('required' => false)),
      'formatofacb'       => new sfValidatorPass(array('required' => false)),
      'formatofacc'       => new sfValidatorPass(array('required' => false)),
      'formatofacd'       => new sfValidatorPass(array('required' => false)),
      'formatoface'       => new sfValidatorPass(array('required' => false)),
      'formatopre'        => new sfValidatorPass(array('required' => false)),
      'formatonot'        => new sfValidatorPass(array('required' => false)),
      'ali_normal'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ali_reducida'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ali_extendida'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tipocob1name'      => new sfValidatorPass(array('required' => false)),
      'rutacob1pict'      => new sfValidatorPass(array('required' => false)),
      'tipocob2name'      => new sfValidatorPass(array('required' => false)),
      'rutacob2pict'      => new sfValidatorPass(array('required' => false)),
      'tipocob3name'      => new sfValidatorPass(array('required' => false)),
      'rutacob3pict'      => new sfValidatorPass(array('required' => false)),
      'tipocob4name'      => new sfValidatorPass(array('required' => false)),
      'rutacob4pict'      => new sfValidatorPass(array('required' => false)),
      'tipocob5name'      => new sfValidatorPass(array('required' => false)),
      'rutacob5pict'      => new sfValidatorPass(array('required' => false)),
      'tipocob6name'      => new sfValidatorPass(array('required' => false)),
      'rutacob6pict'      => new sfValidatorPass(array('required' => false)),
      'esrestaurant'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'recargo'           => new sfValidatorPass(array('required' => false)),
      'idconsumo'         => new sfValidatorPass(array('required' => false)),
      'sidconsumo'        => new sfValidatorPass(array('required' => false)),
      'cfgvisorlinea1'    => new sfValidatorPass(array('required' => false)),
      'cfgvisorlinea2'    => new sfValidatorPass(array('required' => false)),
      'cfgvisorlinea3'    => new sfValidatorPass(array('required' => false)),
      'cfgvisorlinea4'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'faddinv1'          => new sfValidatorPass(array('required' => false)),
      'faddinv2'          => new sfValidatorPass(array('required' => false)),
      'faddinv3'          => new sfValidatorPass(array('required' => false)),
      'faddinv4'          => new sfValidatorPass(array('required' => false)),
      'faddinv5'          => new sfValidatorPass(array('required' => false)),
      'faddinv6'          => new sfValidatorPass(array('required' => false)),
      'faddinv7'          => new sfValidatorPass(array('required' => false)),
      'faddinv8'          => new sfValidatorPass(array('required' => false)),
      'faddinv9'          => new sfValidatorPass(array('required' => false)),
      'faddinv0'          => new sfValidatorPass(array('required' => false)),
      'faddcli1'          => new sfValidatorPass(array('required' => false)),
      'faddcli2'          => new sfValidatorPass(array('required' => false)),
      'faddcli3'          => new sfValidatorPass(array('required' => false)),
      'faddcli4'          => new sfValidatorPass(array('required' => false)),
      'faddcli5'          => new sfValidatorPass(array('required' => false)),
      'faddven1'          => new sfValidatorPass(array('required' => false)),
      'faddven2'          => new sfValidatorPass(array('required' => false)),
      'faddven3'          => new sfValidatorPass(array('required' => false)),
      'faddven4'          => new sfValidatorPass(array('required' => false)),
      'faddven5'          => new sfValidatorPass(array('required' => false)),
      'faddprov1'         => new sfValidatorPass(array('required' => false)),
      'faddprov2'         => new sfValidatorPass(array('required' => false)),
      'faddprov3'         => new sfValidatorPass(array('required' => false)),
      'faddprov4'         => new sfValidatorPass(array('required' => false)),
      'faddprov5'         => new sfValidatorPass(array('required' => false)),
      'rutareporte'       => new sfValidatorPass(array('required' => false)),
      'rutaquery'         => new sfValidatorPass(array('required' => false)),
      'rutaservidor'      => new sfValidatorPass(array('required' => false)),
      'cfgdecimales'      => new sfValidatorPass(array('required' => false)),
      'version'           => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'patrocinado'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'sservidor'         => new sfValidatorPass(array('required' => false)),
      'pservidor'         => new sfValidatorPass(array('required' => false)),
      'series_name'       => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('config_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Config';
  }

  public function getFields()
  {
    return array(
      'id'                => 'Number',
      'id_empresa'        => 'Text',
      'nrofiscal1'        => 'Text',
      'nrofiscal2'        => 'Text',
      'nomfiscal1'        => 'Text',
      'nomfiscal2'        => 'Text',
      'direccion'         => 'Text',
      'telefonos'         => 'Text',
      'fax'               => 'Text',
      'email'             => 'Text',
      'website'           => 'Text',
      'impuesto1'         => 'Text',
      'impuesto2'         => 'Text',
      'impuesto3'         => 'Text',
      'impuesto4'         => 'Text',
      'impuesto5'         => 'Text',
      'impuesto6'         => 'Text',
      'monnac'            => 'Text',
      'monnacsimb'        => 'Text',
      'monex'             => 'Text',
      'monexsimb'         => 'Text',
      'monnac2'           => 'Text',
      'monnacsimb2'       => 'Text',
      'dividemultiplica'  => 'Number',
      'monedafactor'      => 'Number',
      'aplicabsfuerte'    => 'Number',
      'filefondo'         => 'Text',
      'fondoscr'          => 'Text',
      'logoemp'           => 'Text',
      'redonimpu'         => 'Number',
      'decimales'         => 'Number',
      'metodoround'       => 'Number',
      'tasacambio'        => 'Number',
      'ssector'           => 'Text',
      'psector'           => 'Text',
      'scliente'          => 'Text',
      'pcliente'          => 'Text',
      'sagencia'          => 'Text',
      'pagencia'          => 'Text',
      'scomision'         => 'Text',
      'pcomision'         => 'Text',
      'scomprador'        => 'Text',
      'pcomprador'        => 'Text',
      'namecedula'        => 'Text',
      'namerif'           => 'Text',
      'namenit'           => 'Text',
      'nameref1'          => 'Text',
      'nameref2'          => 'Text',
      'ssuplidor'         => 'Text',
      'psuplidor'         => 'Text',
      'sbanco'            => 'Text',
      'pbanco'            => 'Text',
      'pseccion'          => 'Text',
      'sseccion'          => 'Text',
      'pdepo'             => 'Text',
      'sdepo'             => 'Text',
      'ssubgrupo'         => 'Text',
      'psubgrupo'         => 'Text',
      'usa_tyc'           => 'Number',
      'ptallas'           => 'Text',
      'stallas'           => 'Text',
      'pcolores'          => 'Text',
      'scolores'          => 'Text',
      'multicomis'        => 'Number',
      'namefac'           => 'Text',
      'namepre'           => 'Text',
      'namenot'           => 'Text',
      'namerec'           => 'Text',
      'nametrans'         => 'Text',
      'namerecc'          => 'Text',
      'namereq'           => 'Text',
      'namepedv'          => 'Text',
      'pvende'            => 'Text',
      'svende'            => 'Text',
      'sarticulo'         => 'Text',
      'particulo'         => 'Text',
      'comiscob'          => 'Number',
      'integrapag'        => 'Number',
      'integracob'        => 'Number',
      'creferenci'        => 'Text',
      'prcutilfac'        => 'Number',
      'prcutilpre'        => 'Number',
      'prcutilnot'        => 'Number',
      'ecostoprom'        => 'Number',
      'metodoutil'        => 'Number',
      'integrado'         => 'Number',
      'ruta_cont'         => 'Text',
      'ruta_rep'          => 'Text',
      'detallagas'        => 'Number',
      'compragas'         => 'Number',
      'preciodef'         => 'Number',
      'cimpuesto1'        => 'Text',
      'cimpuesto2'        => 'Text',
      'cimpuesto3'        => 'Text',
      'ecampo1'           => 'Text',
      'ecampo2'           => 'Text',
      'ecampo3'           => 'Text',
      'ecampo4'           => 'Text',
      'ecampo5'           => 'Text',
      'eaplicfac'         => 'Number',
      'eaplicnot'         => 'Number',
      'eaplicpre'         => 'Number',
      'eaplictran'        => 'Number',
      'eapliccob'         => 'Number',
      'lcampo1'           => 'Text',
      'lcampo2'           => 'Text',
      'lcampo3'           => 'Text',
      'lcampo4'           => 'Text',
      'lcampo5'           => 'Text',
      'laplicfac'         => 'Number',
      'laplicnot'         => 'Number',
      'lapliccob'         => 'Number',
      'laplicpre'         => 'Number',
      'laplictran'        => 'Number',
      'eencab'            => 'Text',
      'lencab'            => 'Text',
      'contrato'          => 'Number',
      'homematriz'        => 'Number',
      'fectranfer'        => 'Date',
      'balanza'           => 'Number',
      'comiparam'         => 'Number',
      'preficon1'         => 'Number',
      'preficon2'         => 'Number',
      'suficon1'          => 'Number',
      'suficon2'          => 'Number',
      'prog_cal'          => 'Text',
      'prog_back'         => 'Text',
      'conservdep'        => 'Number',
      'impuestomaster'    => 'Number',
      'nameotro'          => 'Text',
      'codcontivavent'    => 'Text',
      'codcontventaneta'  => 'Text',
      'codcontndven'      => 'Text',
      'codcontncven'      => 'Text',
      'codcontcaja'       => 'Text',
      'codcontivacomp'    => 'Text',
      'codcontnetocomp'   => 'Text',
      'codcontndcomp'     => 'Text',
      'codcontnccomp'     => 'Text',
      'codcontinvbal'     => 'Text',
      'codcontinvgyp'     => 'Text',
      'lagencia'          => 'Text',
      'ldeposito'         => 'Text',
      'ltallas'           => 'Text',
      'lcolores'          => 'Text',
      'lgrupos'           => 'Text',
      'larticulos'        => 'Text',
      'lzonas'            => 'Text',
      'ltipoprov'         => 'Text',
      'lproveedor'        => 'Text',
      'ltipocli'          => 'Text',
      'lclientes'         => 'Text',
      'llistaban'         => 'Text',
      'ltarcred'          => 'Text',
      'ltardeb'           => 'Text',
      'ltipooper'         => 'Text',
      'ltiporeten'        => 'Text',
      'ini_periodo'       => 'Date',
      'fin_periodo'       => 'Date',
      'int_linea_cont'    => 'Number',
      'cons_cont'         => 'Number',
      'consing'           => 'Text',
      'consajt'           => 'Text',
      'conschq'           => 'Text',
      'distribdsctofinal' => 'Number',
      'comisobreutil'     => 'Number',
      'formatofac1'       => 'Text',
      'formatofac2'       => 'Text',
      'formatofacb'       => 'Text',
      'formatofacc'       => 'Text',
      'formatofacd'       => 'Text',
      'formatoface'       => 'Text',
      'formatopre'        => 'Text',
      'formatonot'        => 'Text',
      'ali_normal'        => 'Number',
      'ali_reducida'      => 'Number',
      'ali_extendida'     => 'Number',
      'tipocob1name'      => 'Text',
      'rutacob1pict'      => 'Text',
      'tipocob2name'      => 'Text',
      'rutacob2pict'      => 'Text',
      'tipocob3name'      => 'Text',
      'rutacob3pict'      => 'Text',
      'tipocob4name'      => 'Text',
      'rutacob4pict'      => 'Text',
      'tipocob5name'      => 'Text',
      'rutacob5pict'      => 'Text',
      'tipocob6name'      => 'Text',
      'rutacob6pict'      => 'Text',
      'esrestaurant'      => 'Number',
      'recargo'           => 'Text',
      'idconsumo'         => 'Text',
      'sidconsumo'        => 'Text',
      'cfgvisorlinea1'    => 'Text',
      'cfgvisorlinea2'    => 'Text',
      'cfgvisorlinea3'    => 'Text',
      'cfgvisorlinea4'    => 'Number',
      'faddinv1'          => 'Text',
      'faddinv2'          => 'Text',
      'faddinv3'          => 'Text',
      'faddinv4'          => 'Text',
      'faddinv5'          => 'Text',
      'faddinv6'          => 'Text',
      'faddinv7'          => 'Text',
      'faddinv8'          => 'Text',
      'faddinv9'          => 'Text',
      'faddinv0'          => 'Text',
      'faddcli1'          => 'Text',
      'faddcli2'          => 'Text',
      'faddcli3'          => 'Text',
      'faddcli4'          => 'Text',
      'faddcli5'          => 'Text',
      'faddven1'          => 'Text',
      'faddven2'          => 'Text',
      'faddven3'          => 'Text',
      'faddven4'          => 'Text',
      'faddven5'          => 'Text',
      'faddprov1'         => 'Text',
      'faddprov2'         => 'Text',
      'faddprov3'         => 'Text',
      'faddprov4'         => 'Text',
      'faddprov5'         => 'Text',
      'rutareporte'       => 'Text',
      'rutaquery'         => 'Text',
      'rutaservidor'      => 'Text',
      'cfgdecimales'      => 'Text',
      'version'           => 'Number',
      'patrocinado'       => 'Number',
      'sservidor'         => 'Text',
      'pservidor'         => 'Text',
      'series_name'       => 'Text',
    );
  }
}
