# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Exproaqua - Control Almacen Producción
    description:  Aplicación para el control de almacenes de materia prima para el proceso de producción
    keywords:     Aplicación para el control de almacenes de materia prima para el proceso de producción
    language:     es
    robots:       index, follow

  stylesheets:    [main.css, default.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
